### ISSUE TITLE
Microseconds support for MySQL >= 5.6.4

### ISSUE THREAD

**Issue by lorenzomar** [cakephp/phinx#1003]
Starting from version 5.6.4 MySQL added fractional seconds support for `DATE`, `DATETIME` and `TIMESTAMP` [doc](https://dev.mysql.com/doc/refman/5.6/en/fractional-seconds.html). The standard practice is to use date fields without fractional precision but i suppose it is due to absence of the feature. 
What about to add the `limit` option to date fields too?

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?
