### ISSUE TITLE
renameColumn does not preserve comments on that column

### ISSUE THREAD

**Issue by shawnpyle** [cakephp/phinx#1009]
It appears that if there is a comment on a column, then using a renameColumn on that column, the comment will disappear.

### Environment
PHP 5.6.27 (cli) (built: Oct 15 2016 09:29:55)
Phinx by Rob Morgan - https://phinx.org. version 0.6.4
CentOS release 6.5 (Final)
Linux www.jci.dev 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yashtodi94** [comment]
[#1063](https://github.com/robmorgan/phinx/pull/1063) should solve this problem
