### ISSUE TITLE
MysqlAdapter: getColumns() doesn't return precision and scale for decimal

### ISSUE THREAD

**Issue by MarkoNV** [cakephp/phinx#1013]
Migration:

```
$table = new Table('test', [], $this->adapter);
$table->addColumn('dec', 'decimal', array('precision' => 10, 'scale' => 2));
$table->save();
```
Decimal(10,2) column is successfully created, but:
`var_dump($table->getColumns()); `
returns:
```
array (size=2)
  0 => 
    object(Phinx\Db\Table\Column)[35]
      protected 'name' => string 'id' (length=2)
...
  1 => 
    object(Phinx\Db\Table\Column)[34]
      protected 'name' => string 'dec' (length=3)
      protected 'type' => string 'decimal' (length=7)
      protected 'limit' => **int 10**
      protected 'null' => boolean false
      protected 'default' => null
      protected 'identity' => boolean false
      protected 'precision' => **null**
      protected 'scale' => **null**
      protected 'after' => null
      protected 'update' => null
      protected 'comment' => null
      protected 'signed' => boolean true
      protected 'timezone' => boolean false
      protected 'properties' => 
        array (size=0)
          empty
      protected 'values' => null
```
_Since DECIMAL(M) is equivalent for DECIMAL(M,0), precision could be alias for limit, but scale is still missing. getPhinxType returns limit and scale, but it's not assigned to Column class if column type is decimal._ -> additional mistake, see edit.

Edit: Column definition for decimal is DECIMAL (precision, scale), but when parsing existing column data, it's parsed as DECIMAL (limit, precision). Same applies to SQLiteAdapter.

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?

**Comment by ricardoapaes** [comment]
I have the same problem, has it already been resolved?

**Comment by martijngastkemper** [comment]
PR #1258 doesn't solve the problem. I'm currently working on a PR to fix the parsing of `DECIMAL`. Hopefully no backwards compatibility problems 🤞
