### ISSUE TITLE
FK drop doesn't work (MySQL)

### ISSUE THREAD

**Issue by sergeolkhovik** [cakephp/phinx#1023]
Have a code like this:

        $t = $this->table('jobsportal_resume_edu');
        $t->dropForeignKey('FK_jobsportal_resume_edu_jobsportal_edu');
        $this->dropTable('jobsportal_edu');

when I run migration, it crashes at last line.
As a workaround I did:
        $this->execute('alter table jobsportal_resume_edu drop foreign key FK_jobsportal_resume_edu_jobsportal_edu');
That worked.

**Comment by yashtodi94** [comment]
Dropping a foreign key in phinx doesn't work that way. Your syntax should be:

```
$t = $this->table(<table_name>);
$t->dropForeignKey(<name_of_the_column_which_is_the_foreign_key>)
->save();
```
Refer to: http://docs.phinx.org/en/latest/migrations.html#working-with-foreign-keys

**Comment by sergeolkhovik** [comment]
Yes, I was wrong, thank you!
