### ISSUE TITLE
Reapply Phinx migrations on a source code deployment rollback

### ISSUE THREAD

**Issue by piqoni** [cakephp/phinx#1031]
Hi, 
Is there any way to rollback the migrations that are missing? (that are deleted by a deployment rollback, for example).

In that case, we could rollback the deployment code safely, having added the `phinx migrate` command to always run automatically after deployment, code & db schema would always match. Any idea/workaround would be appreciated.

**Comment by piqoni** [comment]
So, don't know if a good idea but, what if we save the php migration code in the phinxlog table for each migration, and we restore the file and perform the rollback when the migration is missing.

**Comment by rquadling** [comment]
Not all phinx migrations would be feasible to be stored in any meaningful way. Data fixing migrations that have to run through multiple steps and/or rely on external sources, for example, could result in significant complexity.

As a further example, our migrations files tend to be stubs with the main behaviour abstracted away in other files. Rolling back code would delete the ancillary files.

There are a couple of features being discussed and are specifically about automated deployment and rollback.

https://github.com/robmorgan/phinx/issues/1044 and https://github.com/robmorgan/phinx/issues/1046

Both are about my organisations use of Phinx and hopefully will be defined well enough to be of real use to a large number of people.

Take a look at these, if you think you have anything to contribute to the specific ideas, please do. Getting more feedback from users will allow us to add the appropriate functionality.

**Comment by dereuromark** [comment]
Discussion can then continue in those linked issues.
