### ISSUE TITLE
Mysql::TEXT_REGULAR make the column 'unique, primary, index, spatial'

### ISSUE THREAD

**Issue by codedigs** [cakephp/phinx#1034]
->addColumn('large_description', 'text', array('limit' => MysqlAdapter::TEXT_REGULAR))

When I use MysqlAdapter::TEXT_REGULAR, the column would be unique, primary, index, and spatial.
Is there anybody encounter this ? thanks

**Comment by dereuromark** [comment]
Is this still an issue?
Any more details you can offer?
