### ISSUE TITLE
Migration Problem

### ISSUE THREAD

**Issue by pogs17** [cakephp/phinx#1066]
Hello Guys,

I'm having a problem during the migration process using the following command. 
"cake migrations migrate -p Acl "

![capturar](https://cloud.githubusercontent.com/assets/5427892/24230762/798bce52-0f5f-11e7-8cc2-6d839d4aea8e.PNG)

I'm using SQL Server v11.0.6020;

Any tip?

Thanks in advance!

Pedro

**Comment by rquadling** [comment]
A couple of points.

I don't speak French, so don't know that the error is saying exactly.

Looking at the output, it looks like you have some sort of issue inserting data. It looks like it is trying to convert a string to a datetime and failing. Can you provide your migration please.

What version of Phinx are you using as part of Cake?

**Comment by daison12006013** [comment]
@pogs17 are you trying to connect to SQL Server? since phinx doesn't support it based on the adapters that we have.

**Comment by rquadling** [comment]
@daison12006013 why do you think Phinx doesn't support MSSQL?

**Comment by daison12006013** [comment]
My mistake @rquadling, before it doesn't support the mssql, but upon checking the adapters, it's already there, sorry for misleading.

https://github.com/robmorgan/phinx/blob/master/src/Phinx/Db/Adapter/SqlServerAdapter.php

**Comment by tolidano** [comment]
Back to the original issue - that isn't French, it's Portuguese. And you are correct that there is a seed insertion into the acl table with an invalid date.

If you paste all the dates you are inserting, that might help (not the entire seed, if that's an issue). My guess would be some sort of time formatting issue (especially if you're using the built-ins to handle creating the dates) against whatever time format your MS SQL Server is set to use. Perhaps try explicit dates?

**Comment by dereuromark** [comment]
No feedback.
