### ISSUE TITLE
MySQL FEDERATED tables

### ISSUE THREAD

**Issue by VitalyOrbit** [cakephp/phinx#1068]
I didn't found support for federated tables (for the MySQL adapter).
I can specify engine='federated', but I'm not able to specify CONNECTION='mysql://USER:PASSWORD@HOST/DB/TABLE'.

Is it possible to do (and I missing about that in the docs) or will be supported in future?

**Comment by daison12006013** [comment]
I think we can't, since PDO doesn't support this (I guess). In the pdo class, we usually call it this way when we instantiate.

```
new PDO("mysql:host=localhost;dbname=mydb", 'someuser', 'somepass')
```

Maybe a new feature to switch @robmorgan 

```
$this->switchToDatabase('some_table_here');
$this->switchToDefault();
```

**Comment by VitalyOrbit** [comment]
Ofcourse federated tables can be replaces by MASTER-MASTER or MASTER-SLAVE replication.
But FEDERATED tables can be useful for big tables if server space is limited.

In my case I use that tables in JOINs. And referenced tables are placed in an external server.

I agree that is not a major issue and can be solved by another ways. Also this feature may not be useful for most of developers.

Thanks.

**Comment by dereuromark** [comment]
Without further interest closing then due to the edge case scenario.
