### ISSUE TITLE
Call to undefined method Phinx\Util\Util::globAll() 

### ISSUE THREAD

**Issue by okneloper** [cakephp/phinx#1074]
Running `phinx migrate` gives me this:

Fatal error: Call to undefined method Phinx\Util\Util::globAll() in /home/involvme/.composer/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php on line 103

This is potentially because I have phinx 0.6.5 installed as a local dependency and 0.8.0 as global, so the global executable somehow autoloads the local files.

**Comment by daison12006013** [comment]
you may use ./vendor/bin/phinx inside your relative path of your project @okneloper

**Comment by okneloper** [comment]
Thanks @daison12006013, I've solved that for my particular case, but the issue overall is still a bug, what do you think?

**Comment by daison12006013** [comment]
Yeah it is still a bug since it is a command, there should be some checking in 0.6.x to check the version for compatibility. to limit only to the same version area 0.6.*, as well for future versions.

**Comment by dereuromark** [comment]
Are you able to provide a patch with your suggested changes as PR?
