### ISSUE TITLE
adapter not available in init()

### ISSUE THREAD

**Issue by glensc** [cakephp/phinx#1095]
i would like to do some common init, like escaping fields and table names, so `up` and `down` could reuse them. `protected function init() {}` seemed right place to do that.

however, `$this->getAdapter()` returns `null` at the time `init()` is invoked:

```php
class SuperCoolMigration extends AbstractMigration
{
    public function init()
    {
        $this->email_table = $this->getAdapter()->quoteColumnName('support_email');
        $this->body_table = $this->getAdapter()->quoteColumnName('support_email_body');
    }
```

**Comment by dereuromark** [comment]
Any update from the team here?
