### ISSUE TITLE
Ordering for database seeding

### ISSUE THREAD

**Issue by jettlin** [cakephp/phinx#1096]
Currently there is no way of saying that one file needs to be run before another in the files themselves.  It would be nice to be able to have a timestamp associated with a seed file name or some sort of command to make sure that certain files are run before others so that migrations can be run in a specific order.  As the functionality exists right now you have to change the name of the seeder based on the order you want it to run based on foreign key constraints.  Migrations don't have this issue because the timestamp at the beginning of the file help to specify the order the files get executed in.  This means that for migrations if there is a foreign key that it is guaranteed the table exists before hand.  However, with seeding that is not guaranteed and the data does not necessarily get inserted into the database in order.

**Comment by josiahaltschuler** [comment]
I agree. Errors may occur based on the loading order of seed files. Curious to know how others solve this when loading all seed files. Are you designating the order of the files alphabetically, or do you just manually load each seed file one by one, paying attention to the order as you go?

**Comment by piotr-cz** [comment]
I've created a bash script `bin\db-reset.sh` to do a [rollback](https://github.com/robmorgan/phinx/issues/1059) and run seeds in defined order

```sh
./phinx rollback -t 0
./phinx seed:run -s ClientsSeeder -s EntityTypesSeeder
./phinx seed:run -s MockValuesSeeder
```

**Comment by emptyhand** [comment]
Hey, I created pull request for seeds ordering feature:
https://github.com/cakephp/phinx/pull/1244

Please review my pull request and comment if you like it.

**Comment by iamuzor** [comment]
For anyone still struggling with this, here is what I did (that required little work);

1. Create a seeder, in its `run()` method, loop through the other seeder classes and trigger their `run()` method. See code snippet below:

`
<?php

use Phinx\Seed\AbstractSeed;

class MainSeeder extends AbstractSeed
{
    // the classes in the $seederClasses should be ordered the way you want it executed
    protected $seedClasses = [
        UserTypeSeeder::class,
        UserSeeder::class,
    ];

    public function run()
    {
        foreach ($this->seedClasses as $seedClass) {
            /** @var AbstractSeed $seeder */
            $seeder = new $seedClass;
            $seeder->setAdapter($this->getAdapter()); // this is required to set the database connection
            $seeder->run();
        }
    }
}

`

2. In your terminal run the command `phinx seed:run -s MainSeeder`

3. You're done.

**Comment by mehov** [comment]
This shows up in search results. Thanks to cakephp/phinx#1244, you can now use `getDependencies()`. Here's how: https://github.com/cakephp/phinx/blob/a96c5465a8f3dd64e39c9115a5d383b8d01928ce/tests/Phinx/Migration/_files/seeds/PostSeeder.php

**Comment by phlanglois** [comment]
Still showing up in the results, but I feel like pointing to the official doc is more reliable : https://book.cakephp.org/phinx/0/en/seeding.html

# Foreign Key Dependencies
> Often you’ll find that seeders need to run in a particular order, so they don’t violate foreign key constraints. To define this order, you can implement the getDependencies() method that returns an array of seeders to run before the current seeder:

```php
<?php

use Phinx\Seed\AbstractSeed;

class ShoppingCartSeeder extends AbstractSeed
{
    public function getDependencies()
    {
        return [
            'UserSeeder',
            'ShopItemSeeder'
        ];
    }

    public function run() : void
    {
        // Seed the shopping cart  after the `UserSeeder` and
        // `ShopItemSeeder` have been run.
    }
}
```

> Dependencies are only considered when executing all seed classes (default behavior). They won’t be considered when running specific seed classes.
