### ISSUE TITLE
Rollback "no migrations to rollback" or "target version () not found"

### ISSUE THREAD

**Issue by omag0** [cakephp/phinx#1097]
Hello guys. When i execute rollback, show me this erros:
- no migrations to rollback
or when i put rollback -t=migration_id
- target version() not found

I execute migrate first, and show this:

using config file .\phinx.php
using config parser php
using migration paths
 - C:\Users\rodri\OneDrive\Documentos\Visual Studio 2017\Projects\Son\Son\db\migrations
using seed paths
 - C:\Users\rodri\OneDrive\Documentos\Visual Studio 2017\Projects\Son\Son\db\seeds
warning no environment specified, defaulting to: development
using adapter mysql
using database son_financas

 == 20170523110151 CreateCategoryCosts: migrating
 == 20170523110151 CreateCategoryCosts: migrated 0.0732s

All Done. Took 0.0923s

Anyone can help me?

**Comment by rquadling** [comment]
There was a bug when only 1 migration existed (https://github.com/cakephp/phinx/pull/1060).

This was fixed and released in https://github.com/cakephp/phinx/releases/tag/v0.8.1

Can you please retest.

**Comment by lorenzo** [comment]
Closing as this has already been fixed. Please do tell us if the most recent release does not fix your issue so we can reopen this thicket.
