### ISSUE TITLE
Documentation: Reference manual is missing

### ISSUE THREAD

**Issue by jkufner** [cakephp/phinx#1099]
Every class, method, and function should link to a reference manual, where the API is described in detail. Currently, it is hard to determine what exactly the method does and what arguments it takes as there are not enough details in the examples.

For example -- http://docs.phinx.org/en/latest/migrations.html:

> When creating or updating tables inside a change() method you must use the Table create() and update() methods. Phinx cannot automatically determine whether a save() call is creating a new table or modifying an existing one.

So, what create() does? What other methods I can call? What exactly save() does?

If save() was a link to reference manual, I could get the answer in one click.

**Comment by dereuromark** [comment]
Maybe someone can PR an improvement to docs here.
