### ISSUE TITLE
Creating a primary key for a table that had none before

### ISSUE THREAD

**Issue by burzum** [cakephp/phinx#1112]
This is probably more of a documentation issue: I could not figure out how to create a primary key for a table that (by accident) was missing the PK. I've tried all options I could find that are related to it. But when running this migration

```php
		$this->table('wa_project_partner_companies_translations', [
				'id' => 'id',
				'primary_key' => 'id',
				'identity' => 'id'
			])
			->addColumn('project_partner_company_id', 'integer',  ['null' => false])
			->addIndex(['locale', 'project_partner_company_id'], ['unique' => 'true', 'name' => 'UNIQUE_TRANSLATION'])
			->addIndex(['locale'])
			->addIndex(['project_partner_company_id'])
			->update();
```

my table is still missing the PK.

It would be nice if there would be a method lie `addPrimaryKey` and `removePrimaryKey`.

**Comment by lulco** [comment]
I think this is duplicity of #335

**Comment by burzum** [comment]
Yes it is. What do you think about adding these two methods?

**Comment by lulco** [comment]
I vote for it, so now we have to wait :)
