### ISSUE TITLE
Dropping `array()` in favor of `[]` syntax in docs

### ISSUE THREAD

**Issue by MarcinOrlowski** [cakephp/phinx#1115]
As Phinx requires PHP 5.4, docs should fully drop use of `array()` and use short syntax instead for better redability. For now some parts of docs still use `array()` while other `[]`'s

**Comment by JayPHP** [comment]
@MarcinOrlowski Could you create a PR for this please?

**Comment by MarcinOrlowski** [comment]
I could but there're 45 opened pull requests in this repo and some are pretty ancient. Frankly it does not encourage to create new one, just to stay in queue for know-know how long. Can you work on that first so we can see it's worth the effort to contribute to the project?

**Comment by lorenzo** [comment]
@MarcinOrlowski CakePHP recently took ownership of this project. We are trying to go over the backlog and be faster at responding issues and merging pull requests.

If you send a PR with that change I'll be very glad to merge it right away :)

**Comment by MarcinOrlowski** [comment]
Here you go: https://github.com/cakephp/phinx/pull/1177

**Comment by JayPHP** [comment]
There's a lot more uses of array() in the codebase, tests and docs. Will look at this myself if I get a chance, but if anyone wants to submit a PR in the meantime, please do.

**Comment by lorenzo** [comment]
@JayPHP only take care of the code for now, not the docs

**Comment by MarcinOrlowski** [comment]
I did changes in files in docs folder only. I will check if i missed anything.

**Comment by dereuromark** [comment]
Thank you, you can then just open a PR.
