### ISSUE TITLE
Make create and update return $this

### ISSUE THREAD

**Issue by eGust** [cakephp/phinx#1124]
Migration comment shows:
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey

```PHP
class CreateUsers extends AbstractMigration
{
	public function change()
	{
		$this->createTable('users')->save();
	}
}
````

It gets:
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method CreateUsers::createTable()
```
Where is `createTable`?

**Comment by JayPHP** [comment]
`$this->table('tableName')->create()` works.

Looks like annotation and docs need to be updated

**Comment by tariquesani** [comment]
@JayPHP would you be interested in sending a pull request after changing the docs? You can do it from the link on top right on http://docs.phinx.org/en/latest/

**Comment by eGust** [comment]
And could you please make `\Phinx\Db\Table@create` returns `$this`?
Now I must write:
```PHP
$this->table('users')->create();
$this->table('users')
     ->addColumn('password', 'string')
     // ...
     ->save();
```
Otherwise I must write `dropTable` in `down()` method.

I think this way would be better:
```PHP
$this->table('users')
     ->create()
     ->addColumn('password', 'string')
     // ...
     ->save();
```

**Comment by JayPHP** [comment]
@tariquesani @eGust Sure, I'll try and find the time and PR once done.

**Comment by JayPHP** [comment]
@eGust Just call create() at the end.

```
$this->table('users')
     ->addColumn('password', 'string')
     ->create()
```

but yes, it should probably return $this.

**Comment by dereuromark** [comment]
Should be fixed in master.
