### ISSUE TITLE
Implement rollback --all feature to rollback all migrations

### ISSUE THREAD

**Issue by lomholdt** [cakephp/phinx#1128]
It would be super handy to be able to rollback all the migrations in one command.
Currently I either have to `bin/cake migrations rollback` for every migrations, or I have to rollback to a specific timestamp by doing a `bin/cake migrations rollback -t 0`. Suggestion is to add a `--all` option to the `rollback` command, that performs a rollback on all the migrations. 

Also having a `refresh` command that performs a `rollback --all` and then migrates could be super handy for development. Even cooler would be to extend this feature with an optional `--seed` that also seeds the database after a `rollback->migrate` has been performed.

**Comment by twoSeats** [comment]
All of this seconded & would make Phinx a real joy to use. Very eager to see `refresh --seed` in particular, it's super useful.

**Comment by lorenzo** [comment]
I'm waiting for this PR to be finished so we can reuse the logic to add `--all` https://github.com/cakephp/phinx/pull/945

**Comment by knobel-dk** [comment]
Eager to use this.

**Comment by daniel-gomes-sociomantic** [comment]
As per http://docs.phinx.org/en/latest/commands.html#the-rollback-command you can rollback all migrations via:
```
phinx rollback -e development -t 0
```

**Comment by dereuromark** [comment]
So this can be closed then as a solution is available.

**Comment by lomholdt** [comment]
Yeah, the timestamp rollback thing is just semantically not very nice. Thanks though.

**Comment by dereuromark** [comment]
@lomholdt Are you able to provide a PR with your semantically improved version of this enhancement?

**Comment by lomholdt** [comment]
I can give it a go. Thanks @dereuromark .
