### ISSUE TITLE
Table prefix on foreign key

### ISSUE THREAD

**Issue by indiwine** [cakephp/phinx#1134]
I am using table prefixes in my project and everything goes just fine until I decide to add a foreign key to table that already exist.

This code has been failed with `SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint`:

    $table = $this->table('documents');
    $table->addForeignKey('version_id', 'documents_versions', 'id',
            ['delete'=> 'CASCADE', 'update'=> 'CASCADE'])
            ->update();`

Command `SHOW ENGINE INNODB STATUS;` show a problem:

    FOREIGN KEY (`version_id`) REFERENCES `documents_versions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE:
    Cannot resolve table name close to:
     (`id`) ON DELETE CASCADE ON UPDATE CASCADE 

So adding a prefix works fine for me (but obviously its a bug):

    $table->addForeignKey('version_id', 'ema_documents_versions', 'id',
            ['delete'=> 'CASCADE', 'update'=> 'CASCADE'])
            ->update();

I am using version `0.8.1` installed with composer.

**Comment by lorenzo** [comment]
Are you sure about this? Mysql can only complaint when creating references to tables that do not exist, not the opposite

**Comment by indiwine** [comment]
Yes, I am sure. I can reproduce this behavior at any time.
I did not fully understand what do you mean "Mysql can only complaint when creating references to tables that do not exist, not the opposite"? How is it possible to crate reference on table that does not exsisit?

**Comment by indiwine** [comment]
Sorry, I have clicked a wrong bottom. So, the problem not with the reference itself, problem with the prefix.

**Comment by indiwine** [comment]
Please, check out my description again. I am using prefix `ema_`. While I just add new tables and columns everything worked fine for me.
BUT, once I have deicide to add  new foreign key for TABLE THAT ALREADY EXIST:
1. This doesn't work: `$table->addForeignKey('version_id', 'documents_versions', ... `
2. But this one: `$table->addForeignKey('version_id', 'ema_documents_versions', ... ` worked fine.

Booth cases has same configuration, but in the second one I should manually add prefix.
This is not a big problem to me, but its a bug. That is why I am writing here.

PS. Sorry for my bad English.

**Comment by lorenzo** [comment]
oh, you are using the automatic table prefix feature? Is that the case?

**Comment by indiwine** [comment]
Yes.

**Comment by lorenzo** [comment]
Thanks for the clarification

**Comment by indiwine** [comment]
You are welcome

**Comment by dereuromark** [comment]
Are you able to make a PR to fix things? That would be the quickest solution to this issue.

**Comment by indiwine** [comment]
Yes, I can do that.

**Comment by lorenzo** [comment]
I think this is working correctly in the new 0.10.0 version
