### ISSUE TITLE
What the real advantage of your fetchRow()?

### ISSUE THREAD

**Issue by VijitCoder** [cakephp/phinx#1135]
Hi.

As I can see in the [manual](http://docs.phinx.org/en/latest/migrations.html#fetching-rows):

> // fetch a user
> $row = $this->fetchRow('SELECT * FROM users');

This example is bad in several senses. Selection of all users, but then take only first of them - unprofitable. Nevertheless, I suggested, that `fetchRow()` works the same as `PDOStatement::fetch()`. I mean, I can use this method for traversing all records of the query. But it doesn't! Your implementation `PdoAdapter::fetchRow()` always execute the query and as a consequence returns **the first row** of the query **on every call** of `fetchRow()`.

So, what's the point of using this function?

**Comment by lorenzo** [comment]
Would you like to send a pull request to the docs to include a better example?

**Comment by VijitCoder** [comment]
I would, but first I need to understand the purpose of this method. Do you realy want always to get the first row or it just a bug in the code?

**Comment by lorenzo** [comment]
It looks like the idea is to always get the first row.

**Comment by VijitCoder** [comment]
Hm.. Pretty strage idea :) But I found using of this method in Phinx sources it self. Yeap, apparently it works as implemented. I will give an example later, if I do not forget about it.

**Comment by lorenzo** [comment]
I will close this. I think the new query builder interface is better than this.
