### ISSUE TITLE
Cockroach DB support discussion

### ISSUE THREAD

**Issue by twmbx** [cakephp/phinx#1136]
I was working on testing out [Cockroach](https://www.cockroachlabs.com) for a new project this week and needed to make some tweaks to the Phinx Postgres Adaptor to get it to work.
Roach [supports the pgsql connector](https://www.cockroachlabs.com/docs/stable/install-client-drivers.html) but because of the implementation of their [SQL grammar](https://www.cockroachlabs.com/docs/stable/sql-statements.html) there are a couple of quirks that needed to be catered for before I could use Phinx to run migrations.

Before submitting a pull request with a whole new Adaptor I wanted to show the changes I made and get feedback on what would be the best way to solve for this use case, particularly because the changes are so minimal between the Adaptors.

The changes that I made can be viewed in the revision diff of the following Gists:
[PdoAdaptor.php Gist](https://gist.github.com/twoSeats/c1be0024880fab57b2fbd9b0fc1b61f3/revisions)
[CockroachAdaptor.php Gist](https://gist.github.com/twoSeats/67e459c0b240a4274c0458c23756bcde/revisions)

What would be the best way to get Roach DB support into Phinx?
Thoughts & feedback?

**Comment by lorenzo** [comment]
The best way to get feedback is to open a new pull request. I think it could be interesting to explore adding support to it

**Comment by twoSeats** [comment]
@lorenzo alright, I'll do that.

**Comment by twoSeats** [comment]
Arrived at the point of needing to write tests & realised that it would kind of be pointless as [travis doesn't support Cockroach DB at the moment](https://docs.travis-ci.com/user/database-setup/).

Not sure how to proceed at this point so I'm going to wait for more input before submitting a pull request.
fyi: @lorenzo

**Comment by lorenzo** [comment]
can it be installed with docker?

**Comment by twoSeats** [comment]
[It can be](https://hub.docker.com/r/cockroachdb/cockroach/), but I have no hands on knowledge regarding Docker use.

**Comment by dereuromark** [comment]
PR welcome.
