### ISSUE TITLE
0.8.1 default_migration_table ignored

### ISSUE THREAD

**Issue by cottton** [cakephp/phinx#1140]
Since updating to 0.8.1 the `default_migration_table` offset gets ignored(?).

all the sudden we got the default `phinxlog` table and migrations gets executed again.

Switching to 0.8.0 works as expected.

    [
        'phinx' => [
            'paths'        => [
                'migrations' => //...,
                'seeds'      => //...,
            ],
            'environments' => [
                'default_migration_table' => 'migrations', // <-- gets ignored
                'default_database'        => //...,
                'default'                 => [
                    'adapter'                 => //...,
                    'host'                    => //...,
                    'name'                    => //...,
                    'user'                    => //...,
                    'pass'                    => //...,
                    'port'                    => //...,
                    'charset'                 => //...,
                    'collation'               => //...,
                    'mysql_attr_init_command' => //...,
                ]
            ]
        ]
    ]

**Comment by Korri** [comment]
Same issue here, narrowed it down to commit to this change: https://github.com/cakephp/phinx/commit/4464b2832859715e245d29da7cda61c6454ced89#diff-1ba3851ff60f2161d4cf1849606cd4a3L111 the `default_migration_table` is not taken into account in the new `BaseAdapter` class

**Comment by JayPHP** [comment]
#1167 merged. Thanks for letting us know.
