### ISSUE TITLE
PHPUnit integration for memory database

### ISSUE THREAD

**Issue by Grafikart** [cakephp/phinx#1146]
This is quite a specific use case but I can't make phinx works with PHPUnit.
I read the [this issue](https://github.com/cakephp/phinx/issues/548) and I wrote my test this way (I put everything in the same method to make the problem simple).

```php
class DemoTest extends TestCase {

    public function testDatabase () {
        // We want to use SQLlite in memory
        $pdo = new PDO("sqlite::memory:", null, null, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ]);

        // Use Phinx programatically (which use memory too)
        $app = new PhinxApplication();
        $app->setAutoExit(false);
        // Having a way to add PDO to the command will solve the issue
        $app->run(new StringInput('migrate'), new NullOutput());

        // My test
        $posts = $pdo->query('SELECT * FROM posts')->fetchAll();
        $this->assertEquals([], $posts);
    }

}
```

Since there is no way to give PDO to phinx, we can't use the memory database (since it's empty for every connection). A solution (I can do a PR if needed) would be to add the option PDO::ATTR_PERSISTENT for the instance used by Phinx

**Comment by Grafikart** [comment]
I dived deeper into the code and ended up with a solution 

```php
        $pdo = new PDO('sqlite::memory:', null, null,
            [
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_BOTH,
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
            ]);
        $config = require('phinx.php'); // My configuraiton is written in php so it's easier
        $config['environments']['test']['connection'] = $pdo;
        $config = new Config($config);
        $manager = new Manager($config, new StringInput(' '), new NullOutput());
        $manager->migrate('test');
        $manager->seed('test');
```

Using the manager directly is much simpler than creating a fake command, and you can share the PDO

**Comment by HavokInspiration** [comment]
@Grafikart It is actually the only way to do it and what I would have suggested you to do.
The cakephp/migrations test suite uses this trick to "fixate" the PDO instance used during the tests, otherwise we encounter the same problem you are having.

This can be closed.

**Comment by Grafikart** [comment]
I close the issue and I'll try to find some time to document this if someone need it.

**Comment by HavokInspiration** [comment]
@Grafikart Thanks for giving some feedback on your own issue :smile: And a note in the doc would indeed be appreciated.
