### ISSUE TITLE
symfony console version

### ISSUE THREAD

**Issue by adeptofvoltron** [cakephp/phinx#1149]
need changes:
Hi! I'am just creating an new migration module for magento2, based on phinx.
But got a silly issue. Magento2 require symfony console in v.2.6.13
You require up from 2.8
Is it possible to make minimum required version of symfony console lower ?

**Comment by mvrhov** [comment]
I recommend having this with separate dependencies. Otherwise the magento will pull you down more and more as they won't upgrade their dependencies.

**Comment by adeptofvoltron** [comment]
Seperate dependency via composer?

**Comment by lorenzo** [comment]
Not possible, we depend on some newer features of the CLI component

**Comment by adeptofvoltron** [comment]
ok. thx.
