### ISSUE TITLE
Display exceptions and errors in migrations

### ISSUE THREAD

**Issue by michalsvec** [cakephp/phinx#115]
It happened to me that I had mistake in a query executed by execute method, but the error was not displayed. 

Is it possible to throw an exception if this error occurs?

Thank you!

**Comment by NickBelhomme** [comment]
same issue here but in the change() method.

**Comment by qyanu** [comment]
@robmorgan i just now experience a similar error. although I did not yet find the typo/error, something in the migrations/xxx.php files causes php to fatal (opposed to just an exception) and it is not shown in the console.
i tried to track the issue down: which part eats the error or where the output might not be flushed etc. but I couldn't yet find anything concrete. However, i suspect that symfony/console might play a part.

with me the symptom is as such, that the migration just stops mid-air:
```
Phinx by Rob Morgan - https://phinx.org. version 0.6.2

using config file ./etc/phinx.php
using config parser php
using migration path /path/to/migrations
using seed path /path/to/seeds
using environment default
using database xxx
```

and that's it...

and I would suggest not discarding output from the config file (`ob_end_clean` in Config.php) but to output it instead. Generelly i would never throw away output, it might contain some error message.

**Comment by qyanu** [comment]
Seems I have to humbly retract my previous comment as a whole. Turns out, that  having something different from ones believes defined in the php.ini file leads to wrong conclusions.

**Comment by rquadling** [comment]
PDO + multiple queries handles errors differently.

Each statement has its own set of results. That includes its errors.

In PDO, you need to get the next row set on the statement (http://php.net/manual/en/pdostatement.nextrowset.php) and then you can access the errors (and results if appropriate) for that row set.

Currently Phinx doesn't do this (https://github.com/robmorgan/phinx/issues/894).

**Comment by lorenzo** [comment]
This was fixed in https://github.com/cakephp/phinx/pull/1122
