### ISSUE TITLE
Incomplete docs

### ISSUE THREAD

**Issue by MadeRelevant** [cakephp/phinx#1150]
I was looking for a way to use phinx within my phpunit integration tests and found this page: http://docs.phinx.org/en/latest/commands.html.
Unfortunately no example code is provided how to use phinx within your tests. 

In the meanwhile I will look into the tests of phinx self and look for a way to use it without the command line. If I have time I could update the readme.

**Comment by JayPHP** [comment]
@MadeRelevant Could you give a bit more information as to what you were specifically trying to do please?

**Comment by MadeRelevant** [comment]
Hi JayPHP,

Sure. At the moment the docs are updated and it is much clearer how to use Phinx programmatically.
Before the docs were updated I came up with the following:

```php
<?php

class SomeTest extends SomeAbstractMigrationTest {

function setUp() {
$migration = new class(1) extends AbstractMigrator {
            public function up()
            {
                   /* Your usual stuff */
            }

            public function down()
            {
                   /* Your usual stuff, probably just a drop table within tests */
            }
        };

        $input = new StringInput(null);
        $dbAdapter = new MysqlAdapter([
            'charset' => 'utf8',
            'name' => getenv('MYSQL_DATABASE'),
            'host' => getenv('MYSQL_HOST'),
            'user' => getenv('MYSQL_USER'),
            'pass' => getenv('MYSQL_PASSWORD')

        ], $input);
        $dbAdapter->setSchemaTableName('patchhistory_global');
        $migration->setAdapter($dbAdapter);

        $migration->up();
        // register the migration so it can be rollbacked automatically in tearDown()
        $this->migrations[] = $migration;
}

protected function tearDown()
    {
        parent::tearDown();
        foreach ($this->migrations as $migration) {
            $migration->down();
        }
    }

}
```
I have some EAV implementation where new entity types require some meta tables so in my tests I wan't to fake having X number of entity types with their corresponding tables, thats the reason behind this requirement.

In case this could be done much better or easier please let me know. Until further response I'll close the issue.
