### ISSUE TITLE
Logic to always show version information breaks autocomplete tools, duplicates output on list command

### ISSUE THREAD

**Issue by dominics** [cakephp/phinx#1162]
There's [some code in the PhinxApplication](https://github.com/cakephp/phinx/blob/master/src/Phinx/Console/PhinxApplication.php#L78) that is intended to ensure the app name and version string (`Phinx by CakePHP - https://phinx.org. 0.8.x` or similar)  is always displayed in output:

```php
if (false === $input->hasParameterOption(array('--help', '-h')) && null !== $input->getFirstArgument()) {
    $output->writeln($this->getLongVersion());
    $output->writeln('');
}
```

This decision causes a couple of issues.

1. A minor issue, but the `list` command causes this output to be duplicated:
    ```
    Phinx by Rob Morgan - https://phinx.org. 0.8.1

    Phinx by Rob Morgan - https://phinx.org. 0.8.1

    Usage:
      command [options] [arguments]
    ```

2. Related to the first, but more annoying, this breaks tools that generate autocomplete information for Console-based commands, such as [symfony-console-autocomplete](https://github.com/bamarni/symfony-console-autocomplete). Running the tool gives an error like `[Symfony\Component\Console\Exception\CommandNotFoundException] Command "Phinx" is not defined.` because the version information isn't expected except where it appears by default (`-V`, `--version`, `phinx list`).

Adding an option or environment variable to disable this output would allow me to generate autocomplete information for Phinx nicely.

(By the way, I can't see the version information being output for a `--help` or `-h` anyway, so I'm not sure that the first part of the if condition is correct either.)

**Comment by lorenzo** [comment]
would you like to send a pull request with a fix for this issue?

**Comment by dereuromark** [comment]
@dominics A PR would be most welcome.
