### ISSUE TITLE
Revert #1117 

### ISSUE THREAD

**Issue by mvrhov** [cakephp/phinx#1168]
IMO the #1117 should be reverted and if one want's strict column names it should quote the name by itself.
The reason is that functional indexes e.g `->addIndex('tsrange(start_time,end_time)'` are not possible anymore.

**Comment by lorenzo** [comment]
@mvrhov I think the right way to proceed here is not create a special object (something like `new RawExpression()`) and use it for this kind of situations where you don't want quoting to happen.

**Comment by mvrhov** [comment]
That's fine by me.
