### ISSUE TITLE
Website still announces 0.8 as latest release

### ISSUE THREAD

**Issue by MarcinOrlowski** [cakephp/phinx#1174]
Website https://phinx.org/ still announces 0.8 as latest release.

![phinx](https://user-images.githubusercontent.com/8041294/30212283-937c6ea0-94a4-11e7-8a74-39fe1e2ebb92.png)

**Comment by JayPHP** [comment]
@lorenzo who has control over this?

**Comment by lorenzo** [comment]
This was already fixed. We all have control over it. It's in the `gh-pages` branch of this repo
