### ISSUE TITLE
code wrapped with "isMigratingUp / Down" mustn't be tested to be reversible

### ISSUE THREAD

**Issue by mh-ovos** [cakephp/phinx#1180]
re #1164

```
    public function change()
    {
		$table = $this->table('my_table');
		
		if ($this->isMigratingUp())
		{
			$table->changeColumn('prefix', 'string', ['length' => 64]);
		}
		else
		{
			$table->changeColumn('prefix', 'string', ['length' => 32]);
		}
		$table->update();
    }

```
this results in 
```
  [Phinx\Migration\IrreversibleMigrationException]
  Cannot reverse a "changeColumn" command

```
I know this may look like an overkill and i should split it to separate up and down methods. The thing is, my migration is tens lines longer than this with more operations which are easily reversible, and I have only one ->changeColumn eventually. I should probably split change to up&down anyway, but maybe we could figure a way how to 'mark' a codeblock so that the proxy would not record these commands.
But how could this be possible? Probably with either some additional begin/end methods or closures?
```

$this->upOnly();
$table->changeColumn('prefix', 'string', ['length' => 64]);
$this->endUpOnly();
$this->downOnly();
$table->changeColumn('prefix', 'string', ['length' => 32]);
$this->endDownOnly();
```

```
$this->upOnly(function() use ($table) {
    $table->changeColumn('prefix', 'string', ['length' => 64]);
});
$this->downOnly(function() use ($table) {
    $table->changeColumn('prefix', 'string', ['length' => 32]);
});

```

**Comment by lorenzo** [comment]
No, just use the up() and down() methods. Anything else is just complicating something that can be done in a straight forward manner
