### ISSUE TITLE
Critical issue after 0.9 release

### ISSUE THREAD

**Issue by developer-devPHP** [cakephp/phinx#1182]
after new release changed
```php
$this->adapter instanceof  Phinx\Db\Adapter\TimedOutputAdapter 
```
and not 
```php
$this->adapter instanceof  Phinx\Db\Adapter\MysqlAdapter
```
if I need to get current adapter object I need to write this code 

```php
$this->adapter->getAdapter()
```

For example: 
**before 0.9 changes**
```php
$last_insert_id = $this->adapter->getConnection()->lastInsertId();
```
**after 0.9 changes**
```php
$last_insert_id = $this->adapter->getAdapter()->getConnection()->lastInsertId();
```
Can you change structure so $this->adapter will return our Adapter object and not TimedOutputAdapter  one?
Or we need to change all our existing code to and use 
```php 
$this->adapter->getAdapter()
```
 call

**Comment by lorenzo** [comment]
Hmm, I don't think so. That would break other things, the current behaviour is the valid one. Maybe you can check if `getAdapter` is returning a wrapper and called `getAdapter` again until it is not?

In other news, I'm working towards getting a better database abstraction layer, so this kind of operations become more natural than what you were doing.
