### ISSUE TITLE
phinx 0.9.1 introduces as 0.8.1 in console

### ISSUE THREAD

**Issue by Lewiatan** [cakephp/phinx#1183]
Hi,
you've probably forgot to change version number in PhinxApplication class as it introduces in console as "Phinx by CakePHP - 0.8.1" but actually version installed is 0.9.1

**Comment by lorenzo** [comment]
Yeah, I just realised that one minute ago. Not much I can do about it now, but will be fixed in the next version

Thanks!

**Comment by JayPHP** [comment]
@lorenzo https://github.com/cakephp/phinx/blob/master/src/Phinx/Console/PhinxApplication.php#L50 Probably need a better way to do this

**Comment by lorenzo** [comment]
@JayPHP want to take care of that?

The way we do in in CakePHP is to have a `VERSION.txt` file that we change on releases.

**Comment by JayPHP** [comment]
Sure, will take a look when I get the time

**Comment by lorenzo** [comment]
thanks

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/pull/1263 resolves this.
