### ISSUE TITLE
I want to add docs about bulk insert with a short example.

### ISSUE THREAD

**Issue by kenzo0107** [cakephp/phinx#1194]
I sent pull request about bulk insert.
The pull request was merged.

https://github.com/cakephp/phinx/pull/1148

And I receive request from @lorenzo.

```
you mind sending another pull request with a short example for the docs?
```

https://github.com/cakephp/phinx/pull/1148

I sent other another pull request for the docs, but my addition doesn't really make sense.
Please send pull request with a short example for the docs.

https://github.com/cakephp/phinx/pull/1163

**Comment by JayPHP** [comment]
Thanks for the issue @kenzo0107! Will update or comment on that PR with corrections when I get a chance :)

**Comment by dereuromark** [comment]
PR open.
