### ISSUE TITLE
Order of Operations on Migrate and Rollback

### ISSUE THREAD

**Issue by miquelbrazil** [cakephp/phinx#1196]
While working on a series of migrations for an ERP app that I'm writing, I noticed some patterns to the way Phinx executes migrations and rollbacks. I can't find anywhere in the documentation that the behavior I'm seeing is the expected operation so I figured I'd author an issue to confirm or to gain a better understanding of what is happening 'under the hood'.

For a bit of context, I use Phinx with CakePHP and came to Cake from a brief background in Ruby on Rails. With RoR, the suggested pattern for writing migrations that use the `up()` or `down()` method is to do so in reverse order. I carried this pattern to Phinx migrations. However, it does not appear that Phinx processes migrations in a sequential fashion (specifically not the `down()` migrations). I can't be sure, but this behavior might be limited to chained methods that end in an `update()`; as opposed to using `save()` call.

It would appear that some operations take precedence over others, regardless of the order they appear in the chain. This 'Order of Operations' appears to be the following:

- All `removeColumn()` methods are called first
- followed by all `changeColumn()` methods
- then `renameColumn()` methods
- then '`addColumn()`

Does anyone else experience this behavior? Is this the intended way for Phinx to process migrations on rollback?

I'm writing this as I leave the office. If helpful, I can edit this issue to provide a code snippet to illustrate what I mean. To be clear, I'm not calling this a feature or a bug, I'm really just trying to get my head around they way Phinx works.

Thanks in advance.

**Comment by dereuromark** [comment]
Sounds like we could improve the docs here on this kind of order.

**Comment by lorenzo** [comment]
Closing as this is not a problem anymore once the internals refactoring branch is merged

**Comment by miquelbrazil** [comment]
My apologies. I wrote this months ago and then moved on to other aspects of the project. Glad to see that it looks like it may no longer be an issue. Thank you for taking the time to investigate.
