### ISSUE TITLE
Is there a way for multiple developers to use the same phinx database?

### ISSUE THREAD

**Issue by billystalnaker** [cakephp/phinx#1203]
We have our setup like this:
Each developer has there own server to develop on, but we share the same database.
When I try to migrate and rollback a phinx script, and another dev has created one before me, it will not allow me to rollback my script because their script does not exist in my file structure.
Error is: `Target version (20171006100001) not found` . How can we get around this? Is it normal for multiple developers to use phinx at the same time?

**Comment by dereuromark** [comment]
Afaik each developer (locally) has his own DB for this to work. Why are you sharing the same DB?

**Comment by billystalnaker** [comment]
We share databases to keep data integrity, and to limit resources needed. I'm not sure what you mean by "each developer (locally) has his own DB".

**Comment by dereuromark** [comment]
On your own server you have a test-clone of the actual master-database.
That is how the migrations are supposed to work.

**Comment by billystalnaker** [comment]
I was unaware that phinx created a local database.. I knew it created a database in the server's phinxlog table.

**Comment by mvrhov** [comment]
What @dereuromark is trying to say is that each developer should have a copy of database on its computer and work on that. Otherwise you cannot possibly do a development on branches that each needs a different schema.

**Comment by gotoin** [comment]
#1197

**Comment by dereuromark** [comment]
Closing as duplicate then.
