### ISSUE TITLE
Compatibility with symfony/console 4.0

### ISSUE THREAD

**Issue by nesl247** [cakephp/phinx#1223]
Can we add support for symfony/console 4.0? It should be the same as 3.4 but with deprecations removed. I'm not sure if there are any such compatibility issues, but I doubt many if any.

Currently phinx cannot be used in Symfony 4 due to this version constraint.

**Comment by dereuromark** [comment]
Are you able to provide a PR here for compatibility?

**Comment by nesl247** [comment]
I certainly can. Please note that to use it with the v4 components a newer PHPUnit that has not been released (5.7.24 or newer) will be required.

**Comment by nesl247** [comment]
https://github.com/sebastianbergmann/phpunit/pull/2822 is the PR fyi.

**Comment by dereuromark** [comment]
PR open
