### ISSUE TITLE
Calling vendor/bin/phinx trigger Fatal error 

### ISSUE THREAD

**Issue by tasmaniski** [cakephp/phinx#1228]
On Ubuntu server (Amazon ec2 + RDS for DB) when I call regular command:
`project_dir$ vendor/bin/phinx status`

I am getting a fatal error:
> [25-Oct-2017 12:17:08 Europe/Berlin] PHP Fatal error:  require(): Failed opening required '/var/www/project_dir/vendor/bin/../app/phinx.php' (include_path='.:/usr/share/php') in /var/www/project_dir/vendor/bin/phinx on line 27

**Comment by Stretch96** [comment]
Have you changed anything in `vendor/bin/phinx`?

The line in question should read:

```
$app = require __DIR__ . '/../app/phinx.php';
```

Which should expand to (in your case):

```
/var/www/project_dir/vendor/robmorgan/phinx/bin/../app/phinx.php
```

**Comment by tasmaniski** [comment]
I didn't change anything. 
Code from the file:

```
$app = require __DIR__ . '/../app/phinx.php';
$app->run();
```

**Comment by Iandenh** [comment]
Can you run `ls -l vendor/bin/` to check if the files in `vendor/bin/` are proper symlinks?

**Comment by tasmaniski** [comment]
Yap, there is phinx, but as I can see it's not a symlinks and that is a problem.

This is probably result of coping whole project/folder to the production server. 
Thanks @Iandenh I can fix it now...

```
$ ls -l vendor/bin/
total 32
-rwxrwxr-x 1 ubuntu ubuntu  813 Mar  1  2017 generate-deps-for-config-factory
-rwxrwxr-x 1 ubuntu ubuntu  815 Mar  1  2017 generate-factory-for-class
-rwxrwxr-x 1 ubuntu ubuntu 1232 Sep 11  2015 phinx
-rwxrwxr-x 1 ubuntu ubuntu 8902 Oct 11  2014 swagger
-rwxrwxr-x 1 ubuntu ubuntu 4711 Mar 21  2017 templatemap_generator.php
```
