### ISSUE TITLE
Timezone Error

### ISSUE THREAD

**Issue by ryangurn** [cakephp/phinx#124]
Warning: date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/Los_Angeles' for 'PDT/-7.0/DST' instead in /Applications/XAMPP/xamppfiles/htdocs/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php on line 129

Warning: date(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'America/Los_Angeles' for 'PDT/-7.0/DST' instead in /Applications/XAMPP/xamppfiles/htdocs/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php on line 129

I am running PHP 5.3.15

**Comment by eko3alpha** [comment]
I'd like to add one more thing to this, here are the supported time zone values for the php.ini file

[http://php.net/manual/en/timezones.php](timezones)
