### ISSUE TITLE
How to execute seeders in a specific order

### ISSUE THREAD

**Issue by littlewrite** [cakephp/phinx#1240]
Hello, 

there're three seeds like user, role and role_user table, I want to first run user and role seeder, and last, I could query user's id by username and query role's id by role name to construct the role_user table. 

so, How can I do?

**Comment by emptyhand** [comment]
Hey, I also need this, and  I created pull request for this feature:
https://github.com/cakephp/phinx/pull/1244

Please review my pull request and comment if you like it.

**Comment by dereuromark** [comment]
PR open.
