### ISSUE TITLE
table collation from phinx.yml

### ISSUE THREAD

**Issue by ChristianSchaefer** [cakephp/phinx#1242]
Hello, is it possible to use the collation setting from phinx.yml as default collation for table creation?

**Comment by dereuromark** [comment]
Are you able to make a PR for it? That would speed up the support here for this feature.

**Comment by khayyam90** [comment]
I think the mysql aspect of this issue is related to this PR [https://github.com/cakephp/phinx/pull/1247](https://github.com/cakephp/phinx/pull/1247)

**Comment by chinpei215** [comment]
No. But the related PR #1169 (and #1247) have been already sent.
