### ISSUE TITLE
SQLite create/dropDatabase

### ISSUE THREAD

**Issue by WGPSenshi** [cakephp/phinx#1245]
Both of these don't do what I'd expect:

createDatabase takes the name, and always appends `.sqlite3` as a file suffix. However, SQLite doesn't care what the file is called, many also use just use `.db` .
Suggestion: allow an optional suffix that replaces the .sqlite3 (second parameter for the function?)

dropDatabase is worse as in: It doesn't work.
The function does a simple `unlink` (also requiring the file suffix to be `.sqlite3`). However, this always fails (at least on Windows). I assume this is because phinx itself still has a file lock on the database while it does migrations?
Suggestion: Not sure if there's a way to solve this one, even? Can Phinx remove the file lock and destroy the database while it still is running?

**Comment by markkimsal** [comment]
I'm not sure if there's a way to force PDO to close a connection or if PDO's file handle is anything like it's network connection handling. 

I have no way to test on Windows, but something like this might work:

```php
    /**
     * {@inheritdoc}
     */
    public function dropDatabase($name)
    {
        //Windows cannot unlink a file that is currently open
        if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
            $thiz = $this;
            register_shutdown_function(function() use($thiz, $name) {
                if (!file_exists($name . $thiz->suffix)) {
                    return;
                }
                //force garbage collection on PDO handle
                $thiz->connection = NULL;
                gc_collect_cycles();

                //if this doesn't work here, there's nothing we can do                                                                                                
                @unlink($name . $thiz->suffix);

            });
        } else {
            //Unix (Posix?) can
            if (file_exists($name . $this->suffix)) {
                unlink($name . $this->suffix);
            }
        }
    }
```
