### ISSUE TITLE
Composer require does not work with symfony/yaml v4.0.0

### ISSUE THREAD

**Issue by krizsanbalazs** [cakephp/phinx#1252]
I just wanted to install and I got this message:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for robmorgan/phinx ^0.9.1 -> satisfiable by robmorgan/phinx[v0.9.1].
    - Conclusion: remove symfony/yaml v4.0.0
    - Conclusion: don't install symfony/yaml v4.0.0
    - robmorgan/phinx v0.9.1 requires symfony/yaml ~2.8|~3.0 -> satisfiable by symfony/yaml[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0].
    - Can only install one of: symfony/yaml[v2.8.0, v4.0.0].
    ...

**Comment by ADmad** [comment]
Fixed in #1224.
