### ISSUE TITLE
Support JSON column in SQLiteAdapter

### ISSUE THREAD

**Issue by jradtilbrook** [cakephp/phinx#1271]
Is there any chance of supporting JSON/JSONB column types in the SQLiteAdapter. I know Laravel's Eloquent supports them by mapping them to text which seems like a fine option to me. I'd be happy to provide a PR if you would accept such a feature.

The use case is purely for testing purposes, where I run PostgreSQL in production but want a lightweight alternative in testing. The rest of the abstraction is handled by our ORM (Yii in this case)

**Comment by chinpei215** [comment]
Since Phinx has `PHINX_TYPE_JSON` and `PHINX_TYPE_JSONB`, I wouldn't oppose it.

**Comment by dereuromark** [comment]
PR open
