### ISSUE TITLE
[MysqlAdapter] CREATE TABLE and Generated Columns

### ISSUE THREAD

**Issue by demyan112rv** [cakephp/phinx#1276]
The method that creates the expression for the column does not support the generated columns. 
For instance: 

```
CREATE TABLE `my_table` (
    ...
    `generated_column` int(11) [GENERATED ALWAYS] AS (expression)
    [VIRTUAL | STORED] [NOT NULL | NULL]
    [UNIQUE [KEY]] [[PRIMARY] KEY],
    ...
) ENGINE=InnoDB
```

Can you add support for these columns?

[\Phinx\Db\Adapter\MysqlAdapter::getColumnSqlDefinition()](https://github.com/cakephp/phinx/blob/master/src/Phinx/Db/Adapter/MysqlAdapter.php#L989)
[Mysql doc](https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html)

**Comment by chinpei215** [comment]
I think #1175 will allow you to add those columns if it gets merged.
