### ISSUE TITLE
Create custom config file with init command

### ISSUE THREAD

**Issue by jawira** [cakephp/phinx#1279]
Currently the [init command](http://docs.phinx.org/en/latest/commands.html#the-init-command) allow to create a `phinx.yml` config file. Optionally, the _init command_ also allows to specify the destination folder.

Besides the destination folder, it would be nice to be able to also specify a custom **file name**:

For example, all these commands should be valid:
```
$ vendor/bin/phinx init
$ vendor/bin/phinx init .
$ vendor/bin/phinx init /custom/location/
$ vendor/bin/phinx init phinx.yml
$ vendor/bin/phinx init custom-config.yml
$ vendor/bin/phinx init /custom/location/custom-config.yml
```

It seems that _init_'s developer already thought in this feature as you can read in [Init.php - line 81](https://github.com/cakephp/phinx/blob/b8c4fc088c0c354eab4b21791a0dcf4379ac9ae3/src/Phinx/Console/Command/Init.php#L81): `// TODO - maybe in the future we allow custom config names.`

Anyway, I already worked on this and I have already created a pull request some days ago https://github.com/cakephp/phinx/pull/1266 . What do you think?

**Comment by chinpei215** [comment]
Fixed in #1266
