### ISSUE TITLE
0.9.2 not parsing yaml file

### ISSUE THREAD

**Issue by chrisharrison** [cakephp/phinx#1283]
Steps to reproduce

```bash
mkdir test
cd test
composer init --require=robmorgan/phinx:0.9.2 -n
composer install
./vendor/bin/phinx init
./vendor/bin/phinx migrate
```

An error will occur related to parsing the YAML file. If you repeat the above steps but install Phinx 0.9.1 instead - it works.

(using PHP 7.1)

**Comment by chinpei215** [comment]
I couldn't reproduce this issue.

**Comment by chrisharrison** [comment]
Interesting. I can't reproduce on two home machines either. But it was pretty consistent on my work machine. All these are Mac OS.

I will investigate more on Monday when I'm back at work.

**Comment by josegonzalez** [comment]
@chrisharrison what was the error?

**Comment by chrisharrison** [comment]
I can't reproduce the error now. I'm still quite sure that the steps detailed in my original post *was* throwing an error about not being able to parse the YAML file. So either a) I was mistaken or b) there was some conflicting side effect on my system that has now resolved itself. As no one else has reported this, let's assume it was a) for now.
