### ISSUE TITLE
Timestamp of length '0' broken for Postgres

### ISSUE THREAD

**Issue by shamblesides** [cakephp/phinx#1287]
When specifying a 'limit' (or 'length') for a column of type `timestamp` in Postgres, it typically works as intended and creates a timestamp with that many decimals of sub-second precision.

However, this is broken for a limit of 0. We would expect to create a column of type `TIMESTAMP(0)`, but it actually generates a field of type `TIMESTAMP` which by default has 6 decimals of precision.

It looks like an oversight in PostgresAdapter.php on line 926.

```
if ($column->getLimit() || isset($sqlType['limit'])) {
```

This condition probably intends to check if the result of `$column->getLimit()` is not null, but it misses the case for a 0 limit.

I will try to create a pull request for this issue tonight.

**Comment by chinpei215** [comment]
Thank you for reporting the issue. Probably it relates to #1258. I appreciate you if you create the pull request with some test cases.

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/pull/1289
