### ISSUE TITLE
Use own Table class

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/phinx#1288]
Let's say I have custom MyTable class (similar to \Phinx\Migration\Db\Table) in project and I want Migration to use it. Do I need to create new Migration class and rewrite table method like this

```
namespace App\Migrations\Migration;

use App\Migrations\Db\MyTable;
use Migrations\AbstractMigration;

class MyMigration extends AbstractMigration {
    public function table($tableName, $options = array())
    {
        return new MyTable($tableName, $options, $this->getAdapter());
    }
}
```

OR is there better way how to "inject" custom Table class without creating custom MyMigration class and rewritting table method?

**Comment by dereuromark** [comment]
Currently, this is the best way.
Adding them through some kind of configurable factory could be useful.
PR welcome.
