### ISSUE TITLE
SQLite & MySQL identity definition incompatible

### ISSUE THREAD

**Issue by 51systems** [cakephp/phinx#1297]
If you are using the `identity` key to define an auto-increment column the syntax is incompatible between SQLite and MySQL.

In MySQL you _must_ define the `primary_key` in the table definition in addition to setting the `identity` key to true. For example:
```php
$table = $this->table('test', [
    'id' => false,
    'primary_key' => ['custom_id']
]);

$table
    ->addColumn('custom_id',
        'integer', [
            'signed' => false,
            'identity' => true
        ])
```

If you don't do this, the `PRIMARY KEY` is not set for the table.

However, in the case of the SQLite adapter, when you set `identity` to `true`, this defines the column as `PRIMARY KEY AUTOINCREMENT`, so if the column appears in the `primary_key` array, it tries to add the primary key multiple times, resulting in an exception (eg: `SQLSTATE[HY000]: General error: 1 table "test" has more than one primary key`)

**Comment by dereuromark** [comment]
PR open.
