### ISSUE TITLE
Primary keys are not unsigned

### ISSUE THREAD

**Issue by johnrobertporter** [cakephp/phinx#1300]
I have always been taught that primary key columns should be stored as unsigned int(11).

The default primary keys created by Phinx are not unsigned. Is this an oversight or by design?

**Comment by dereuromark** [comment]
It is usually not relevant at all.
But you can make a PR here to optimize these integers, if you want.

**Comment by xaphalanx** [comment]
There is a pull request for this. Someone should close this one.

**Comment by dereuromark** [comment]
You need to link the PR here then.

**Comment by dereuromark** [comment]
I do see it covered in https://github.com/cakephp/phinx/issues/292 already, so closing this as dup.

**Comment by johnrobertporter** [comment]
👍
