### ISSUE TITLE
MySQL Timestamp Precision

### ISSUE THREAD

**Issue by johnrobertporter** [cakephp/phinx#1301]
The `timestamp `type in MySQL allows for precision values like `timestamp(4)`. Phinx seems unable to do this at present.

**Comment by dereuromark** [comment]
Duplicate of https://github.com/cakephp/phinx/issues/1301 ?

**Comment by dereuromark** [comment]
Are you able to provide a pull request here?

**Comment by johnrobertporter** [comment]
Sadly not, I am under a lot of pressure to get too much work done. I would if I could.

Plus I don't know the internals of this code base and it looks very complicated.
