### ISSUE TITLE
Error: Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by designermonkey** [cakephp/phinx#1304]
> `Error: Cannot use object of type stdClass as array in xxx/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/SQLiteAdapter.php:155
`

I'm sure this would be the same in other adapters?

Caused by:

`[PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ]` as PDO options.

A simple fix is to always cast database results to array, being that they are `StdClass` instances.

**Comment by lorenzo** [comment]
What was your goal of having ` PDO::FETCH_OBJ`?

**Comment by dereuromark** [comment]
PR https://github.com/cakephp/phinx/pull/1419 open
