### ISSUE TITLE
Bug with escaping columns on create indexes.

### ISSUE THREAD

**Issue by TimurFlush** [cakephp/phinx#1306]
Hello, i'm got a bug with escaping columns on create indexes.

Adapter: pgsql,
Column name: group (reserved word)

On create 'group' index, i'm getting next error: 
`
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "group"
  LINE 1: ...DEX settings_name_group ON "public"."settings" (name,group);
`

To fix this bug, your need escape every column on every queries.

**Comment by chinpei215** [comment]
What version of Phinx are you using? I did the following with the Postgres adapter:
```php
    public function change()
    {
        $this->table('settings')
            ->addColumn('name', 'string')
            ->addColumn('group', 'string')
            ->addIndex(['name', 'group'])
            ->create();
    }
```
Seems to work for me.

**Comment by TimurFlush** [comment]
v0.8.1
