### ISSUE TITLE
Custom Primary Key ID doesn't go unsigned even passing as True in Options

### ISSUE THREAD

**Issue by igormorse** [cakephp/phinx#1310]
I was creating some migrations and after trying to setup the Foreign Keys I have got a lot of errors so I decided to check up if the attributes types were equals. All my Primary Keys were signed and my Foreign Keys Attributes were unsigned.

**Example Code:**

```
 public function change()
    {
       // Users Table Description Comment
        $usersTableComment = 'Table that contains all the Users Informations';

        // Users Table Primary Key
        $usersTablePK = 'id_user';

        // Table Creation
        $usersTable = $this->table('users', ['id' => $usersTablePK, 'signed' => false, 'comment' => $usersTableComment]);

       $usersTable->create();

   }
```

Passing the argument **signed** in the Options for creating the Table doesn't seem to work. 

Checking the DDL Script of this Table the Primary Key remains **signed**. Is this the normal behaviour ?

**Comment by igormorse** [comment]
The only workaround I've found is setting manually the Primary Key Column with addColumn() passing the options **signed** and **identity** but this add a lot of extra work and unnecessary lines to the migration file.

The example above should've worked because **signed** is a valid option for the Primary Key.

**Example Code:**
```
        // Table Creation
        $usersTable = $this->table('users', ['id' => false, 'primary_key' => 'id_user', 'comment' => $usersTableComment]);

        $usersTable
            ->addColumn('id_user', 'integer', ['signed' => false, 'identity' => true])
```

There is a Pull Request for that ( #1294 ) from 27 days ago is it going to be merged in the next version ?

**Comment by dereuromark** [comment]
PR merged.
