### ISSUE TITLE
Phinx return mysql error 2014

### ISSUE THREAD

**Issue by NickOver** [cakephp/phinx#1315]
I wanna test is custom config file work correctly, so i crate new "dummy" migration:

```
<?php

use Phinx\Migration\AbstractMigration;

class Test extends AbstractMigration
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change()
    {
       $this->execute('SHOW TABLES;');
    }
}
```
After run i got error:

> SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

It's because i don't use fetchAll() method, and phinx wanna add migration to log. I think before executing query to update log's phinx shoud clear pdo buffer.

After change change method body to:
```
$stmt = $this->query('SHOW TABLES;');
$rows = $stmt->fetchAll();
```
everythink works correctly.

**Comment by dereuromark** [comment]
Are you able to provide a PR with your suggested changes?

**Comment by NickOver** [comment]
Ofc :) I will try make pull request on next few days.

**Comment by JayPHP** [comment]
@NickOver Could you dump the PR reference in here once done please? We'll be able to merge asap then.

**Comment by markkimsal** [comment]
`PDO->exec()` is different from `PDOStatement->execute()`.  `exec()` is not designed for queries that produce result sets, only for statements INSERT/UPDATE/DELETE and commands like SET.  `PDO->exec()` only returns the number of rows affected, hence why there is a result set buffer sitting around.

In a migration `$this->execute()` is short for `$this->getAdapter()->getConnection()->exec()`

http://php.net/manual/en/pdo.exec.php

I don't think it's possible to clean up this result set from PHP land, I think the PDO C extension leaves it orphaned in the libmysqlclient.so.

Simply changing `execute()` to `query()` without fetching the result set fixes the problem:
```
class ShowTables extends AbstractMigration
{
    public function change()
    {
        $this->query('SHOW TABLES');
    }
}
```
