### ISSUE TITLE
Change limit of a string column

### ISSUE THREAD

**Issue by jnwmd** [cakephp/phinx#1316]
Hi guys, hope this won't be a duplicate entry. 

I've looked for an answer in open and closed issues but it seems there is no a solution yet. 
I defined a column like follow: 
   $table->addColumn("my_column", "string")
and everything was ok until column was required to be added it an index and increase its limit (by default phinx assigns varchar(255) if am not wrong).
After added the index with: 
  $table->addIndex("my_column", ["unique" => true]); (This migrate was successful) I tried to increate the length of the column with:  
  $table->changeColumn("my_column", "string", ["limit"] => 256);  
and I received this error.

[PDOException]                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t  
  oo long; max key length is 767 bytes

I've seen some topics with the similar error but without any solution.

This is a bug or am missing something? 

Thanks.

King regards.

Julián May

**Comment by dereuromark** [comment]
What type of collaction is that? utf8mb4_unicode_ci?

**Comment by jnwmd** [comment]
Hi @dereuromark am using utf8, and after research about it and tried out into the database and table, it seems the limit of utf8 collation is 255. 
I think we'll continue with 255 for now. 

or do you have a suggestion?


Thanks.

**Comment by dereuromark** [comment]
There are some good reads out there on the limit of these fields and how that relates to utf8 or utfmb4. Closing then.
