### ISSUE TITLE
[SqlServerAdapter] Computed column support

### ISSUE THREAD

**Issue by hdogan** [cakephp/phinx#1317]
It would be nice to support SQL Server computed columns too (similar to MySQL generated columns, except SQL dialect terminology). I'll try to implement it if #1311 (MySQL generated columns) PR is merged.

More info: https://docs.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table

**Comment by dereuromark** [comment]
PR open
