### ISSUE TITLE
Less output on create

### ISSUE THREAD

**Issue by rakshazi** [cakephp/phinx#1334]
Hello!
`phinx create` command shows a lot of information in output, but I need only migration file path.
Is any way here to suppress "debug" part of output?

**Examples**:

Now is something like this:

```
phinx create InitialData
Phinx by Rob Morgan - https://phinx.org. version 0.8.0

using config file ./phinx.php
using config parser php
using migration paths 
 - /tmp/jura/db/migrations
using migration base class Phinx\Migration\AbstractMigration
using default template
created ./db/migrations/20170428180919_initial_data.php
```

And I want something like this:

```
Migration created ./db/migrations/20170428180919_initial_data.php
```

How can I do it?

**Comment by rquadling** [comment]
Using `-q` almost gets you there, in as far as you get no output. If the output is to be used by another script, then using `grep` if via the command line, or use a Buffered Output if you are calling the create command in your own code.
