### ISSUE TITLE
Managing permissions and configuration values?

### ISSUE THREAD

**Issue by synapdk** [cakephp/phinx#1337]
Thanks for indulging a question that I wasn't able to answer from the documentation. I'm willing to PR an update to the docs if I figure it out.

Should we use `execute()` to grant permissions? That would be something like

```php
$this->execute('GRANT SELECT ON db.new_table TO \'user\'@\'localhost\'');
```

Now if part of that is different in different environments, is there a way to use a configuration value in the migration? Say if `localhost` or some other value were different in each environment.

Thanks for any pointers or ideas!

**Comment by rquadling** [comment]
I think the Environment is now being (or will be) presented to the migration, so you should be able to determine which (if you have many) database is being migrated.

**Comment by synapdk** [comment]
Ah, I needed to search "environment" issues. Looks like PR #794 will address this question and implement #984.
