### ISSUE TITLE
New release (v0.9.3)

### ISSUE THREAD

**Issue by piotr-cz** [cakephp/phinx#1347]
What about new release?
I'm particularly interested in #1208 but there has been [lots of other commits since last v0.9.2 release](https://github.com/cakephp/phinx/compare/v0.9.2...master)

**Comment by dereuromark** [comment]
You can use dev-master until then. To see if all good.

**Comment by lorenzo** [comment]
In a week or two

**Comment by rquadling** [comment]
How's the review going for a new release? Waiting on this to fix a super-minor issue with `phinx list --format=xml` not outputting xml. Well, not JUST xml.

**Comment by lorenzo** [comment]
@rquadling I was planning on releasing this weekend after testing it in a couple projects. Can you also helps us verify that things work alright when using the master branch?

**Comment by l0gicgate** [comment]
Looking forward to new release @lorenzo

**Comment by lorenzo** [comment]
@l0gicgate sorry for the late release, I wanted to make sure things were working fine and also include a major last minute feature

**Comment by SeinopSys** [comment]
[Packagist](https://packagist.org/packages/robmorgan/phinx) didn't get the memo about the new release. You might want to look into that.

**Comment by dereuromark** [comment]
Working on it :)

**Comment by lorenzo** [comment]
@SeinopSys working now!

**Comment by SeinopSys** [comment]
Cheers!

**Comment by piotr-cz** [comment]
Thank you!
