### ISSUE TITLE
Modify multiple tables in single migration

### ISSUE THREAD

**Issue by niko-lay** [cakephp/phinx#1348]
Hello
I need to modify multiple tables in single migration and I'm using phinx about this way
```php
public function up()
    {
        $table = $this->table('user_data');
        $table->addColumn('data_type', 'integer')// other columns
                  ->save();
        
        $table = $this->table('users');
        $table->addColumn('data_type', 'integer')
                   ->save();
}

public function down(){
// remove column data_type
//  drop table user_data
}
```
But if second `save()` fails DB is needed a manual correction (remove `user_data` table, as in example). 
Is there any way to make the migration, which changes several tables?

**Comment by lorenzo** [comment]
It is only possible for databases that support transactional DDL, such as postgresql. This is not possible for other database systems like MySQL.

**Comment by lorenzo** [comment]
Closing as this is a limitation in mysql itself
