### ISSUE TITLE
Add MySQL 'Enum' column type

### ISSUE THREAD

**Issue by aarbrown** [cakephp/phinx#135]
Add support for MySQL Enumeration types.  

I haven't looked into the source too deeply, but it looks like I would just have to modify the getColumnTypes() method of PdoAdapter.php and make the limit option accept an array.

Usage would look something like this, possibly:

$table->addColumn('enumeration', 'enum', array('limit' => array('value1', 'value2'));

Thoughts, @robmorgan?

**Comment by marcosdalte** [comment]
Doesnt have support to enum, yet?

**Comment by hshhhhh** [comment]
@marcosdalte it does, update your phinx.

**Comment by marcosdalte** [comment]
Thank you, I found this example and works to me:

->addColumn('column22', 'enum', array('values' => array('three', 'four')));
