### ISSUE TITLE
Phinx Memory Leak

### ISSUE THREAD

**Issue by iamdann** [cakephp/phinx#1359]
I'm experiencing this weird issue when trying to execute seeders.  It appears to be a memory leak issue because increasing memory size dind't solve the issue. 

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/19746471/40887917-3495d30c-6750-11e8-84ea-b76d1333f2a1.png">

Any ideas of how to debug this?

**Comment by iamdann** [comment]
Found the issue.

When using `getDependencies()` refering to it's own class causes the above exception to be thrown.

**Comment by MasterOdin** [comment]
You were doing:
```
<?php

use Phinx\Seed\AbstractSeed;

class TestSeeder extends AbstractSeed
{
    public function getDependencies()
    {
        return [
            'TestSeeder '
        ];
    }

    public function run()
    {
    }
}
```
?

**Comment by iamdann** [comment]
Yup!
