### ISSUE TITLE
Insert Seeds data with associations table

### ISSUE THREAD

**Issue by EdouardTack** [cakephp/phinx#1362]
Hello,

Is it possible to insert data with associations ? or just get the last insert id ?

In my case:
I want to insert data with Seed command line, but i do not want to have static id in my data. And i have associations with other table.

Thanks

**Comment by brettmc** [comment]
I came up against this issue too. Phinx doesn't look like it supports the concept yet, but the way I worked around it was to use phinx's db adapter to run a query to fetch foreign keys:
```php
public function getDependencies()
{
  return [MyForeignTable::class];
}
public function run()
{
  $table = $this->table('MyReferencingTable');
  $foreignKeys = $this->adapter->fetchAll('select id from MyForeignTable');
  $table->insert([
    'id' => 'foo',
    'fk_id' => $foreignKeys[array_rand($foreignKeys)],
  ])->save();
}
```

**Comment by lorenzo** [comment]
@EdouardTack it does not support it, and to be honest I don't think it will. Supporting associations is quite a complicated endeavour which is likely out of scope for all of us.

Maybe you can use something like an ORM that supports associations to help you do that?

**Comment by EdouardTack** [comment]
@lorenzo, i agree with you about associations. But i don't want to use an ORM inside Phinx, an i already configure phinx for my website, i don't want to change it.

My databases of dev and production can be different, and i don't want static **id** in my Seeds.

So, i've got an idea. We can just get the last insert ID when we save data Seed ?

In my exemple below, we got a contents with several contents languages.
```php
$contentsTable = $this->table('contents');
$contents = [
    [
        'content' => [
            'user_id' => 1,
            'status' => 1,
            'created' => '2018-06-07 10:15:53',
        ],
        'languages' => [
            [
                'id_language' => 1,
                'name' => 'Français 1'
            ],
            [
                'id_language' => 2,
                'name' => 'Anglais 1'
            ]
        ]
    ],
    [
        'content' => [
            'user_id' => 2,
            'status' => 1,
            'created' => '2018-06-07 10:45:19',
        ],
        'languages' => [
            [
                'id_language' => 1,
                'name' => 'Français 2'
            ],
            [
                'id_language' => 2,
                'name' => 'Anglais 2'
            ]
        ]
    ],           
];

foreach ($contents as $content) {
    $insertId = $contentsTable->insert($content['content'])->save();
    foreach ($content['languages'] as $language) {
        $language['content_id'] = $insertId;
        $this->table('content_languages')->insert($language)->save();
    }
}
```

**Comment by lorenzo** [comment]
We could only get the id's when not using bulk inserts (which phinx does by default and are a lot faster)

If you use the latest code in master you may be able to use the new `$this->getQueryBuilder()->insert()` function, which has the ability for getting the last inserted id. Would that be a solution?

**Comment by EdouardTack** [comment]
Thanks @lorenzo, it's help me for what i want to do.
I put the exemple below.

```php
$query = $this
    ->getAdapter()
    ->getQueryBuilder()
    ->insert([
        'email',
        'password',
        'created'
    ])
    ->values([
        'XXX@XXX.fr',
        'XXX',
        '2018-05-24 12:15:53'
    ])
    ->into('users');
$insertedId = $query->execute()->lastInsertId();
```

**Comment by 4yz4** [comment]
I still have the problem of foreign keys, I leave my code to see where the error is.
`public function getDependencies(){
        return UsersTable::class;
    }
     public function run()
    {
        $faker = Faker\Factory::create();
        $data = [];
        $foreignKeys = $this->getDependencies()->fetchAll(['id']);

        for ($i=0; $i < 200 ; $i++) { 
            $data[] = [
                'title' => $faker->name(),
                'description' => $faker->text(),
                'url' => $faker->url(),
                'created' => date("Y-m-d H:i:s"),
                'modified' => date("Y-m-d H:i:s"),
                'user_id' => $foreignKeys[array_rand($foreignKeys)]
            ];
        }

        $table = $this->table('bookmarks');
        $table->insert($data)->save();
    }
}`

**Comment by clementmtn** [comment]
Hi @4yz4 

Try this :) 

```
public function getDependencies(){
        return UsersTable::class;
}
public function run()
    {
        $faker = Faker\Factory::create();
        $data = [];
        $foreignKeys = $this->adapter->fetchAll("SELECT id FROM Users");

        for ($i=0; $i < 200 ; $i++) { 
            $data[] = [
                'title' => $faker->name(),
                'description' => $faker->text(),
                'url' => $faker->url(),
                'created' => date("Y-m-d H:i:s"),
                'modified' => date("Y-m-d H:i:s"),
                'user_id' => $foreignKeys[array_rand($foreignKeys)]['id']
            ];
        }

        $table = $this->table('bookmarks');
        $table->insert($data)->save();
```

**Comment by 4yz4** [comment]
Thank you @clementmtn, you solved the problem that I have been dragging for a long time. =)

**Comment by 4yz4** [comment]
@clementmtn the table is populated with data but I get this error message:

Warning Error: Invalid argument supplied for foreach() in [C:\xampp\htdocs\pocake\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php, line 815]

I don't understand where the error is if the execution is correct :( help please @clementmtn

**Comment by clementmtn** [comment]
Hi @4yz4 Can you give details from your foreach() function ?
