### ISSUE TITLE
Using generated table names in execute() method

### ISSUE THREAD

**Issue by therecluse26** [cakephp/phinx#1368]
Hi, I'm writing a series of MySql migrations that include the creation of db events. Is there any way to do this that would include the proper table names including the `table_prefix` set in the config file? The only way I'm aware to even create events at this point is through the `execute` method. Is there a way to pass parameters into the up() and down() methods or something like that to accomplish what I'm trying to do?

**Comment by lorenzo** [comment]
I don't think I understand your requirement, could you explain a bit more? Maybe add some for for what your are doing and what you would like to happen

**Comment by therecluse26** [comment]
@lorenzo Sure, I'll just copy some of the code in that I'm hoping to include as part of my migrations. The `{$tblprefix}` variable is what I'm hoping to have replaced by the configured `table_prefix` setting from the yml config file.

`<?php

use Phinx\Migration\AbstractMigration;

class DbEvents extends AbstractMigration
{
    public function up()
    {
        $this->execute("SET GLOBAL event_scheduler = ON;
                        CREATE EVENT IF NOT EXISTS cleanupOldDeleted
                        	ON SCHEDULE EVERY 1 DAY
                        DO
                        BEGIN
                          DELETE FROM {$tblprefix}deleted_members
                          WHERE mod_timestamp < DATE_SUB(NOW(), INTERVAL 30 DAY);
                        END;");

        $this->execute("CREATE EVENT IF NOT EXISTS unbanUsers
                            ON SCHEDULE EVERY 15 MINUTE
                        DO
                        BEGIN
                            DELETE FROM `vw_banned_users` where hours_remaining < 0;
                            UPDATE {$tblprefix}members m SET m.banned = 0 where m.banned = 1 AND m.id not in (select v.user_id from `vw_banned_users` v);
                        END;");
    }

    public function down()
    {
    }
}
`

**Comment by lorenzo** [comment]
I would do this by creating your own adapter wrapper. Your wrapper would override execute, and do the variable replacement. Does that make sense?

**Comment by therecluse26** [comment]
Yeah, I'm just not totally sure the best way to go about that. Any pointers?

**Comment by lorenzo** [comment]
Check the TablePrefixAdapter class, or the TimedOutput adapter, you will see how different functions are overridden to add more features

**Comment by arnisjuraga** [comment]
Just a note, how to get correct prefixed table name:

```php
 public function up()
    {
    $tableAdapter = new \Phinx\Db\Adapter\TablePrefixAdapter($this->getAdapter());
    // And then:
    $table_name = $tableAdapter->getAdapterTableName('product_special');
    // or, directly in execute statement:
    $this->execute("update {$tableAdapter->getAdapterTableName('product_special')} set date_end = NULL where date_end < '1971-01-01'");
    ...
} 
```
