### ISSUE TITLE
addTimestamps() has column names inverted

### ISSUE THREAD

**Issue by vichaunter** [cakephp/phinx#1377]
Hello,

I've notice that when i use addTimestamps() in my tables, it creates two columns correctly, but the functionality about update time is inverted.

Expected:
created_at: get the date when row is created
updated_at: get the date each time row is updated

Current:
created_at: get the date each time row is updated
updated_at: get the date when row is created

The only thing needed to reproduce is create a table and set addTimestamps, check the database scheme and you can see the update statement enabled in created_at column.

Cheers!

**Comment by lorenzo** [comment]
Would you be able to submit a pull request to fix this?

**Comment by vichaunter** [comment]
I don't understand, i should expect that updated_at will be the date when the row was created and created_at will change with each row update?

**Comment by juliuswz** [comment]
No. But if you look at the method, you will see that the definition of the `created_at` column only contains the `default` option, that is, only when a row is created is added the `CURRENT_TIMESTAMP`.

**Comment by alturic** [comment]
Has this been tweaked at all? I'm getting a correct column names, and created_at is working as expected, however update_at get's a null default and nothing ever changes when altering the record.

**Comment by lorenzo** [comment]
> Has this been tweaked at all? I'm getting a correct column names, and created_at is working as expected, however update_at get's a null default and nothing ever changes when altering the record.

This is expected. You are responsible for updating the column yourself. I'll close this issue since the method is working as expected
