### ISSUE TITLE
Table::saveData() is expected to reset pending changes

### ISSUE THREAD

**Issue by djcvijic** [cakephp/phinx#1381]
I feel like this is a common gotcha which is not so easy to uncover - perhaps you make a few insert statements, then call saveData(), then do something else, then call save(), or saveData() again on the same table. I would expect the first few insert statements to be executed only once, but they are in fact executed twice with this workflow. Here's a concrete example:

```
        $table
            ->addColumn('column1', 'string', ['null' => true])
            ->save();
        $table
            ->insert($data)
            ->saveData();
        $table
            ->changeColumn('column1', 'string', ['null' => false])
            ->save();
```

In this example all rows from $data are inserted twice.

The [official documentation](http://docs.phinx.org/en/latest/migrations.html#inserting-data) only mentions the saveData() method once, and at no point mentions this unexpected behaviour, even seeming to skim around the issue by instantiating a new table before calling save() later. And a few [unofficial blog posts](https://lornajane.net/posts/2015/insert-data-with-phinx) also never mention this.

I can accept that this is by design, but **at the very least** I would propose a documentation update to save new users from this gotcha in the future, probably advocating the use of save() only. At best I would also start deprecating the saveData() method, making it private with the next major version.

**Comment by lorenzo** [comment]
this is a bug I probably introduced myself. Would you like to send a pull request to fix it?

**Comment by djcvijic** [comment]
@lorenzo Oh ok then, I didn't think it would be a bug.

I'll fix it.

Just to be sure, expected behaviour is saveData() to reset pending changes?

**Comment by lorenzo** [comment]
yes, that's correct
