### ISSUE TITLE
Contributing docs - how to handle partially implemented features

### ISSUE THREAD

**Issue by djcvijic** [cakephp/phinx#1388]
A section that might be helpful in CONTRIBUTING.md - what to do when contributing, but not able to fully implement a feature?

For example, a feature requires code for all four supported database types, but the contributor is unable to either implement or test implementations for all four. What should be done in this case? Suggestions are to leave TODOs, leave methods that throw NotImplementedExceptions, leave valid but failing test cases, etc...

**Comment by lorenzo** [comment]
Did you have an specific case in mind for this?

My take would be that no incomplete features should be merged

**Comment by djcvijic** [comment]
@lorenzo I am currently working on https://github.com/cakephp/phinx/issues/335, but I can see this being an issue on any larger task.

I was hoping the docker image would contain all four databases, but after installing it learned it had only postgres and mysql, which still leaves me no way of testing the sqlite and sqlserver. How difficult would it be to add them to the image? Or would you propose a different solution?

**Comment by lorenzo** [comment]
SQLite should súper easy to add, it is just a matter of adding the php extension.

SQLserver would not be possible, but you could test indericyly through app veyor, once we enable the test there again

**Comment by djcvijic** [comment]
You're right, SQLite turned out to be very simple as well, and enabled out-of-the-box in the provided docker image.

So only SQLServer is a problem still. I'll try setting up manually on a Windows machine now, but I hope there will be a better option in the future, to guarantee the consistency and quality of future cross-database contributions.
