### ISSUE TITLE
removeIndex needs save(), but...

### ISSUE THREAD

**Issue by akkie-github** [cakephp/phinx#1391]
removeIndex() needs save(), but it is written in the document that "There is no need to call the save() method when using removeIndex(). The index will be removed immediately."
And it is called save() for tests of removeIndex().

**Comment by lorenzo** [comment]
Would you be kind to add that to the documentation?

**Comment by akkie-github** [comment]
Thank you for your response.
Is it correct to save () when calling removeIndex ()?
If so, I will try to fork it and propose my changes.
(just delete the description in the document.)

**Comment by lorenzo** [comment]
Yes, save() is required

**Comment by dereuromark** [comment]
Anyone wants to make an update to docs?

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/pull/1659
