### ISSUE TITLE
Trying to use a multi-column index

### ISSUE THREAD

**Issue by cemozder** [cakephp/phinx#1404]
When i run this command
```
$table = $this->table('mails');
$table->addColumn('mode', 'text')
              ->addColumn('send_at', 'datetime')
              ->addColumn('status', 'text')
              ->addIndex(['mode', 'status', 'send_at'], [
                 'limit' => ['mode' => 30, 'status' => 30],
                 'name' => 'mode_status_sendat'
              ])
```
i get an error like
'[PDOException]                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error i  
  n your SQL syntax; check the manual that corresponds to your MySQL server v  
  ersion for the right syntax to use near 'Array))) ENGINE = InnoDB CHARACTER  
   SET utf8 COLLATE utf8_general_ci' at line 1'

thank you for your help.

**Comment by lorenzo** [comment]
Why do you have those weird quotes around `mode_status_sendat`?

```
'name' => `'mode_status_sendat'`
```

**Comment by cemozder** [comment]
I fixed that but still have an error.

**Comment by lorenzo** [comment]
Ok, can you figure out what query is generating that error? Use the -vvv flag when running phinx

**Comment by lorenzo** [comment]
What phinx version are you running?

**Comment by cemozder** [comment]
0.8.1

**Comment by cemozder** [comment]
should I run the code 'php vendor / bin / phinx migrate -vvv development'?

**Comment by lorenzo** [comment]
You are using a version of phinx that does not support the feature you are trying to use, please update.
