### ISSUE TITLE
Remove support for up()/down().

### ISSUE THREAD

**Issue by rquadling** [cakephp/phinx#1411]
With the initial removal of `up()` and `down()` back in April 2015 from the AbstractMigration.template.dist file and https://github.com/cakephp/phinx/pull/1410 introducing the deprecation and todo annotations to inform users of Phinx of the dropping of `up()` and `down()`, in favour of `change(string $direction = null)`, this issue is to actually effect that deprecation and so remove support for `up()` and `down()` completely.

This will be a major backwards compatibility issue, especially if you have hundreds of migrations.

So a reasonable amount of time from when the release of the deprecation needs to be accounted for.

I'd go with 6 months and a new major release (0.11 as things stand at the moment) so that semantic versioning is maintained.

**Comment by lorenzo** [comment]
Do we actually need to remove it? I personally find it more clear to split the migration in two steps, if I know my steps cannot be automatically done for me in `change`

**Comment by rquadling** [comment]
Well, this seems to be the direction, having removed `up()` and `down()` from the base template.

**Comment by rquadling** [comment]
I wasn't happy with the initial removal. I'd say at least 90% of my migrations don't use change().

But with #1410, at least `change()` now has the direction, so, with that, we could leave `up()` and `down()` as hidden/undocumented features, but they would need to be maintained indefinitely.

So removing them ... eventually.

If the consensus is to just hide them, then again, why hide them? Re-introduce them into the template, but have them as commented out, so the move from `up()`/`down()` to `change($direction)` is fine, but a user can decide to implement the alternative and supported pattern.

As things stand, a user doesn't see the missing methods in the base template and has to add them back in to use them.

**Comment by halfer** [comment]
I'd be happy for `up`/`down` to be left in - I use a good mix of `up`/`down` and `change`.

**Comment by dereuromark** [comment]
PR open https://github.com/cakephp/phinx/pull/1410
