### ISSUE TITLE
Passing variables to file specified in --config option

### ISSUE THREAD

**Issue by bezdutchek** [cakephp/phinx#1412]
I'm using PHP script as a config file for Phinx, is it possible to pass variable to that file? I know I can get enviroment variables in that PHP file but it's not what I need since I'm running phinx in bash loop and I'm trying to pass found folders to that script

**Comment by lorenzo** [comment]
Can you maybe set the folders as env vars?

**Comment by bezdutchek** [comment]
>  I know I can get enviroment variables in that PHP file but it's not what I need

**Comment by lorenzo** [comment]
@bezdutchek why is it not what you need when that would work just fine?

**Comment by lorenzo** [comment]
@bezdutchek What I meant was, you can set the env vars (new made up ones) in bash and read them in the php config file and transform the data into anything you need
