### ISSUE TITLE
Impossible rollback a specifc migration with target option

### ISSUE THREAD

**Issue by yanbert** [cakephp/phinx#1413]
Hello everyone, i use cake everyday but i some problems with migrations. I have many migrations files and i want rollback only one migration so il a use --target option or -t alias but doesn't work.
someone could help me?
thanks

**Comment by lorenzo** [comment]
If you need help, please use one of our support channels. Like the slack community or the support forums :)

I'll close this ticket as the issue tracker is reserved for possible bugs or enhancements.
