### ISSUE TITLE
SQLite - Functions broken after 0.9.2

### ISSUE THREAD

**Issue by JamesRItchie88** [cakephp/phinx#1422]
Hey,

The following methods do not work as intended since 0.9.2: rename, addColumn, removeColumn (with foreign key constraints). There may be other issues but these are the only ones I've encountered so far.

The new AlterInstructions and query builders for SQLite treats it as a single executable. 

**Adding Columns**

Single query for add column example query generated using:

` $this->table('table_1')
	   ->addColumn('user_id', 'integer')
	   ->create();`

would create "ALTER TABLE standard_working_time ADD user_id INTEGER;"

This would work absolutely fine. However, with the AlterInstructions now executing one statement only for each type of method... SQLlite cannot handle the following for add columns:

` $this->table('table_1')
	   ->addColumn('user_id', 'integer')
           ->addColumn('type', 'VARCHAR')
	   ->create();`

This would generate the following SQL statement: "ALTER TABLE standard_working_time ADD user_id INTEGER, ADD type VARCHAR;

SQLite does not support this and has to be executed like so:

 "ALTER TABLE standard_working_time ADD user_id INTEGER;"
 "ALTER TABLE standard_working_time ADD type VARCHAR;"

**Rename Table**

`$this
	->table('table_1')
	->rename('table_2');`

Running this in SQLite will also throw RuntimeException with the following message:

In AbstractMigration.php line 362:
Migration has pending actions after execution! 

This was run directly after the following migration:

`$this
			->table('table_1')
			->addColumn('user_id', 'integer')
			->addColumn('weekday', 'integer', ['limit' => MysqlAdapter::INT_TINY])
			->addColumn('start', 'time')
			->addColumn('end', 'time')
			->addForeignKey('user_id', 'users', 'id', ['delete' => 'NO_ACTION', 'update' => 'CASCADE'])
			->create();`

As you can see above, there are multiple addColumn methods. I implemented my own temporary "workaround" to move on with my migrations to see if anything else was broken for SQLite

AlterInstructions was changed to have this:

```
/**
     * Executes the ALTER instruction and all of the post steps.
     *
     * @param string $alterTemplate The template for the alter instruction
     * @param callable $executor The function to be used to execute all instructions
     * @return void
     */
    public function execute($alterTemplate, callable $executor)
    {
    	$adapter = $executor[0];
    	$adapter_type = $adapter->getAdapterType();

        if ($this->alterParts) {
            if ($adapter_type === 'sqlite') {
				foreach ($this->alterParts as $alterPart) {
					$alter = sprintf($alterTemplate, $alterPart);
					$executor($alter);
				}
            } else {
	            $alter = sprintf($alterTemplate, implode(', ', $this->alterParts));
	            $executor($alter);
            }
        }

        $state = [];

        foreach ($this->postSteps as $instruction) {
            if (is_callable($instruction)) {
                $state = $instruction($state);
                continue;
            }

            $executor($instruction);
        }
    }
```

This allowed me to use addColumn multiple times. (not the most ideal fix as I'd rather change how the SQLAdapter builds the queries and look into executing multiple times by making improvements to the alterInstructions class but this was just a simple implementation to get it working). 

**Removing Columns (with foreign keys)**

Create the following table:

```
$this
			->table('table_3')
			->addColumn('user_id', 'integer')
			->addColumn('start', 'datetime')
			->addColumn('end', 'datetime')
			->addColumn('description', 'string')
			->addForeignKey('user_id', 'users', 'id', ['delete' => 'CASCADE', 'update' => 'CASCADE'])
			->create();
```

now further in your migrations, make changes to the table like so:

```
                       $this
			->table('table_3')
			->dropForeignKey('in_event_id')
			->dropForeignKey('out_event_id')
			->removeIndex(['in_event_id', 'out_event_id'])
			->removeColumn('in_event_id')
			->removeColumn('out_event_id')
			->save();
```
The initial creation works (using the temp fix I put in place to allow chaining addColumn. 
The migration after fails due to the following SQL statements being run

ALTER TABLE `table_3` RENAME TO `tmp_table_3`;

This is fine. This however isn't when it goes to re-create the table:

CREATE TABLE `table_3`
(
  `id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, `user_id` INTEGER NULL,
  `start` DATETIME NULL, `end` DATETIME NULL, `description` VARCHAR(255) NULL,
  `out_event_id` INTEGER NULL,
  FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`in_event_id`) REFERENCES `door_events` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  FOREIGN KEY (`out_event_id`) REFERENCES `door_events` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
);

The foreign keys are kept in place, thus throwing an error as it's trying to add a foreign key to something that doesn't exist.

**Comment by lorenzo** [comment]
Hi, thanks for reporting. Would you like to help solving some of those issues? Seems like you have a pretty good idea of what is broken and what needs to be done

**Comment by lorenzo** [comment]
Instead of adding the hack, you just need to change the sqlite adapter to use `$instructions->addPostStep()` or use the second argument of `AlterInstructions` constructor. Here, for example https://github.com/cakephp/phinx/blob/master/src/Phinx/Db/Adapter/SQLiteAdapter.php#L343

You just need to make sure that the full statement is written, instead of just the `ADD` part.

**Comment by JamesRItchie88** [comment]
Briefly used that earlier while going through the code base to get a better understanding of what's going on and checking out the changes and does look like a better way of going about it than the crappy workaround I put in to do more tests. I will look into it more soon as I get chance and ideally add in more unit tests to hopefully prevent it happening in the future

**Comment by lorenzo** [comment]
@JamesRItchie88 thanks a lot for your report and help. I'm really surprised this was not caught by tests before, so definitely we need to add more to prevent this kind of mistakes in the future

**Comment by lorenzo** [comment]
Thanks!
