### ISSUE TITLE
Allow specify a SQL function or expression when changing column type

### ISSUE THREAD

**Issue by CauanCabral** [cakephp/phinx#1423]
When you have a column of type 'varchar' and need to change that type for 'integer', you actually receive a error message from DB (in that case, Postgresql):

```shell
Exception: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "your_field" cannot be cast automatically to type integer
HINT:  You might need to specify "USING your_field::integer". in [/home/vagrant/project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 165]
```

In Rails, you can pass um extra parameter to define a function/expression:

```ruby
change_column :your_table, :your_filed, 'integer USING CAST(your_field AS integer)'
change_column :your_table, :your_field, :integer, using: 'your_field::integer'
```

Can we support that too?

**Comment by lorenzo** [comment]
You can use the `Literal` class for this. 

http://docs.phinx.org/en/latest/migrations.html?highlight=literal#custom-column-types-default-values
