### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Migration::up()

### ISSUE THREAD

**Issue by paddelboot** [cakephp/phinx#1424]
That is the error I get trying to migrate a table:

`$ lib/bin/phinx migrate -e development
Phinx by CakePHP - https://phinx.org. 0.10.5

using config file ./phinx.yml
using config parser yaml
using migration paths 
 - /media/Entwicklung/Entwicklung.xxx/pci-app/db/migrations
using seed paths 
using environment development
using adapter mysql
using database pcall

 == 20180808131136 Migration: migrating
PHP Fatal error:  Uncaught Error: Call to undefined method Migration::up() in /media/Entwicklung/Entwicklung.xxx/pci-app/lib/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php:128
Stack trace:
`

Any info on what's going wrong?

**Comment by paddelboot** [comment]
Here's my migration file:

``<?php

use Phinx\Migration\AbstractMigration;

class Migration extends AbstractMigration {

         /**
	 * Remember to call "create()" or "update()" and NOT "save()" when working
	 * with the Table class.
	 */

	public function create() {

		$call = $this->table( 'call' );
		
		$call->addColumn( 'uuid', 'string', [ 'limit' => 40 ] )
				->addColumn( 'CallerNumber', 'string', [ 'limit' => 40 ] )
				->addColumn( 'DestinationNumber', 'string', [ 'limit' => 40 ] )
				->addColumn( 'created', 'datetime' )
				->addIndex( [ 'uuid' ], [ 'unique' => true ] )
				->save();
	}

}``

I also left that comment on there, because it is confusing - all the examples in the official documentation work with the save() - method.

**Comment by MasterOdin** [comment]
Your migration should be:
```
<?php

use Phinx\Migration\AbstractMigration;

class Migration extends AbstractMigration {

    /**
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */

    public function change() {
        $call = $this->table( 'call' );

        $call->addColumn( 'uuid', 'string', [ 'limit' => 40 ] )
            ->addColumn( 'CallerNumber', 'string', [ 'limit' => 40 ] )
			->addColumn( 'DestinationNumber', 'string', [ 'limit' => 40 ] )
			->addColumn( 'created', 'datetime' )
			->addIndex( [ 'uuid' ], [ 'unique' => true ] )
			->create();
    }
}
```

The migration functions must be either `up` and `down` or just `change` (which auto does the down route for you).


The function chain then that you use on your table class (`$call` in your example) should be either `create()` or `update()`.

**Comment by MasterOdin** [comment]
The "up" and "down" can be thought of as whether you're "upgrading" or "downgrading" your DB (via your migration scripts).

**Comment by paddelboot** [comment]
So "down" would be the same as a rollback?

**Comment by MasterOdin** [comment]
Yeah.
