### ISSUE TITLE
Foreign key drop / add (with the same name) in a single run results in mysql error

### ISSUE THREAD

**Issue by falkenhawk** [cakephp/phinx#1426]
With the introduction of the "Plan" dropping / adding a foreign key with the same name (e.g. in order to change ondelete behavior) results in an error in mysql - apparently it cannot handle it when it's compiled to a single query.
```sql
ALTER TABLE `module_challenges_taskslots` DROP FOREIGN KEY fk_module_challenges_taskslots_module_challenges_missions1, ADD  CONSTRAINT `fk_module_challenges_taskslots_module_challenges_missions1` FOREIGN KEY (`id_mission`) REFERENCES `module_challenges_missions` (`id`) ON DELETE CASCADE;
```
`[23000][1022] Can't write; duplicate key in table '#sql-1_3'`
In phinx <0.10.x this was split to two separate queries, afair.

Should AddForeignKey and DropForeignKey be grouped separately in \Phinx\Db\Plan\Plan::gatherConstraints (with drop being executed first of the two), perhaps?

an example failing (working before the upgrade to 0.10.x) migration:
```php
<?php

class ChallengeTaskSlotAdjustForeignKey extends AbstractMigration
{
	public function up()
	{
		$this->table('module_challenges_taskslots')
			// modify onDelete from SET NULL to CASCADE
			->dropForeignKey('id_mission')
			->addForeignKey('id_mission', 'module_challenges_missions', 'id', ['delete' => 'CASCADE', 'constraint' => 'fk_module_challenges_taskslots_module_challenges_missions1'])
			->update();
	}

	public function down()
	{
		$this->table('module_challenges_taskslots')
			// modify onDelete from CASCADE to SET NULL
			->dropForeignKey('id_mission')
			->addForeignKey('id_mission', 'module_challenges_missions', 'id', ['delete' => 'SET NULL', 'constraint' => 'fk_module_challenges_taskslots_module_challenges_missions1'])
			->update();
	}
}

```

**Comment by unhawkable** [comment]
Whatever works :) It would still need to be executed in two separate DROP, ADD queries though

...also if you wanted to change the column in foreign table it references to, and there is an index on the fk column already, it would need to be dropped according to this? https://stackoverflow.com/a/38777142/3729316 but i'm not sure... and that would need to be covered by changeForeignKey() method?

On the second thought, I think I'd rather keep dropForeignKey and addForeignKey without any usage restrictions as they are, just executing drops first and adds.

**Comment by lorenzo** [comment]
Yes, that is clear. I was thinking that the new method would capture the logic for doing this, with the multiple steps involved.

**Comment by martijngastkemper** [comment]
The same problems occurs when combining `renameColumn` and `changeColumn`. I looked into these bugs and was thinking about @lorenzo solution. But splitting the alter query must be done in `Phinx\Db\Adapter\PdoAdapter->executeActions()`. In that function the action are combined into one `AlterInstructions`. I think the functions must derive multiple `AlterInstructions` from `$actions`. Am I right or is there a more simple solution?

**Comment by lorenzo** [comment]
@martijngastkemper Almost, you are right that we need multiple AlterInstructions, but the splitting should be done in the `Plan` class. Specifically, it should detect this kind of conflicts and be able to separate the actions accordingly. This is the relevant method:

https://github.com/cakephp/phinx/blob/master/src/Phinx/Db/Plan/Plan.php#L172

**Comment by lorenzo** [comment]
@martijngastkemper Let me know if you would like to work on this and I can guide you through it :)

**Comment by martijngastkemper** [comment]
I would like to work on this problem. I looked at `resolveConflicts`, but that's to order the actions and group them by table. In `PdoAdapter` the actions are combined into one ALTER query. I think both functions have to be changed, am I right?

**Comment by lorenzo** [comment]
@martinssipenko Yes, I think you are right. The lazy version of the fix would be to though an exception in `resolveConflicts` explaining that you need two separate `save()` so it can work correctly. The fancy version is fixing the conflict for the user.

**Comment by lorenzo** [comment]
@martijngastkemper thanks a lot for you interest in fixing this, let me know if you need help!

**Comment by rquadling** [comment]
Dropping and creating a foreign key to allow us to control the `ON UPDATE` and `ON DELETE` clauses for mysql.

```sql
-- UP

ALTER TABLE `orders_items`
  ALGORITHM = INPLACE,
  DROP FOREIGN KEY `orders_items_ibfk_1`,

  ADD CONSTRAINT `fk_orders_items_to_orders` FOREIGN KEY (`orderID`) REFERENCES `orders` (`orderID`)
  ON UPDATE CASCADE
  ON DELETE CASCADE;
```

**Comment by martijngastkemper** [comment]
@lorenzo I'll first try the lazy version. Maybe it's possible to create a fancy solution from that point.

**Comment by lorenzo** [comment]
fixed in https://github.com/cakephp/phinx/pull/1523
