### ISSUE TITLE
Varchar not supported datatype

### ISSUE THREAD

**Issue by bramkorsten** [cakephp/phinx#1431]
I was wondering why `varchar` isn't supported by phinx. My database makes extensive use of it, and I would love to be able to use the `change()` command instead of just running a query in `up()` and `down()`

**Comment by rquadling** [comment]
AdapterInterface::PHINX_TYPE_STRING is what should be used. This is the engine agnostic way to say you want a variable length string as not all database engines use the keyword `varchar`.

**Comment by chrissound** [comment]
Wait what.... It's literally not supported?

**Comment by MasterOdin** [comment]
It is, it's just not referred to `varchar`, rather `string` (or `AdapterInterface::PHINX_TYPE_STRING` which maps to `string`).

```php
        $this->table('tags')->addColumn('short_name', 'string', ['limit' => 30])
              ->create();
```

that will give you a table `tags` with a `varchar(30)` column.

**Comment by othercorey** [comment]
@chrissound Please open a new issue if you have a problem to discuss. We don't encourage discussion in closed issues.
