### ISSUE TITLE
SQLite defaulting all columns to nullable

### ISSUE THREAD

**Issue by watermark** [cakephp/phinx#1446]
Version 0.10.6

When deploying to SQLlite, all columns (except identity) are defaulting to allowing null.  This behavior differs from all other adapters, so it should be corrected.  This issue seems to only occur when the default value of a column isn't set.

SQLite
`$def .= (!$column->isIdentity() && ($column->isNull() || is_null($default))) ? ' NULL' : ' NOT NULL';`

MySQL
`$def .= ($column->isNull() == false) ? ' NOT NULL' : ' NULL';`

**Comment by lorenzo** [comment]
Would you like to send a pull request to fix this?

**Comment by aldas** [comment]
if this is ever done - Phinx (semantic) version should reflect this as non-backwards compatible change. This would break users who rely on this behavior.

**Comment by dereuromark** [comment]
Fix merged to upcoming 0.12

**Comment by MasterOdin** [comment]
@dereuromark this can be closed (not sure why it was not auto-closed, but oh well).

**Comment by dereuromark** [comment]
Auto close only works on PRs against master
