### ISSUE TITLE
Invalid column type "smallinteger"

### ISSUE THREAD

**Issue by kabatak** [cakephp/phinx#1467]
I am trying to use the "[smallinteger](http://docs.phinx.org/en/latest/migrations.html#id2)" column: 

`->addColumn('foo', 'smallinteger')`

however I am getting this error:

> An invalid column type "smallinteger" was specified for column "foo".

Any ideas why? Thanks.

**Comment by phiter** [comment]
There is no support for `smallinteger`.
There's a list of the available columns in the [docs](https://book.cakephp.org/3.0/en/phinx/migrations.html#working-with-columns).

If you're using postgres, you can use `smallint`.
If you're using mysql, you'll need to pass `limit` option with `INT_SMALL` const from the `MysqlAdapter` class, like this:

`->addColumn('foo', 'smallinteger', ['limit' => MysqlAdapter::INT_SMALL])`

Of course, you need to add it to the uses:

`use Phinx\Db\Adapter\MysqlAdapter;`

**Comment by kabatak** [comment]
@phiter Thanks. I guess the [docs ](http://docs.phinx.org/en/latest/migrations.html#id2) need to be updated with that info.

**Comment by phiter** [comment]
I believe this info can be found in it [Limit Option and MySQL](http://docs.phinx.org/en/latest/migrations.html#limit-option-and-mysql).

**Comment by MasterOdin** [comment]
I wonder if that should be `smallint` in the docs that @kabatak linked to, not `smallinteger`.

It'd also be useful for you to say what DB you're using this against @kabatak.

**Comment by kabatak** [comment]
@MasterOdin `smallint` also returns `An invalid column type...` error.
I'm using MySQL and I guess the solution as pointed out by @phiter is to use the `Phinx\Db\Adapter\MysqlAdapter` constants. Although it would be nice if Phinx can automatically do that behind the scenes instead.

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/pull/1633
