### ISSUE TITLE
Rollback problems with index and foreign key adding in same change method

### ISSUE THREAD

**Issue by egorbwork** [cakephp/phinx#1468]
When I tried to upgrade phinx to version 0.10.0. Following case is not any more possible to rollback:
```
public function change()
{
        $table = $this->table('my_table');
        $table->addForeignKey('entity_id', 'my_another_table', 'id', [
            'delete' => ForeignKey::CASCADE,
            'update' => ForeignKey::CASCADE,
            'constraint' => 'my_another_table_foreign_key'])
            ->addIndex(['entity_id'], ['unique' => true])
            ->update();
}
```

The response from console is:
` SQLSTATE[HY000]: General error: 1553 Cannot drop index 'entity_id': needed in a foreign key constraint  `

Is there any solution for this?

**Comment by ArtemGoutsoul** [comment]
the order of dropping column, foreign key and index in rollback is wrong, it's a clear regression

**Comment by lorenzo** [comment]
would you mind showing the generated SQL that triggers the problem?

**Comment by egorbwork** [comment]
What I get on -vv: 
```
START TRANSACTION
 -- Altering table my_table
ALTER TABLE `my_table` DROP INDEX `entity_id`
```

And after:
`SQLSTATE[HY000]: General error: 1553 Cannot drop index 'entity_id': needed in a foreign key constraint `

**Comment by ArtemGoutsoul** [comment]
Any workarounds for now?

**Comment by ArtemGoutsoul** [comment]
> 2 migrations: one for the index and other for the foreign key.

This would require refactoring all past migrations, which is not viable...
