### ISSUE TITLE
Helpers method from CakePhp are conflicting with Laravel ones

### ISSUE THREAD

**Issue by egorbwork** [cakephp/phinx#1469]
Unfortunately after update to last version of the Phinx, I can't say any more that it is `PHP Database Migrations For Everyone`. If there are some painless possibilities to use library with other frameworks other than CakePhp. Please give a hint.

**Comment by garas** [comment]
See discussion at https://github.com/cakephp/cakephp/issues/12669

**Comment by egorbwork** [comment]
Thanks.
