### ISSUE TITLE
Postgres: truncate doesn't reset auto increment

### ISSUE THREAD

**Issue by Wtyd** [cakephp/phinx#1474]
The truncate on Postgres's BDD doesn't reset the auto increments by default. For this, we have to add 'RESTART IDENTITY' to the query:

`TRUNCATE TABLE table_name RESTART IDENTITY`

The current behavior of truncate doesn't reset auto increment and there is no option to force it. The only way is with a raw sql script.

Should be truncate with reset auto increments the default behavior?

Thanks

**Comment by rakshazi** [comment]
Faced same issue. Please, document that behavior or add fix to phinx logic

Thank you

**Comment by lorenzo** [comment]
Would you like to help doing either of those?

**Comment by rakshazi** [comment]
added pr with fix

**Comment by JKingweb** [comment]
Note that SQLite is similarly deficient. I'll write some tests and submit a patch when I have a bit of time.
