### ISSUE TITLE
Adapter for mongo

### ISSUE THREAD

**Issue by garipovazamat** [cakephp/phinx#1482]
I want to add adapter for mongo but I don't know how to add dependencies in composer.json. If I insert "mongodb/mongodb" dependency in composer.json, so will need to exist mongodb driver extention in php for user, otherwise will throw error when user execute composer install and he will be need to execute `composer install --ignore-platform-reqs`.
How I can do better to add mongo driver in project?

**Comment by garipovazamat** [comment]
#1510

**Comment by dinesh419** [comment]
For python we can use pymongo as an adapter for connecting to MongoDB database.

**Comment by garipovazamat** [comment]
@dinesh419 How we can use pymongo in this project? This is in php language.

**Comment by dereuromark** [comment]
PR open
