### ISSUE TITLE
Migration on Multiple Database migration

### ISSUE THREAD

**Issue by aksharaCaprice** [cakephp/phinx#1483]
How to do migration on multiple databases  from a single environment ? 
eg: below given are multiple database name 
customer1_application
customer2_application
customer3_application
customer4_application
How to run same migration in all databases ?

**Comment by lorenzo** [comment]
Have many different configuration files, and run sphinx pointing it to each different configuration

**Comment by aksharaCaprice** [comment]
In my scenario I have 100's of databases it is difficult to run 100 migrations separately . From table I can get  all the database name is there any other solution to do migrations in all databases by running single migration.

**Comment by broberts-mrmc** [comment]
This use case is contemplated by #180

**Comment by lorenzo** [comment]
@aksharaCaprice care to explain what the difficult part would be? You could even point to the same config file but pass different environment variables. The config files supports that. You just need to call sphinx in a loop for each database. That's the logic phinx would have to do anyway

**Comment by suryacaprice** [comment]
Hi @lorenzo 
I work with akshara . Sorry for the late reply . Our product is a multitenant application. Ex : Customer 1 --> customer 1 db , Customer 2 ---> customer 2 db .. this is exponential increase and the db name changes dynamically as the customer base grows. Is there a way to handle it ? Do you have any scripts to handle the dynamic database name change in phinx . Without which we cant use the phinx into our application . I am sure many products use the same concept
