### ISSUE TITLE
Using Phinx with PHPUnit

### ISSUE THREAD

**Issue by paddelboot** [cakephp/phinx#1484]
Hello,

I'm trying to set up a fixture for an integration test using a PDO sqlite in-memory database. I'm looking at the [documention](http://docs.phinx.org/en/latest/commands.html#using-phinx-with-phpunit):

        $configArray = require('phinx.php');
        $configArray['environments']['test'] = [
            'adapter'    => 'sqlite',
            'connection' => $pdo
        ];

This results in an error, because `app/phinx.php` is just a class loader for `PhinxApplication` apparently:

`Error: Cannot use object of type Phinx\Console\PhinxApplication as array`

How can I therefore setup a fixture as explained in the docs with the current version of Phinx? Thanks.

**Comment by paddelboot** [comment]
Sorry, I was a bit confused; the `phinx.php` is supposed to be the PHP configuration file, not the `app/phinx.php` from the vendor dir.

**Comment by paddelboot** [comment]
My `phinx.php` config file now looks as follows:

    return [
       "paths" => [
        "migrations" => "pci-app/db/migrations"
       ]
    ];

I have the `setUp` method in my integration test class:

    public function setUp() {
        $pdo = new PDO( 'sqlite::memory:', null, null, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
        ] );
        $configArray = require('phinx.php');
        $configArray[ 'environments' ][ 'test' ] = [
            'adapter' => 'sqlite',
            'connection' => $pdo,
            'table_prefix' => 'nx24_2_'
        ];
        $config = new Config( $configArray );
        $manager = new Manager( $config, new StringInput( ' ' ), new NullOutput() );
        $manager->migrate( 'test' );
        $manager->seed( 'test' );
    }

Running phpunit, I get another error:

`PDOException: SQLSTATE[HY000]: General error: 1 near "(": syntax error`

Any help how to proceed from here?

**Comment by paddelboot** [comment]
Okay, that already helps. The migration is:

    public function change() {

		$call = $this->table( 'call' );

		$call->addColumn( 'Uuid', 'string', [ 'limit' => 40 ] )
				->addColumn( 'CallerNumber', 'string', [ 'limit' => 40 ] )
				->addColumn( 'DestinationNumber', 'string', [ 'limit' => 40 ] )
				->addColumn( 'Creation', 'timestamp', [
					'timezone' => true,
					'default' => Literal::from( 'now()' )
				] )
				->addIndex( [ 'uuid' ], [ 'unique' => true ] )
				->create();
	}

I changed it to `'CURRENT_TIMESTAMP'` and the issue seems to go away. Not sure where the `now()` came from. Thanks again.

**Comment by Marcin-TA** [comment]
Hi! Is there any way to run migration from the specific directory? I have unit tested on which I need to create just 3 tables and some seeds, so I don't want to run all the migrations/seeds files.
