### ISSUE TITLE
Add Composer dependencies for required PHP extensions

### ISSUE THREAD

**Issue by halfer** [cakephp/phinx#1490]
I just ran `phinx migrate` in an Alpine/PHP environment, and found that it blew up because the `json` extension was not installed. Can a PHP extension dependency be added to `composer.json`? This will ensure Composer fails gracefully based on an unavailable dependency.

I believe this is done using `ext-json` in the `require` section.

If a core dev is :+1: then ping me and I will raise a PR.

**Comment by lorenzo** [comment]
I'm ok with this

**Comment by halfer** [comment]
Great. Are there any other exts that are needed? I can add them at the same time.

**Comment by dereuromark** [comment]
Only add whats required. Your IDE (e.g. phpstorm) will usually tell you in the files.

**Comment by halfer** [comment]
@dereuromark: I'm on NetBeans, it's not quite that fancy :grin:. No matter, it was only if someone knew some extensions off the top of their head. I'll get `json` done for now.

**Comment by dereuromark** [comment]
PR open
