### ISSUE TITLE
Phinx option didn't recognize.

### ISSUE THREAD

**Issue by Sasukenshin** [cakephp/phinx#1504]
Hi everybody,

I have a project in my enterprise, and we choose to use phinx to relate our php code to our mysql database. We have installed composer and phinx and it works fine. However recently we have found a bug, and we still can resolve it that the reason I came here. When we try to launch a phinx command with option we got a symphony error who says that this option is unknown. . . But when I tape the -help on this command the option exist??? I am in 5.6.38 version for PHP 

See a basic exemple 

![image](https://user-images.githubusercontent.com/8657020/53244972-af9baa00-36ac-11e9-974a-dfd390f11e0f.png)

Here is the composition of my composer.json

![image](https://user-images.githubusercontent.com/8657020/53244943-94c93580-36ac-11e9-9c5e-70533cd0cc69.png)

My phinx.yml if needeed

![image](https://user-images.githubusercontent.com/8657020/53245083-0b663300-36ad-11e9-9cc9-c867a2a79e44.png)

I got this problem on all option phinx first of all I think that -s option was not understand by composer but it comes from Symphony so I think it's purely phinx problem . . .

If u guys have, any idea thanks will appreciate the help.

**Comment by dereuromark** [comment]
Is this still an issue?

**Comment by MasterOdin** [comment]
When using composer to run scripts (e.g. `composer phinx:win` in this example), any options or arguments that start with a `-` must come after a `--` or else they get interpreted as being flags to composer itself. See the second paragraph in the [composer docs](https://getcomposer.org/doc/articles/scripts.md#running-scripts-manually).

So for you, you would want to do:
`composer phinx:win seed:run -- -vv -s TraductionSeederId`

@dereuromark I think this can be closed given there's nothing to do on phinx for this.
