### ISSUE TITLE
delete multiple row

### ISSUE THREAD

**Issue by shyandsy** [cakephp/phinx#1508]
Is there any way to perform delete with multiple conditions?

````
delete by single condition
<?php
$builder = $this->getQueryBuilder();
$builder
    ->delete('users')
    ->where(['accept' => false])
    ->execute()
````

````
delete by multiple condition
<?php
$builder = $this->getQueryBuilder();
$builder
    ->delete('users')
    ->where(['accept' => false] or ['language' => "en"])  // like this
    ->execute()
````

**Comment by saeideng** [comment]
>->where(['accept' => false] or ['language' => "en"])  // like this

```php
->where([
        'OR' => [['accept' => false], ['language' => "en"]],
    ]);
```

see docs for more info 
https://book.cakephp.org/3.0/en/orm/query-builder.html#advanced-conditions

phinx uses cakephp/database package 
https://github.com/cakephp/database

**Comment by shyandsy** [comment]
thanks you so much

there is no mention the cakephp doc 
http://docs.phinx.org/en/latest/migrations.html#dropping-a-table

![image](https://user-images.githubusercontent.com/5271457/53677764-df354e00-3c7a-11e9-91c7-2bd46dd9c8a0.png)

**Comment by saeideng** [comment]
mentioned here to cakephp/database package
http://docs.phinx.org/en/latest/migrations.html#using-the-query-builder

```
The Query builder is provided by the cakephp/database project,
 and should be easy to work with as it resembles very closely plain SQL.
 Accesing the query builder is done by calling the getQueryBuilder() function:
```

feel free to open a PR and add the cakephp doc link

**Comment by saeideng** [comment]
also there are more examples here that mentioned in the phinx docs
https://github.com/cakephp/database#where-conditions
