### ISSUE TITLE
When new release will be available?

### ISSUE THREAD

**Issue by developer-devPHP** [cakephp/phinx#1511]
You did a lot of changes since your last release and all that changes in master branch.  So my question is when you are going to create new release with all this changes?

**Comment by dinesh419** [comment]
Once the development is done, will be testing the code in UAT. Finally, the data will be available for new release.

**Comment by lpj145** [comment]
i think a config env by parse and files are a failure, is not possible inject config by constructor application ? your have plans to change it ?

**Comment by josegonzalez** [comment]
We will make a new release once we feel comfortable about the stability of the master branch.
