### ISSUE TITLE
DropForeignKey and RemoveColumn in the same migration can conflict

### ISSUE THREAD

**Issue by Firehed** [cakephp/phinx#1514]
I recently started the process of upgrading from v0.9.2 to v0.10.6, and discovered a weird interaction (in MySQL): Phinx now generates two queries to drop the FK and the corresponding column, but tries to drop the column before the FK. This results in `SQLSTATE[HY000]: General error: 1553 Cannot drop index 'page_id': needed in a foreign key constraint`

It's pretty easy to work around by tweaking the migration, but it would be nice if the two queries ran in the correct order by default so that  wouldn't be necessary.

Migration (this worked in 0.9.2 since it was a bunch of queries):

```php
    public function up()
    {
        $this->table('pages')
            ->dropForeignKey('state')
            ->removeColumn('state')
            ->update();
    }
```

Schema pre-migration (irrelevant columns removed for brevity):

```sql
CREATE TABLE `pages` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `state` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `state` (`state`),
  CONSTRAINT `pages_ibfk_2` FOREIGN KEY (`state`) REFERENCES `scrape_states` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

Dry-run SQL output:

```sql
START TRANSACTION
ALTER TABLE `pages` DROP COLUMN `state`
ALTER TABLE `pages` DROP FOREIGN KEY pages_ibfk_2
COMMIT
INSERT INTO `phinxlog` (`version`, `migration_name`, `start_time`, `end_time`, `breakpoint`) VALUES ('20180315164720', 'RemoveOldColumnsFromPage', '2019-03-28 19:13:57', '2019-03-28 19:13:57', 0);
```

**Comment by dinesh419** [comment]
This query can give the result as u have expected, there will not be any conflict. 
START TRANSACTION
ALTER TABLE `pages` DROP COLUMN `state`
ALTER TABLE `pages` DROP FOREIGN KEY pages_ibfk_2

**Comment by dinesh419** [comment]
This query can give the result as u have expected, there will not be any conflict.
START TRANSACTION
ALTER TABLE pages DROP COLUMN state
ALTER TABLE pages DROP FOREIGN KEY pages_ibfk_2

**Comment by dereuromark** [comment]
PR open.
