### ISSUE TITLE
Phinx is slowing down every project that has it as a requirement

### ISSUE THREAD

**Issue by alexskra** [cakephp/phinx#1520]
**I thought Phinx as a dependency would be fine**
So my thought was that adding Phinx as a dependency would be a non-issue. I'd only use it once for migration on deployments and since autoloading is a thing it wont ruin the service by tanking performance. I think that's a fair assumption.

**But dependencies can be evil**
But now in v0.10 Phinx has added cakephp dependencies that does something very stupid: The dependencies are adding files as requirements.

**Why is that bad?**
The code in the required files are executed on every single request. It's absolutely pointless and can have a significant effect on the performance of lightweight applications.(reduces performance to ~82 % in my situation)

https://getcomposer.org/doc/04-schema.md#files

> If you want to require certain files explicitly on every request then you can use the files autoloading mechanism.

Here's the thing. Phinx is usually used from the CLI, and rarely from inside code itself. But these dependencies results in phinx dependency code getting executed on every single page load even if it has nothing to do with phinx. That is bad and can cause performance issues.

**Possible solutions**
Some possible solutions is to remove dependencies that doesn't respect performance, find something better to depend on or rewrite Phinx so it doesn't need dependencies that affects performance.

Dependencies that are causing problems:

- cakephp/collection
- cakephp/database (requires cakephp/core that causes the problem)

**Comment by broberts-mrmc** [comment]
This is not an experience I’ve had. Does your app’s bootstrapping process instantiate Phinx?

**Comment by aleskr** [comment]
Well, that is how it works. All you have to do is to include the composer autoloader, you don't have to do anything with sphinx, just adding it as a dependency is enough, and that's why it's a problem.

**Comment by josegonzalez** [comment]
How are you gauging the performance change? Do you have a reproduction here we can run?

**Comment by aleskr** [comment]
You can measure it however you want, either by benchmarking the whole stack or just profiling a run.

1. Create a PHP file and require the autoloader generated by composer.
```php
<?php
require 'vendor/autoload.php';
```
2. Measure/profile or whatever.
3. Install Phinx.
4. Congratulations, you now have additional code that is executed on every request!

**Comment by broberts-mrmc** [comment]
In my experience, auto loaders are “registered” [only] and registering an auto loader should not cause [additional] PHP source files to be read or code within those files to be interpreted/executed until an object is instantiated for which no corresponding class has yet been defined, which I assume includes objects defined by Composer-managed dependencies. In other words, Phinx or CakePHP objects must be instantiated somewhere to “trigger” those source files to be read, interpreted, etc. It would be interesting to see the call stack for a request in your app to understand how/where Phinx or CakePHP objects are being instantiated.

**Comment by MasterOdin** [comment]
Except that cakephp/collection and cakephp/core both use the [autoload:files](https://getcomposer.org/doc/04-schema.md#files) functionality which means that just having them installed will mean that composer will include the functions.php files from those two projects on every page load, though they are relatively small and it's not particularly clear that they would take any significant time to run (and I couldn't see a difference in a quick test).

**Comment by josegonzalez** [comment]
@aleskr thanks for that.

What you basing _your_ number off of? I'd like to know how you measured that number so that I can simulate it on my own system.

**Comment by aleskr** [comment]
@josegonzalez In my case the performance difference amounts to a ~18 % drop in performance, from ~16k to ~13k rps, in my codebase, benchmarked with and without phinx as a requirement in the project. That is quite significant, especially for something that does nothing at all.

If you want to simulate it you can just do what I described in my previous comment. Include the autoloader generated by composer and use something like ab, wrk or hey to benchmark it with and without phinx as a dependency, eg:

```
mkdir example && cd example
composer init --no-interaction && composer install
echo -e "<?php\nrequire 'vendor/autoload.php';\necho 'Hello world';\n" > script.php

# Serve the folder using nginx, apache or whatever.

# Benchmark
wrk -t4 -c50 -d20s http://127.0.0.1/script.php

# Add Phinx.
composer require robmorgan/phinx

# Benchmark
wrk -t4 -c50 -d20s http://127.0.0.1/script.php
```

Result without Phinx:
```
Running 20s test @ http://127.0.0.1/script.php
  4 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.14ms  317.76us  15.34ms   89.55%
    Req/Sec     5.64k   479.32     7.07k    89.62%
  449197 requests in 20.01s, 85.66MB read
Requests/sec:  22450.74
Transfer/sec:      4.28MB
```

With Phinx:
```
Running 20s test @ http://127.0.0.1/script.php
  4 threads and 50 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.53ms  391.97us  16.64ms   90.15%
    Req/Sec     4.76k   652.01    18.49k    90.26%
  379775 requests in 20.10s, 72.42MB read
Requests/sec:  18894.59
Transfer/sec:      3.60MB
```

Difference:  ~ -16 % performance with phinx.

Strangely enough the difference is larger on my servers. 

I first noticed this when I updated dependencies and deployed a new build to production and everything went to hell. All of a sudden multiple dependencies in my project had added other dependencies that did this. Requests was taking over three times as long and the servers was overloaded and the service went down. Not a great experience.

My point is that relying on dependencies that does this is clearly bad practice and will reduce performance even if the dependency is unused in the current request.

**Comment by jawngee** [comment]
The other issue we've run into is that these loaded files are declaring functions with the same names as some other functions declared elsewhere which is causing fatal errors.

These are the packages loading files:

https://github.com/cakephp/core/blob/master/composer.json
https://github.com/cakephp/collection/blob/master/composer.json
https://github.com/cakephp/utility/blob/master/composer.json

It also appears that `symfony/polyfill-ctype`, `symfony/polyfill-mbstring` and `myclabs/deep-copy` also autoload files.

Our workaround is:

- Git cloning phinx to a separate unrelated directory
- composer install
-  symlinking `./bin/phinx` to `/usr/local/bin/phinx`

Seems to work but we just got started using it.

**Comment by jawngee** [comment]
I feel like the best practice is that autoloaded files in composer only autoload namespaced functions.

**Comment by lorenzo** [comment]
Two possible solutions:

1. Only load Phinx as a dev dependency. I really cannot think of a reason why you would use phinx un production. 
2. Use the authoritative class map flag in composer. This will improve the clsss loading part a bit.

Future:
- lobby in the php language committee for a way to autoload functions, which seems to be one on the root causes of this issue.

**Comment by jawngee** [comment]
You need it in production for running migrations when deploying to staging/production so using it as a dev dependency doesn't make much sense.

I think the best option is this thing is wrapped up like WP-CLI or composer as a phar.  It doesn't make any sense that it's added as a dependency via composer to a project, imho.  It should be a system tool.

**Comment by dereuromark** [comment]
Actually, phinx should not be installed as require-dev only, but require. When you properly deploy an app to a production server you want it to be there to execute the migrations.

**Comment by dereuromark** [comment]
I agree, an independent tool could be the solution here.

**Comment by lorenzo** [comment]
That of course depends on how you execute your deployments. I personally do it in two steps, and don’t require migrations to be part of the production bundle. The first step is to checkout the app somewhere else, and run migrations there. Once completed, the app is deployed.

**Comment by lorenzo** [comment]
I also agree that a separate tool is desirable.

**Comment by broberts-mrmc** [comment]
It seems part of the issue is also auto loading of functions into the global namespace.  For what it’s worth, using class static methods also triggers auto loading, so it’s possible to leverage auto loading for “function-like” symbols and avoid cluttering the global namespace (e.g. Cake::h() instead of h()). I also agree that an external tool not managed like a Composer dependency would increase isolation between Phinx and apps that use it.

**Comment by aleskr** [comment]
Having a separate tool is not a bad idea, but I do prefer to have it in composer. It's nice to be able to pull a repo and run `composer install && vendor/bin/phinx migrate` and be done.

If these dependencies gets fixed or preferably removed this won't be a problem and people can use it however they want without any issues.

Description of the project:
> Phinx is just about migrations without all the bloat of a database ORM system or framework.

It used to be case before v0.10, but then bloat from a framework was added, so that statement is no longer true. :(

**Comment by lorenzo** [comment]
@aleskr can you send a PR to remove that misleading line? Phinx is a migrations framework, there’s no other goal than being good at doing migrations in php.

**Comment by lorenzo** [comment]
@aleskr just as at small piece of advice for you: make sure you run your server with opcache enabled and with revalidation of files set to 0, otherwise the time spent in loading files will always be significant. With those options enabled, you will see dramatic changes for the better.

**Comment by rquadling** [comment]
> That of course depends on how you execute your deployments. I personally do it in two steps, and don’t require migrations to be part of the production bundle. The first step is to checkout the app somewhere else, and run migrations there. Once completed, the app is deployed.

This is a critical step towards continuous integration/continuous deployment. Some notes on our approach : https://gist.github.com/rquadling/942253b0ccebd2a0a3c3d6030524fdb0

**Comment by lorenzo** [comment]
Those are great notes @rquadling, maybe we should have a docs page with those as best practices. Like not having phinx in the production bundle and running migrations as a separate step before deployment.

**Comment by rquadling** [comment]
@lorenzo Sounds like a good idea. The approach works for us. There are 2 few elements that are not Phinx (protect migrations + sync migrations, and repeatables), but these are our implementations of the idea, so how a team wishes to handle them is not constrained to this.
