### ISSUE TITLE
How can I achieve the following using Phinx migration?

### ISSUE THREAD

**Issue by rahimnagori** [cakephp/phinx#1534]
Suppose there are two table : 
TableOne
TableTwo
TableTwo has a column name `tableOne_id`.
I want to execute the following query.
```
$TableOne_records = $this->execute("SELECT * FROM `TableOne` WHERE /* Followed by some condition */ ;");
foreach($TableOne_records $key => $value){
	$tableTwo_record = $this->execute("SELECT * FROM `TableTwo` WHERE `tableOne_id` = " .$value['id'] ."AND /* Followed by any condition(s) */ ;");
	$this->execute("UPDATE `TableTwo` SET `col1` = 'some Value', `col2` = 'Some value' WHERE `id` = " .$tableTwo_record['id'];");
}
```

**Comment by vibby** [comment]
You can achive that in pure SQL, look at «INSERT INTO SELECT». 
An example ressource : https://www.sqlshack.com/sql-insert-into-select-statement-overview-and-examples/
Or you can ask any SQL expert
