### ISSUE TITLE
SQLite: Poor support for multiple databases

### ISSUE THREAD

**Issue by JKingweb** [cakephp/phinx#1536]
Pursuant to #1535, the SQLite adapter has only token support for multiple databases, in `createDatabase` and `dropDatabase`. It should be possible to expand this to include attaching databases when they are referred to, though it would likely require the following changes:

- `quoteTableName` would have to be modified to treat everything before the _last_ dot in a table name to be the database (e.g. `'files/primary.db.table' -> "files/primary.db"."table"`)
- Databases could either be required to be enumerated by the user via some new method, or attached automatically when first encountered and/or when created
- Any references to `SQLiteAdapter::$options['name']` should be transformed into `main`

Databases being attached automatically might be surprising if the user executes arbitrary SQL assuming the database will already be attached.

**Comment by dereuromark** [comment]
PR welcome.
At this point multi dabase is not supported for most DBs though.
