### ISSUE TITLE
SQLite: Index handling is completely broken

### ISSUE THREAD

**Issue by JKingweb** [cakephp/phinx#1544]
Phinx is currently absolutely hopeless when finding, listing, re-creating, or dropping indices for an SQLite database. The root cause is [a particular line](https://github.com/cakephp/phinx/blob/2bdeffc5b828baf79fa4d2761aa153e8f2972fb9/src/Phinx/Db/Adapter/SQLiteAdapter.php#L676) which overwrites an array key in a loop instead of pushing to the end of the array. Thus, whatever last index SQLite reports internally is all Phinx ends up knowing about. It also doesn't distinguish between incidental indices created by constraints (which are an implementation detail) and actual indices which can be dropped  and need to be re-created when altering a table.

**Comment by lorenzo** [comment]
Can you send a pull request to fix this please?

**Comment by JKingweb** [comment]
Working on one presently. Code is basically done, but tests will take a little longer.

**Comment by JKingweb** [comment]
Question: What is the fundamental purpose of `hasIndex()`? Is it supposed to answer the question "Does an index with these and exactly these columns exist?", or is supposed to instead answer the question "Is there a usable index covering these columns?"

**Comment by lorenzo** [comment]
It is supposed to answer `Does an index with these and exactly these columns exist?`
