### ISSUE TITLE
"The JSON data did not pass validation" building Phar

### ISSUE THREAD

**Issue by burgoyn1** [cakephp/phinx#1559]
Anyone else getting this error?

Running:
php 7.2.19
box 2.7.5

I have determined if I remove line 33 "exclude-composer-files": false from the box.json file it will then build, but it won't work as it has not included the composer files to be able to actually run.

**Comment by dereuromark** [comment]
Can we close this then or do we need some follow up here?

**Comment by MasterOdin** [comment]
@dereuromark Would it be worthwhile to make producing a phar file with box be a worthwhile addition to the .travis.yml pipeline for any cut releases on GH? I think that might be the nicest way as it then ensures the box.json file is kept up-to-date and working, and people who want the phar file for whatever reason have an easy way to get it.
