### ISSUE TITLE
Can't update database in migration

### ISSUE THREAD

**Issue by christhomas** [cakephp/phinx#1563]
I'm trying to run a loop over a particular large database table which can't be loaded into memory at the same time. I can't really see much wrong with what I wrote. But perhaps there is something I'm missing.

The up() method looks like this

```
$processed = 0;
$tables = "countries"

while(true){
	/** @var PDOStatement $stmt */
	$stmt = $this->query("select id,name from $table order by id limit 100 offset $processed");

	if($stmt->rowCount() === 0){
		print("No more data in table '$table'\n");
		break;
	}

	while($row = $stmt->fetch()){
		$id = $row["id"];
		$this->execute("update $table set slug='hello' where id='$id'");
		$processed++;
	}
}
```

At the end, I expected that the table would hold slugs with hello in them. But to my surprise, it's a completely empty column.

What am I doing wrong here? I must be blind to something.

**Comment by garas** [comment]
From php [docs](https://www.php.net/manual/en/pdostatement.rowcount.php):

For most databases, `PDOStatement::rowCount()` does not return the number of rows affected by a SELECT statement. Instead, use `PDO::query()` to issue a `SELECT COUNT(*)`.

**Comment by christhomas** [comment]
Dude, please don't close issues without fully understanding the issue. It's premature and a little bit hostile.

The problem is not that it doesn't find any rows. Actually, it processes the entire table. I've output each and every query that it makes against the server. It does actually run the update, it just doesn't actually update anything.

So, discount what you said, as in this case it does return a result of 230 rows. It does run through the entire table. What you have said. Is not the problem

**Comment by christhomas** [comment]
I wrote some debugging output and here is a snippet

It's just a simple var_dump of the table, slug, id, and the query it generated

```
string(9) "countries"
string(13) "united states"
string(3) "230"
query = 'update countries set slug='hello' where id='230''
```

**Comment by christhomas** [comment]
If I run this query inside an sql program. It updates the table. But this query executed in phinx. Doesn't update the table. The slug field is still empty.

**Comment by lorenzo** [comment]
Maybe you are not committing the transaction?

**Comment by christhomas** [comment]
I've looked at other examples of using query/execute and I can't see them calling save(). I've only used save() when running modifications on a table and the examples in the docs do this in the same way. So I'm really lost when nothing is happening and getting written to the database. The logs don't reveal anything untoward.

**Comment by lorenzo** [comment]
can you show you full migration file?

**Comment by christhomas** [comment]
Sure, also maybe it's important, but it's running against a mariadb:latest docker image

```
<?php
use Phinx\Migration\AbstractMigration;

class AddSlugs extends AbstractMigration
{
    private function addSlug($table)
    {
        $table = $this->table($table);
        $table->addColumn("slug", "string", ["null" => false, "after" => "name"])->save();
    }

    private function removeSlug($table)
    {
        $this->table($table)->removeColumn("slug")->save();
    }

    private function processTable($table)
    {
        print("Processing Table: $table\n");

        //$this->addSlug($table);

        $count = $this->fetchRow("select count(id) as count from $table");
        $count = intval($count["count"]);

        if($count === 0){
        	die("This count is invalid");
		}

        $processed = 0;

		$builder = $this->getQueryBuilder();

        while(true){
			/** @var PDOStatement $stmt */
			$stmt = $this->query("select id,name from $table order by id limit 100 offset $processed");

			if($stmt->rowCount() === 0){
				print("No more data in table '$table'\n");
				break;
			}

			while($row = $stmt->fetch(PDO::FETCH_ASSOC)){
				$id = $row["id"];
				$text = $row["name"];
				$slug = "-";

				$text = htmlentities($text, ENT_QUOTES, 'UTF-8');
				$text = preg_replace('~&([a-z]{1,2})(acute|cedil|circ|grave|lig|orn|ring|slash|th|tilde|uml);~i', '$1', $text);
				$text = html_entity_decode($text, ENT_QUOTES, 'UTF-8');
				$text = preg_replace(array('~[^0-9a-z'.preg_quote($slug,'~').']~i', '~[ -]+~'), $slug, $text);
				$text = trim($text, " -");
				$text = strtolower($text);

				if(empty($text)) $text = "";

				var_dump($table, $text, $id);
				// no effect
				//$builder->update($table)->set('slug', $text)->where(['id', $id])->execute();

				// no effect
				$this->query($q="update $table set slug='$text' where id='$id'");

				// no effect
				//$this->execute($q="update $table set slug='$text' where id=$id");

				print("query = '$q'\n");

				//return;
				//die();

				$processed++;
				$percent = ($processed / $count) * 100;
				if($processed % 1000 === 0){
					print("Processed rows[$id]: '$processed' of '$count', $percent% complete, memory used = ".floor(memory_get_usage(true)/1024)."KB\n");
				}
			}
		}
    }

    public function up()
    {
    	$this->execute("update countries set slug=''");
//		$this->addSlug("countries");
//		$this->addSlug("regions");
//		$this->addSlug("cities");

        $this->processTable("countries");
		die();
        $this->processTable("regions");
        $this->processTable("cities");
    }

    public function down()
    {
        $this->removeSlug("countries");
        $this->removeSlug("regions");
        $this->removeSlug("cities");
    }
}
```

**Comment by garas** [comment]
Could you try to `return` instead of `die()`  in `up()`.

Migration is executed in transaction, and `die()` aborts it and does not save changes.

**Comment by christhomas** [comment]
what if this loop is 2.7 million entries long? it's not commiting any of those queries? all 2.7 million of them :/ hmmmmm that doesn't sound good. But yeah I can try what you suggest. But is there a way to not use transactions cause I have a feeling this migration will or at least should kill something

**Comment by garas** [comment]
You can commit transaction before updates, and begin new transaction again in the end so it will be in transaction on finish

**Comment by christhomas** [comment]
I don't see anything in the phinx manual about transactions. Do I just issue begin transaction/commit sql calls on the adapter connection directly?

**Comment by garas** [comment]
`up()` is executed here

https://github.com/cakephp/phinx/blob/c34ace8a284953043f36386c92fa9326483e00ac/src/Phinx/Migration/Manager/Environment.php#L128

So yes, call commit/begin transaction on adapter.

**Comment by christhomas** [comment]
Whenever I try to commit, I get this message "There is no active transaction". Seems that this function doesn't use transactions.

**Comment by emimarz** [comment]
I "suffer" something similar and I change my query builder query to something like this (I pick your code and change it)
$this->query("update $table set slug='$text' where id='$id'")->execute();
