### ISSUE TITLE
Bug: inserting multiple rows fails when keys are modified

### ISSUE THREAD

**Issue by skript-cc** [cakephp/phinx#1565]
I just encountered an issue with a migration. On inserting multiple rows of data with `$this->table('my_table')->insert($data);` the migration failed with multiple error notices: "PHP Notice:  Array to string conversion in /var/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php on line 306" and finally "SQLSTATE[42S22]: Column not found: 1054 Unknown column '2' in 'field list'."

Some debugging lead me to this line: https://github.com/cakephp/phinx/blob/7187e558ab70d5ac2197d197234ce6a5faf5cfbf/src/Phinx/Db/Table.php#L591. Turns out that the check to determine whether to insert multiple rows or a single row expects the key of the first item to be zero. Since I was building my array dynamically and ran it through array_map and array_filter, the first item happened to have 2 as it's key. Running my array through array_values before passing it to the insert function solves my issue, but it would be nice if this is done in the insert method (`$data = array_values($data);` would do the trick).

**Comment by lorenzo** [comment]
Can you send us a pull request? You seem to have a good solution in mind already :)

**Comment by skript-cc** [comment]
Yes, I'll see what I can do.
