### ISSUE TITLE
Dry run - missing semicolons in some some cases

### ISSUE THREAD

**Issue by raph1mm** [cakephp/phinx#1567]
IMO I'd be useful if --dry-run option generated working SQL script. I does not for now - I've noticed missing semicolons after:

- START TRANSACTION
- COMMIT
- ALTER TABLE

**Comment by dereuromark** [comment]
Are you able to make a PR with the suggested changes?

**Comment by raph1mm** [comment]
I'm not sure, but I'll try to figure out the solution when I'll have some free time. :)

**Comment by dereuromark** [comment]
PR open
