### ISSUE TITLE
Test\Phinx\Migration\ManagerTest::testPostgresFullMigration tests MySQL database

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1574]
I noticed this when I was testing something else, but it looks like this test actually tests against mysql and not postgres. If I have a postgres database running and a mysql not running, I get the following error trying to run the test:

```
1) Test\Phinx\Migration\ManagerTest::testPostgresFullMigration
InvalidArgumentException: There was a problem connecting to the database: SQLSTATE[HY000] [2002] Connection refused

/Users/mpeveler/Work/Github/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php:127
/Users/mpeveler/Work/Github/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:136
/Users/mpeveler/Work/Github/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:167
/Users/mpeveler/Work/Github/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php:1114
/Users/mpeveler/Work/Github/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php:449
/Users/mpeveler/Work/Github/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php:373
/Users/mpeveler/Work/Github/phinx/tests/Phinx/Migration/ManagerTest.php:5879
```

I'm assuming that it's desired that this gets fixed to use Postgres properly? Should the test be left in place to also test a full MySQL migration as well?

I can fix it to whatever is desired based on the answer of the above two questions.

**Comment by lorenzo** [comment]
I wonder if it is just the name that is wrong?

**Comment by MasterOdin** [comment]
Given the rest of https://github.com/cakephp/phinx/commit/589d665440a0ccb389af5972f5103dc82092bbf1 where it was added, it looks like it was intended for PostgreSQL.
