### ISSUE TITLE
Allow creation of MSSQL identity columns with user specified seed and increment

### ISSUE THREAD

**Issue by JRDuncan** [cakephp/phinx#1576]
Example:

        public function change()
        {
                $table = $this->table('product', ['id' => false, 'primary_key' => ['id'], ['name' => 'aaaaa_product_pk']]);
                $table->addColumn('id', 'integer', ['identity' => true, 'seed' => 1, 'increment' => 10, ])
                        ->addColumn('name', 'string', ['default' => null,'limit' => 50,'null' => false,])
                        ->addColumn('is_active', Literal::from('tinyint'), ['default' => 1,'limit' => 11,'null' => false, ])
                        ->addColumn('created_on', 'datetime', ['default' => 'CURRENT_TIMESTAMP','null' => false])
                        ->addColumn('modified_on', 'datetime', ['null' => true])
                        ->addIndex(['name'], ['unique' => true,'name' => 'uc_product_name'])
                        ->create();

        }

**Comment by JRDuncan** [comment]
Hi @lorenzo,
Can I be assigned this one. I already done the fix in my local repo

**Comment by lorenzo** [comment]
Sure, just send a pull request
