### ISSUE TITLE
issue with creating tinyint(2)

### ISSUE THREAD

**Issue by SignpostMarv** [cakephp/phinx#1578]
#426 added support for specifying `tinyint(3)` (re: #249), booleans come out as `tinyint(1)` (re: #764), but I can't use phinx to create `tinyint(2)`.

Whilst this issue is *technically* a duplicate of #1037, that issue was closed by the author without indicating if the underlying issue was actually resolved.

Ideally I want to be able to specifically say `['limit' => 2]` means `tinyint(2)`, ***not*** `int(2)`, or I'd like to be able to specify a min/max range than have phinx automagically use the most appropriate field type & signed/unsigned- i.e. both values in a `min`/`max` pair being greater than or equal to zero would create an unsigned number field, whilst either value of a `min`/`max` pair would create a signed number field.

**Comment by dereuromark** [comment]
Shouldnt tinyinteger with limit 2 work?

**Comment by SignpostMarv** [comment]
in pure terms of syntax, yes.

I do however forget the exact use-case I had at at the time of writing.

If the pure syntax issue doesn't necessitate a fix, shall we just close this until I stumble across the particular use-case again?

**Comment by dereuromark** [comment]
Sure, let us how to reproduce.
