### ISSUE TITLE
Migrations not running

### ISSUE THREAD

**Issue by paulmiller3000** [cakephp/phinx#1580]
New phinx user. Hoping someone can help.

I've installed with composer in Windows. I created a migration class, but migrations don't run and none are listed under pending.

```
$ vendor/bin/phinx migrate -e development
Phinx by CakePHP - https://phinx.org. 0.10.8

using config file .\phinx.php
using config parser php
using migration paths
 - C:\xampp\htdocs\pixapad\db\migrations
using environment development
using adapter mysql
using database pixapad_local
```

At that point it just hangs. I have to use Ctrl+Break to exit.

No migrations show up with the status check:

```
$ vendor/bin/phinx status -e development
Phinx by CakePHP - https://phinx.org. 0.10.8

using config file .\phinx.php
using config parser php
using migration paths
 - C:\xampp\htdocs\pixapad\db\migrations
using environment development
ordering by creation time

 Status  [Migration ID]  Started              Finished             Migration Name
----------------------------------------------------------------------------------

```

Again, it hangs. I actually have to kill my console to exit.

Here's my migration script (/db/migrations/20190806193906_page_table.php):

```class PageTable extends AbstractMigration
{
    public function change()
    {
        $tableName = 'page';

        $exists = $this->hasTable($tableName);
        if (!$exists) {
        // create the table
            $table = $this->table($tableName);
            $table->addColumn('PageHtml', 'text')
                  ->addColumn('DateCreated', 'datetime')
                  ->addColumn('name', 'varchar', ['limit' => 100])
                  ->create();
        }
    }

    /**
     * Migrate Up.
     */
    public function up()
    {

    }
}
```

On a whim, I tried `vendor/bin/phinx create PageTable` but Phinx advised the migration class already exists. I'm not sure what to check next.

Suggestions?

**Comment by JRDuncan** [comment]
@paulmiller3000 Was the phinxlog table created in your database "pixapad_local". If not can you make sure credentials are valid

**Comment by JRDuncan** [comment]
@paulmiller3000 
also
 ->addColumn('name', 'varchar', ['limit' => 100])
should be 
->addColumn('name', 'string', ['limit' => 100])

**Comment by paulmiller3000** [comment]
> @paulmiller3000 Was the phinxlog table created in your database "pixapad_local". If not can you make sure credentials are valid

Well, chalk another one up to user error! Credentials were right, but your suggestion prompted me to check my other entries. Turns out I'd set my database port to 81 instead of the correct database port of 3306.

Oops. Fixing that corrected my issue.

I also updated the `addColumn` statement per your guidance.

Thank you!
