### ISSUE TITLE
Incorrect removing/changing columns for SQLite

### ISSUE THREAD

**Issue by gibat** [cakephp/phinx#1583]
**Impact**:
Database can be corrupted

**Reproduced with** SQLite library 3.28.0 (PHP 7.1.31)

**Steps to reproduce**:
1. Create migration:
```
$tableA = 'tableA';
$tableB = 'tableB';

$this->table($tableA, ['id' => false, 'primary_key' => ['id']])
    ->addColumn('id', 'integer', ['identity' => true])
    ->addColumn('columnToRemove', 'integer')
    ->create();

$this->table($tableB, ['id' => false, 'primary_key' => ['id']])
    ->addColumn('id', 'integer', ['identity' => true])
    ->addColumn('tableA_id', 'integer')
    ->addForeignKey('tableA_id', $tableA, 'id', [
        'delete' => 'CASCADE',
        'update' => 'NO_ACTION',
    ])
    ->create();

$this->table($tableA)
    ->removeColumn('columnToRemove')
    ->save();
```
2. Run `phinx migrate -vv`

**Actual table structure**:
```
create table tableB
(
  id INTEGER not null primary key autoincrement,
  tableA_id INTEGER references tmp_tableA (id) on delete cascade
);
```

**Expected table structure**: (pay attention to the name of reference table)
```
create table tableB
(
  id INTEGER not null primary key autoincrement,
  tableA_id INTEGER references tableA (id) on delete cascade
);
```

**Additional information**:
I've found following lines in SQLite changelog:
> 2018-09-15 (3.25.0) Fix table rename feature so that it also updates references to the renamed table in triggers and views.
> 2018-12-01 (3.26.0) Added the PRAGMA legacy_alter_table command, which if enabled causes the ALTER TABLE command to behave like older version of SQLite (prior to version 3.25.0) for compatibility.

Also you can read that gist: https://gist.github.com/kpcyrd/1805a9f5c87182dfe40bf4bc2b68c54e

**Possible way to fix**:
a) Existed tableA shouldn't be renamed to tmp_tableA, instead of this need to firstly create tmp_tableA, copy all data, remove tableA and rename tmp_tableA to tableA. This must work correctly
b) Set legacy_alter_table=ON while performing "such" migrations

**Comment by lorenzo** [comment]
Would you like to submit a fix for this?

**Comment by baturin** [comment]
Any chances to get that fixed? The issue blocks usage of the library on PHP 7.1.32 with SQLite.

**Comment by Jeckerson** [comment]
Same problem with SQLite...
