### ISSUE TITLE
Update tables in more than one database

### ISSUE THREAD

**Issue by omzy** [cakephp/phinx#1584]
Hi all,

How can I create a migration that updates tables in more than one database (within the same environment)? The only way I can see this working is if you can specify the database name within the migration code - but I have not come across any examples of this.

Would it be a case of creating separate config files for each database and running them individually? Ideally I want this to be an operation that I can run in one command, i.e. `phinx migrate`.

I have seen the issue https://github.com/cakephp/phinx/issues/180 but this is more about creating migrations for databases in multiple environments.

**Comment by rquadling** [comment]
You _should_ be able to use the normal `database.table.column` format.

This assumes that both databases are accessible via the same connection.

If you are using Microsoft SQL Server, and have shared servers setup, then you _should_ be able to use `server.database.table.column`. From what I can tell, mysql cannot run queries across separated mysql instances in the same way.

**Comment by omzy83** [comment]
Hi @rquadling, thanks for you reply.

Can you give me an example of how that would be utilised in a migration? I am using a MySQL database.

My existing migration code is like this:

    public function up()
    {
        $table = $this->table('users');
        $table->addColumn('city', 'string')
              ->save();
    }

**Comment by garas** [comment]
Try `$this->table('database.users')`

**Comment by omzy83** [comment]
@garas that worked, but it updates the log table in the database that is specified in the config file.

I guess separate config files is the best solution.

**Comment by rquadling** [comment]
It is entirely possible to have a database credential set that can access multiple databases and/or schemas (depending upon the technology), with the phinx config also including which database/schema holds the phinxlog store.

It is upto each migration to correctly interact with the right database/schema tables.
It is upto the DB admin to make sure that the credentials used have the appropriate permissions.

**Comment by rquadling** [comment]
> @garas that worked, but it updates the log table in the database that is specified in the config file.
> 
> I guess separate config files is the best solution.

If you have 3 databases (Client1, Client2, and Client3) in 2 environments (Development and Production), then you could have a config file per database with 2 environments, OR a config file per environment with 3 databases.

The effort is probably the same. It is just a case of supplying a config and an environment, or an environment and a config.

**Comment by dereuromark** [comment]
PR welcome.
