### ISSUE TITLE
 Symfony\Component\Console\Exception\LogicException

### ISSUE THREAD

**Issue by cesar1983** [cakephp/phinx#1585]
Hello guys

I just started to get this exception while running Phinx :

PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /var/lib/jenkins/workspace/hqbeds-dev-php7/vendor/symfony/console/Command/Command.php:453
Stack trace:
#0 /var/lib/jenkins/workspace/hqbeds-dev-php7/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php(47): Symfony\Component\Console\Command\Command->getName()
#1 /var/lib/jenkins/workspace/hqbeds-dev-php7/vendor/symfony/console/Command/Command.php(77): Phinx\Console\Command\Init->configure()
#2 /var/lib/jenkins/workspace/hqbeds-dev-php7/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(60): Symfony\Component\Console\Command\Command->__construct()
#3 /var/lib/jenkins/workspace/hqbeds-dev-php7/vendor/robmorgan/phinx/app/phinx.php(36): Phinx\Console\PhinxApplication->__construct()
#4 /var/lib/jenkins/workspace/hqbeds-dev-php7/vendor/robmorgan/phinx/bin/phinx(27): require('/var/lib/jenkin...')
#5 {main}
  thrown in /var/lib/jenkins/workspace/hqbeds-dev-php7/vendor/symfony/console/Command/Command.php on line 453

I was using version 0.10.6 when I got the error. I tried upgrading to 0.10.8 , but still the same problem.

My php version is PHP 7.3.7

It was running okay  3 hours ago...

Can anyone help me?

**Comment by Xakki** [comment]
Here broke \Symfony\Component\Console\Command\Command::getName
https://github.com/symfony/console/commit/4510f04e70344d70952566e4262a0b11df39cb10#diff-25a75e093c4a0d5564a36cebbb1384b3R461

**Comment by aslabs** [comment]
I got crazy trying to figure out what is the problem. It's a relief to see that it's not just in my head.
What should we do then? downgrade phinx? 
Thanks

**Comment by nicolas-grekas** [comment]
Is there a reasonable fix on cake's side?
Can the method be made to return a name?

**Comment by leaderpol** [comment]
You have to set ne name of the command in PhinxApplication.php:59
$this->addCommands([
            new Command\Init('init'),
            new Command\Create('create'),
            new Command\Migrate('migrate'),
            new Command\Rollback('rollback'),
            new Command\Status('status'),
            new Command\Breakpoint('breakpoint'),
            new Command\Test('test'),
            new Command\SeedCreate('seedcreate'),
            new Command\SeedRun('seedrun'),
        ]);

**Comment by gnugat** [comment]
Looks like Symfony's Command::getName() was never intended to return `null`, but it worked in Phinx because types were not enforced (they were only declared using PHPdocs). It is my understanding that for its version 5 Symfony intends to enforce its type returns.

So preparing a fix for Phinx seems to me to be the best approach, as it immediately solves the issue and prepares for the future. I've created a PR for it, please have a look a leave a comment if you see it fit.

**Comment by dereuromark** [comment]
Your PR https://github.com/cakephp/phinx/pull/1588 indeed seems quite future proof
Nice one!

**Comment by dream-mo** [comment]
> Force the version of symphony/console in your composer.json untill they fix it with
> "symfony/console": "v3.4.27"
> I did that here...

good idea
