### ISSUE TITLE
Fatal error due to symfony change

### ISSUE THREAD

**Issue by danb1974** [cakephp/phinx#1589]
Because of getName() checking if the application name is not set, the setName(getName() ?: 'init') code does no longer work, but crash with an exception:

PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name.

**Comment by dereuromark** [comment]
Resolved with https://github.com/cakephp/phinx/pull/1588
