### ISSUE TITLE
PHP Fatal error - after update  Symfony

### ISSUE THREAD

**Issue by aleksey005** [cakephp/phinx#1593]
`
Step 16/26 : RUN vendor/bin/phinx migrate
 ---> Running in 293a0585ef05
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /app/vendor/symfony/console/Command/Command.php:453
Stack trace:
#0 /app/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php(47): Symfony\Component\Console\Command\Command->getName()
#1 /app/vendor/symfony/console/Command/Command.php(77): Phinx\Console\Command\Init->configure()
#2 /app/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(60): Symfony\Component\Console\Command\Command->__construct()
#3 /app/vendor/robmorgan/phinx/app/phinx.php(36): Phinx\Console\PhinxApplication->__construct()
#4 /app/vendor/robmorgan/phinx/bin/phinx(27): require('/app/vendor/rob...')
#5 {main}
  thrown in /app/vendor/symfony/console/Command/Command.php on line 453
The command '/bin/sh -c vendor/bin/phinx migrate' returned a non-zero code: 255
time="2019-08-27T14:01:10Z" level=fatal msg="exit status 255"
`

**Comment by dereuromark** [comment]
Fixed by https://github.com/cakephp/phinx/pull/1588
