### ISSUE TITLE
Not working with Symfony 4.3.4 

### ISSUE THREAD

**Issue by tonydspaniard** [cakephp/phinx#1595]
Current changes on Symfony console `Command::getName()` (https://github.com/symfony/console/commit/6b101586a5938f1a5958ef0d6ca598755b6d6ea8#diff-25a75e093c4a0d5564a36cebbb1384b3R342) makes the `configure()` method of each command to throw an error. 

```
$this->setName($this->getName() ?: 'create')
// ... 
```

**Comment by dereuromark** [comment]
Please see the last 5 issues.

**Comment by dereuromark** [comment]
Resolved in master ( https://github.com/cakephp/phinx/pull/1588 ).
Please use dev-master until the release can be tagged.
