### ISSUE TITLE
symfony/console v4.3.4 breaks Phinx

### ISSUE THREAD

**Issue by Jacco-V** [cakephp/phinx#1599]
The recent `symfony/console` update to version `v4.3.4` (Aug 26, 2019, 10:26 AM GMT+2) breaks Phinx with error:

```
Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /var/www/project/vendor/symfony/console/Command/Command.php on line 453

Call Stack:
    0.0002     390480   1. {main}() /var/www/project/vendor/robmorgan/phinx/bin/phinx:0
    0.0004     392128   2. require('/var/www/project/vendor/robmorgan/phinx/app/phinx.php') /var/www/project/vendor/robmorgan/phinx/bin/phinx:27
    0.0212    1646192   3. Phinx\Console\PhinxApplication->__construct() /var/www/project/vendor/robmorgan/phinx/app/phinx.php:36
    0.0231    1760632   4. Phinx\Console\Command\Init->__construct() /var/www/project/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php:60
    0.0240    1889792   5. Phinx\Console\Command\Init->configure() /var/www/project/vendor/symfony/console/Command/Command.php:77
    0.0240    1889792   6. Phinx\Console\Command\Init->getName() /var/www/project/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php:47
```

This is caused by the `$this->setName` call in [Phinx/Console/Command/Init.php:47](https://github.com/cakephp/phinx/blob/v0.10.8/src/Phinx/Console/Command/Init.php#L47).

From the looks of it, this issue is fixed in [`v0.11.0`](https://github.com/cakephp/phinx/blob/v0.11.0/src/Phinx/Console/Command/Init.php#L48), but this version has [not been published on packagist](https://packagist.org/packages/robmorgan/phinx) yet?

It would be highly appreciated if somebody could push the `v0.11.0` version to packagist.

Cheers

**Comment by dereuromark** [comment]
Refs also https://github.com/cakephp/phinx/pull/1598

We are soon fixing this. Until then you can use dev-master as branch or not using latest symfony/console patch.

**Comment by dereuromark** [comment]
Release patch is out. Also shows up fine now: https://packagist.org/packages/robmorgan/phinx

**Comment by doganoo** [comment]
just googled the error message and seen that there is a patch published 7 minutes ago. Thank you guys!

@dereuromark

**Comment by paulmiller3000** [comment]
> just googled the error message and seen that there is a patch published 7 minutes ago. Thank you guys!
> 
> @dereuromark

Same here. Thanks!
