### ISSUE TITLE
Do not print out Phinx header info if using --format json or --pipe

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1601]
Opening this as a way of garnering whether this is the appropriate way to approach this.

The first method `--format json` seems like less likely to cause contraversy. Essentially, it's in my opinion that anyone using `--format json` for a command probably does not want to see the header information of the command (for example:
```
Phinx by CakePHP - https://phinx.org. 0.11.1

using config file ./phinx.yml
using config parser yaml
using migration paths
 - /Users/mpeveler/Work/Github/phinx/db/migrations
using seed paths
warning no environment specified, defaulting to: production
using format json
ordering by creation time
```

but just the produced JSON object from the command so that it can be used in a downstream application/piped into something immediately without having to take weird intermediary steps that most people wouldn't expect to take compared to tools like composer.

However, some people would like to see the text output of the command, but not the header (such as #1568 with `--dry-run`). For this, I propose adding a new global flag `--pipe` (maybe not the best name) that when used, would silence the above header information and only output the information from the command. For `phinx status`, it would be look something like:
```
$ phinx status --pipe
 Status  [Migration ID]  Started              Finished             Migration Name
----------------------------------------------------------------------------------
     up  20190828175258  2019-08-28 17:55:41  2019-08-28 17:55:41  TestMigration
```

I'm making this issue with both methods as both should be able to utilize the same mechanism to silence the header information while outputting the main results of a command.

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/phinx/issues/962

For me your PR https://github.com/cakephp/phinx/pull/1600 is sufficient here. :)
