### ISSUE TITLE
Error when execute phinx bin

### ISSUE THREAD

**Issue by SylvanoTombo** [cakephp/phinx#1604]
I have this error when execute phinx bin.
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /home/sylvanito/Labs/tuto-blog/vendor/symfony/console/Command/Command.php:453
Stack trace:
#0 /home/sylvanito/Labs/tuto-blog/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php(47): Symfony\Component\Console\Command\Command->getName()
#1 /home/sylvanito/Labs/tuto-blog/vendor/symfony/console/Command/Command.php(77): Phinx\Console\Command\Init->configure()
#2 /home/sylvanito/Labs/tuto-blog/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(60): Symfony\Component\Console\Command\Command->__construct()
#3 /home/sylvanito/Labs/tuto-blog/vendor/robmorgan/phinx/app/phinx.php(36): Phinx\Console\PhinxApplication->__construct()
#4 /home/sylvanito/Labs/tuto-blog/vendor/robmorgan/phinx/bin/phinx(27): require('/home/sylvanito...')
#5 {main}
  thrown in /home/sylvanito/Labs/tuto-blog/vendor/symfony/console/Command/Command.php on line 453
 I DONT KNOW HOW TO REPRODUCE THE ISSUE.

**Comment by dereuromark** [comment]
Use fixed version https://github.com/cakephp/phinx/releases/tag/0.11.1

**Comment by SylvanoTombo** [comment]
> Use fixed version https://github.com/cakephp/phinx/releases/tag/0.11.1

Thanks.
