### ISSUE TITLE
Update default branch on codecov to master

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1609]
Something I noticed today when I went to show someone codecov and using this repo as the example. Going to https://codecov.io/gh/cakephp/phinx shows an error screen showing that there's no data available yet for 0.5.x-dev. Should update the settings for the repo to use `master` as the default branch to show on the dashboard.

**Comment by garas** [comment]
I've updated the settings to use `master` branch on the dashboard.
