### ISSUE TITLE
Create phinx migration files from existing database tables

### ISSUE THREAD

**Issue by faizalmansor** [cakephp/phinx#1610]
Is there a plugin for this? If not, how would I go about making one? Any ideas would be greatly appreciated.

**Comment by MasterOdin** [comment]
For MySQL 5.7+, there exists https://github.com/odan/phinx-migrations-generator. Not sure if there's anything for the other database types.

**Comment by dereuromark** [comment]
Duplicate of https://github.com/cakephp/phinx/issues/820
