### ISSUE TITLE
Phinx command defined in "Phinx\Console\Command\Init" cannot have an empty name.

### ISSUE THREAD

**Issue by fajarhide** [cakephp/phinx#1613]
Hi, 

I found an issue in phinx depedency on the symfony version like this:

`
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /current/vendor/symfony/console/Command/Command.php:453
Stack trace:
#0 /current/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php(47): Symfony\Component\Console\Command\Command->getName()
#1 /current/vendor/symfony/console/Command/Command.php(77): Phinx\Console\Command\Init->configure()
#2 /dcurrent/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(60): Symfony\Component\Console\Command\Command->__construct()
#3 /dcurrent/vendor/robmorgan/phinx/app/phinx.php(36): Phinx\Console\PhinxApplication->__construct()
#4 /current/vendor/robmorgan/phinx/bin/phinx(27): require('/current')
#5 {main}
  thrown in /current/vendor/symfony/console/Command/Command.php on line 453
`

I use phinx on composer.json :
`
"robmorgan/phinx": "^0.10.7",
`

i found this issue cause `phinx `auto update depedency package `symfony `latest version

**Comment by MasterOdin** [comment]
This has been previously reported (#1585) and fixed by upgrading to `0.11.1`.

**Comment by fajarhide** [comment]
Oke, thanks
