### ISSUE TITLE
Standarize exit codes to constants across console commands

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1623]
From discussion in #1622.

Right now, all console commands (with the slight exception of error codes for status) use magic integers for returns of exit codes. Phinx should define constants under a class to have a central place for where these constants are defined. My vote would be in the [`AbstractCommand`](https://github.com/cakephp/phinx/blob/master/src/Phinx/Console/Command/AbstractCommand.php) base class, and would include moving the two existing commands in the [`Manager`](https://github.com/cakephp/phinx/blob/master/src/Phinx/Migration/Manager.php) to there as well:
https://github.com/cakephp/phinx/blob/6b1c0edb507bb5b3ffb5056015a75b32052b6489/src/Phinx/Migration/Manager.php#L76-L84

Finally, there should be a consensus on when a command should throw an exception and when to print `<error>` and return an exit code and it seems somewhat inconsistent at this point with some potentially only throwing exceptions (`create`, `seed:create`), some doing a mix (`rollback`) and some only doing error codes(`migrate`).

**Comment by dereuromark** [comment]
Do you want to make a PR here?
