### ISSUE TITLE
changeColumn() to unsigned doesn't work with SmallInt

### ISSUE THREAD

**Issue by SilkAndSlug** [cakephp/phinx#1625]
I'm using the `changeColumn` method on `Table` to change a bunch of columns to unsigned=false. This works fine with Integer-type columns, but has no effect on SmallInt-typed columns.

Example code:

    up() {
        $list = $this->get_list_of_relevant_tables();
        foreach ($list as $name1) {
            $table = $this->table($name1);
            $columns = $this->get_list_of_relevant_columns($name1);
            foreach ($columns AS $name2) {
                $column = $table->getColumn($name2);
                $type = $column->getType();
                $table->changeColumn($name2, $type, [ 'unsigned' => false ]);
            }
            $table->save();
        }
    }

I've added debugging to line 166 in Phinx\Db\Adapter\PdoAdapter.php :

    echo "sql $sql", PHP_EOL;

Running the migration gives this:

    sql ALTER TABLE `departments_to_permissions` CHANGE `permission_id` `permission_id` INT(11) unsigned NOT NULL
    sql ALTER TABLE `group_types` CHANGE `group_type_id` `group_type_id` SMALLINT(6) NOT NULL
    sql ALTER TABLE `groups` CHANGE `group_type_id` `group_type_id` SMALLINT(6) NOT NULL
    sql ALTER TABLE `permissions` CHANGE `id` `id` INT(11) unsigned NOT NULL
    ....

Note that the INT(11) columns have `unsigned` in the SQL, and the SMALLINT(6) columns don't. The smallint columns *tend* to be references to other tables, i.e. indexed but not unique or primary -- but aren't always

Workaround is to write your own SQL, and pass it to `$this->execute()`

**Comment by garas** [comment]
Probably only this list should be updated

https://github.com/cakephp/phinx/blob/4dfbaaa0a50055a1b4edaa542bac882be7b40e3e/src/Phinx/Db/Adapter/MysqlAdapter.php#L47-L54
