### ISSUE TITLE
run Phinx via custom cli tool?

### ISSUE THREAD

**Issue by ltdev22** [cakephp/phinx#1628]
Would appreciate some feedback if possible. I'm having a php app in which I'm using a custom cli tool like Artisan for generating files etc which is based on Symfony's Console. So I'm having a folder of commands like this

```php
<?php

namespace App\Console\Commands;
use App\Console\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class HelloWorldCommand extends Command
{

    protected $command = 'say:hello';

    protected $description = 'Say the classic "hello world!"';

    public function handle(InputInterface $input, OutputInterface$output)
    {
            $this->info('Hello World !');
    }

    protected function arguments()
    {
        return [
            ['name', InputArgument::REQUIRED, 'Enter your name.'],
        ];
    }

    protected function options()
    {
        return [
            ['somehthing', 'r', InputOption::VALUE_OPTIONAL, 'Do something.', 1],
        ];
    }
}
```

I'm also using Phinx for creating and running migrations and seeds. So whenever I want to run a phinx command I do something like `vendor/bin/phinx create/migrate/rollback etc`, which works fine. However I'm looking for a way to run the phinx commands via the cli tool.

Is there a better way of doing this instead of doing something like this `exec('vendor/bin/phinx migrate/rollback etc');` in my handle method? I think this looks a bit hacky

**Comment by sabl0r** [comment]
I implemented this some time ago: https://github.com/cakephp/phinx/issues/1365#issuecomment-396245197

**Comment by dereuromark** [comment]
Maybe someone can put this into docs as showcase? Then it might be found more easily.
