### ISSUE TITLE
Changing a column's limit changes other properties of the column unexpectedly

### ISSUE THREAD

**Issue by worsethannetbeans** [cakephp/phinx#1640]
Suppose I have an existing database with a table column like:

```
`somecolumn` varchar(50) DEFAULT NULL,
```

If I change the column length with a raw MySQL query e.g.

```
ALTER TABLE `sometable`
MODIFY `somecolumn` VARCHAR(100)
```

This gives me:

```
`somecolumn` varchar(100) DEFAULT NULL,
```

Which is what I would expect viewing the "create table" syntax of the modified table. Now I will do the same with Phinx using:

```
$table = $this->table('sometable');
$table->changeColumn('somecolumn', 'string', ['limit' => 128])
      ->save();
```

This results in:

```
  `somecolumn` varchar(128) NOT NULL,
```

Instead of modifying _just_ the property of the column I expected, it set it to `NOT NULL` as well. Perhaps it picked up some default from Phinx? To fix it I had to be very specific in my script i.e.

```
$table = $this->table('sometable');
$table->changeColumn('somecolumn', 'string', ['limit' => 128, 'null' => true])
      ->save();
```

Imagine if I don't notice the `NOT NULL` part when testing. I have a production database with null values in that column as it is optional... My migration script is working fine locally in development as that column is fully filled with testing data. It also works fine in testing in the CI environment as it has similar testing data. Then I try deploy it to production. The migration script unexpectedly fails due to some values being null in the column. Maybe the CI environment doesn't detect the migration error, then the related code deployed with this change fails as well because the form is now rejecting saving legitimate records (previously it was an optional field).

This is a pretty good footgun that should be documented somewhere in the docs in bold red text. Or ideally the migration script should only modify the column properties that are specifically specified to be modified i.e. in this case, the limit.

**Comment by dereuromark** [comment]
PR to docs welcome.
