### ISSUE TITLE
Support for Symfony 5.0

### ISSUE THREAD

**Issue by dan-coman** [cakephp/phinx#1645]
It would be nice to have support for symfony 5.0 for packages:
- symfony/console
- symfony/config
- symfony/yaml

**Comment by dereuromark** [comment]
What is still missing after https://github.com/cakephp/phinx/pull/1644 ?

**Comment by dan-coman** [comment]
I think it needs a new tag.

**Comment by dereuromark** [comment]
That will sure come soon.

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/releases/tag/0.11.2

**Comment by dan-coman** [comment]
Still getting the 0.11.1 version. I think the tag is not pushed.
Thanks

**Comment by dan-coman** [comment]
I think you should update in composer also:

 Problem 1
    - The requested package robmorgan/phinx 0.11.2 exists as robmorgan/phinx[0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.5, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.x-dev, 0.9.2, dev-0.6.x-dev, dev-0.7.x-dev, dev-JayPHP-patch-1, dev-i413-fluent-phinx, dev-introduce-deprecation-of-up-and-down, dev-master, dev-phing-phinx-task, dev-repeatable_migrations, dev-revert-822-patch-3, dev-scrutinizer-patch-2, v0.1.2, v0.1.3, v0.1.4, v0.1.5, v0.1.6, v0.1.7, v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.2.8, v0.2.9, v0.3.0, v0.3.1, v0.3.2, v0.3.3, v0.3.4, v0.3.5, v0.3.6, v0.3.7, v0.3.8, v0.4.0, v0.4.1, v0.4.2, v0.4.2.1, v0.4.3, v0.4.4, v0.4.5, v0.4.6, v0.5.0, v0.5.1, v0.5.2, v0.5.3, v0.5.4, v0.5.5, v0.6.0, v0.6.1, v0.6.2, v0.6.3, v0.6.4, v0.6.5, v0.6.6, v0.7.0, v0.7.1, v0.7.2, v0.8.0, v0.8.1, v0.9.0, v0.9.1] but these are rejected by your constraint.

Thanks

**Comment by dereuromark** [comment]
@markstory Any way we can fix this for now and the future?
