### ISSUE TITLE
Publish a new release with support for Symfony 5

### ISSUE THREAD

**Issue by khayyam90** [cakephp/phinx#1646]
Hi,
Recently migrated Symfony projects cannot use phinx anymore due to the official release that still don't support the v5 for the symfony components needed by phinx. 
The source code on github is already up to date, could it be possible to publish a new release on packagist with this new SF5 support ?
Thanks a lot

**Comment by dereuromark** [comment]
You can use "dev-master as x.y.z." in the meantime.

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/releases/tag/0.11.2
