### ISSUE TITLE
Docs site isn't updated

### ISSUE THREAD

**Issue by berarma** [cakephp/phinx#1648]
The site http://docs.phinx.org is getting out of date. Did something break or is it updated manually?

**Comment by dereuromark** [comment]
Shouldnt this redirect to the new docs then? @markstory

**Comment by markstory** [comment]
I don't know how or where the hosting for docs.phinx.org is setup unfortunately.

**Comment by dereuromark** [comment]
Fixed now

**Comment by MasterOdin** [comment]
https://docs.phinx.com is still way out of date. It's being built through the readthedocs.org platform and it looks like it was last synced about a year ago: https://readthedocs.org/projects/phinx/builds/.

If the intention is to have everyone use https://book.cakephp.org/3/en/phinx.html, it might be worth deleting it from RTD so that it stops being a top result on google.

**Comment by dereuromark** [comment]
@robmorgan ping

**Comment by robmorgan** [comment]
Hmmmm I think I'll do two things.

1. Point the Phinx marketing site (https://phinx.org), directly to https://book.cakephp.org/3/en/phinx.html
2. Setup a 301 from docs.phinx.org directly to https://book.cakephp.org/3/en/phinx.html

Sound good?

**Comment by robmorgan** [comment]
Just thinking out loud - the only problem with that approach is we'd need to remember to bump the CakePHP Version number in the URL for every major release.

**Comment by dereuromark** [comment]
Maybe we could also point it to a entry point that auto redirects to latest major

   https://book.cakephp.org/en/phinx.html

e.g. would then show or find+redirect the latest
@markstory that is doable?

That way it is always true.

**Comment by markstory** [comment]
We can make https://book.cakephp.org/phinx always resolve to the latest english docs.

**Comment by dereuromark** [comment]
Cool, once that is done, we can ping rob to set the link.

**Comment by robmorgan** [comment]
For now I've started redirecting http://docs.phinx.org/ to https://book.cakephp.org/4/en/phinx.html. I'll shutdown readthedocs for SEO purposes at some point.

**Comment by markstory** [comment]
@robmorgan If you have a chance could you change the redirect to https://book.cakephp.org/phinx/ that URL will do one additional redirect and end up at the current release docs going forward.

**Comment by robmorgan** [comment]
@markstory I've updated the link now:

*://docs.phinx.org -> https://book.cakephp.org/phinx/

**Comment by igorsantos07** [comment]
Just wanted to point out to @robmorgan that https://phinx.readthedocs.io/ is still stealing the scene on some searches

PS.: should the docs contain all options, or just leave that to the (confusing) `help` commands? If so, I can try writing a PR with the missing stuff, like `--fake`.

![image](https://user-images.githubusercontent.com/532299/101235084-159bca80-36a4-11eb-8936-492561cacfb3.png)

**Comment by robmorgan** [comment]
@igorsantos07 chiming in here 6 months later, I've now finally removed the Phinx docs from readthedocs.io so the [search results](https://phinx.readthedocs.io/en/latest/migrations.html) will start returning a 404 and gradually be removed from the index.

**Comment by igorsantos07** [comment]
Awesome, man! Great you got the time for that!
