### ISSUE TITLE
Composer version mismatch

### ISSUE THREAD

**Issue by flavioheleno** [cakephp/phinx#1650]
Hi folks, first and foremost, thanks for such a brilliant package! It has helped me a lot through the years <3

This issue is about the latest release, here at GitHub it is tagged as [v0.11.2](https://github.com/cakephp/phinx/releases/tag/0.11.2), but at Packagist, it is tagged as [v0.11.1](https://packagist.org/packages/robmorgan/phinx#0.11.1).

As you may know, that keeps users from updating the package.

Thank you :-)

**Comment by flavioheleno** [comment]
I tried to do a PR for fixing it, but apparently I messed up with the right base to merge into.

With some guidance I can put it back on :-)

**Comment by visavi** [comment]
they just broke the synchronization or disconnected  github -> packagist

**Comment by dereuromark** [comment]
Turns out the nonsense version in there is responsible: https://github.com/cakephp/phinx/pull/1653
Time to get rid of it for good, an anti pattern to have it.

**Comment by dereuromark** [comment]
I will merge and release a new tag then.

**Comment by dereuromark** [comment]
https://packagist.org/packages/robmorgan/phinx now has the new patch release.
Thanks for the heads up!
