### ISSUE TITLE
Removing Version from composer.json breaks CakePHP Migrations Plugin

### ISSUE THREAD

**Issue by kwentworth** [cakephp/phinx#1655]
This commit: https://github.com/cakephp/phinx/commit/1d72681b214e058f5d1a3ecce12762344c676427

Breaks logic to determine phinx version:
https://github.com/cakephp/migrations/commit/3f0a10534b64edefa86cc83abdd3e1e6bf88586e#diff-abae0260b2ff59fb81f37864b18fe5a1

Now migrations plugin not working on cakephp 3.8.9 after composer update

**Comment by dereuromark** [comment]
This is fixed in master.

**Comment by dereuromark** [comment]
https://github.com/cakephp/migrations/releases/tag/2.4.1
