### ISSUE TITLE
Deprecation of implode usage with PHP 7.4

### ISSUE THREAD

**Issue by diegosardina** [cakephp/phinx#1656]
bin/cake migrations create gives:

`2019-12-15 10:50:01 Notice: Deprecated (8192): implode(): Passing glue string after array is deprecated. Swap the parameters in [/home/diego/public_html/cakephp/vendor/robmorgan/phinx/src/Phinx/Util/Util.php, line 111]`

This was already fixed in master with #1606 but wasn't merged in 0.11.x branch.

**Comment by dereuromark** [comment]
Master is 0.11
What branch are you referring to? Pretty sure that one is not supposed to be used.

**Comment by dereuromark** [comment]
I made a 0.next and merged master into it: https://github.com/cakephp/phinx/compare/0.next?expand=1
Please move away from using the 0.11.x as this is misleading and will be removed in the near future.

**Comment by diegosardina** [comment]
Just upgraded a test project to CakePHP 4.0-RC2 with PHP 7.4.

Phinx hasn't been installed manually but via dependency of cakephp/migrations.

The phinx version is:
            "name": "robmorgan/phinx",
            "version": "0.11.x-dev",

**Comment by dereuromark** [comment]
Thx, we then need to fix migrations, too.

**Comment by dereuromark** [comment]
https://github.com/cakephp/migrations/pull/415
