### ISSUE TITLE
Index column sort order

### ISSUE THREAD

**Issue by JRDuncan** [cakephp/phinx#1661]
Phinx does not allow you to specify the sort order on Index columns.

    public function change()
    {
        $table = $this->table('users');
        $table->addColumn('email', 'string')
              ->addColumn('username','string')
              ->addIndex(['email','username'], ['order' => ['email' => 'DESC', 'username' => 'ASC']])
              ->create();
    }

**Comment by dereuromark** [comment]
PR welcome

**Comment by nohaycubetto** [comment]
Second this.
