### ISSUE TITLE
i cant migrate

### ISSUE THREAD

**Issue by room3622** [cakephp/phinx#1685]
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-log ORDER BY version ASC' at line 1 in /home/the-game.ddns.net/public_html/App/System/Composer/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:212

**Comment by MasterOdin** [comment]
What is the value of `default_migration_table` in your configuration file?
