### ISSUE TITLE
Better @return tag for query method

### ISSUE THREAD

**Issue by miroslav-demcak-cz** [cakephp/phinx#1690]
**Problem description (by example)**

The method fetchAll is not found by IDE in the following case.

`$this->query($sql)->fetchAll();`

**Suggested solution**

The [@return tag at the query method phpDoc](https://github.com/cakephp/phinx/blob/master/src/Phinx/Migration/MigrationInterface.php#L145) should include:

- all adapter's query return types or
- mixed type or
- (nothing (not preffered))

instead of array.

I would also suggest following information as part of the query phpDoc:

_To improve correct IDE auto-completion possibility, you can overwrite the query method phpDoc in your (typically custom abstract parent) migration class, where you can set the return type by the adapter in your current use._

Thank you.

**Comment by dereuromark** [comment]
PR open
