### ISSUE TITLE
Unable to connect using external variables

### ISSUE THREAD

**Issue by GlennM** [cakephp/phinx#1692]
I seem to be unable to use the external variables [as mentioned here](https://book.cakephp.org/phinx/0/en/configuration.html#external-variables)

When running `vendor/bin/phinx status` I get the connection error where the variables have not been replaced with values.
E.g. `There was a problem connecting to the database: SQLSTATE[HY000] [1045] Access denied for user '%%PHINX_DBUSER%%'@'localhost' (using password: YES)`

I'm using Docker with a separate database container.

When using the hardcoded values for the db connection in `phinx.yml` I am able to connect.

**Comment by MasterOdin** [comment]
What version of phinx are you running? Are the external variables properly exported to the environment (and so available within child processes outside the shell)? Also, what OS are you using it on?

**Comment by GlennM** [comment]
* **Version**: 0.11.4
* **OS**: macOS (latest version)

Can't easily reproduce this issue anymore since the codebase has changed a great amount since opening the issue. I managed to get my Phinx working in another way.

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/pull/1700 might fix this.
