### ISSUE TITLE
PostgreSQL adapter can't use smallserial type

### ISSUE THREAD

**Issue by badmansan** [cakephp/phinx#1693]
```php
$smallSerial = (new \Phinx\Db\Table\Column())->setName('id')
	->setType(\Phinx\Db\Adapter\AdapterInterface::PHINX_TYPE_SMALL_INTEGER)
	->setIdentity(TRUE);

$this->table('test', ['id' => FALSE, 'primary_key' => ['id']])
	->addColumn($smallSerial)
	->create();
```
The result table contains column ```id``` with type ```integer``` instead ```smallint```.
This is because of [this](https://github.com/cakephp/phinx/blob/master/src/Phinx/Db/Adapter/PostgresAdapter.php#L1132) code:
```php
$buffer[] = $column->getType() == 'biginteger' ? 'BIGSERIAL' : 'SERIAL';
```

Can any one fix this?

**Comment by dereuromark** [comment]
Why are you not using normal integers?
Are u able to make a pr here?

**Comment by badmansan** [comment]
> Why are you not using normal integers?
My reference table is very small, but related table is very large.

> Are u able to make a pr here?
Sure, [here](https://imgur.com/a/L4T0Lrl)

**Comment by dereuromark** [comment]
My tip for you: Don't nano-optimize.
It only creates problems without any benefit for you.
In this case you also don't gain anything.

**Comment by badmansan** [comment]
May be you right)
