### ISSUE TITLE
Migration with raw SQL files

### ISSUE THREAD

**Issue by jackie-d** [cakephp/phinx#1694]
Looking quickly at the official docs we can found on the beginning of the description this phrase:

>  It is preferred that you write your migrations using the Phinx PHP API, but raw SQL is also supported.

[Phynx Migrations](https://book.cakephp.org/phinx/0/en/migrations.html)

But if in my migration folder I put files containing SQL code, like:

```
20200101120000_create.sql
20200101120000_additional.sql
```

and then run 

`phynx migrate
`

I found in the database just being generating the table for the `phynx migration log `(empty) but none of the sql files are being executed. I also get a correct output from terminal but without any migration listed.

My configuration it's ok, either for db connection data and for folder paths.

What does exactly raw SQL support means and how to make it work? Thanks.

**Comment by garas** [comment]
It does look Phinx only supports `.php` files.

https://github.com/cakephp/phinx/blob/12f6eefcc0b6c6d90a82d624418e82e6c464b516/src/Phinx/Util/Util.php#L41

_Phinx PHP API_ likely means code like
```php
$users = $this->table('users');
$users->addColumn('username', 'string', ['limit' => 20])
        ->addColumn('password', 'string', ['limit' => 40])
        ->addIndex([ 'email'], ['unique' => true])
        ->create();
```

and _raw SQL is also supported_ means you can execute any SQL statement
```php
$this->execute('CREATE TABLE users ...');
$count = $this->execute('DELETE FROM users');
$stmt = $this->query('SELECT * FROM users');
```

**Comment by dereuromark** [comment]
You could also file_get_contents() those and then forward them to the execute() etc.
This way you have a main PHP file and then optionally also some SQL files.

I wonder if we should further look into the support of this feature.
Or if that can be then solved and closed as project implementation.

**Comment by jackie-d** [comment]
> You could also file_get_contents() those and then forward them to the execute() etc.

This could actually be a solution for a starting a one project with a backward compatibility injecting all the needed SQL files to a PHP-like formatted migration file as you say, and get a first db version.
From there on, we would need to rely only on PHP file migrations to keep the db schema updated, because to create duplication of PHP/SQL file for each migrations it's such a boilerplate.

I believe the support for both PHP extension and SQL dump-like formats would be a great feature, but moreover I also believe the needing of implementing both UP and DOWN migration directions could be quite an obstacle, as for PHP file it's one file implementing them both at the moment, and of course an SQL would have just to contain a single SQL algorithm, so this would bring the boilerplate to 3 files each migration (1 PHP + 2 SQL).

Actually a solution would be to just extend the cli by introducing a new generate parameter --sql that would create a php file from a prefilled template that would just do the file_get_contents() from other two also generated SQL file.

`
./phynx generate UserNation --sql
`
to generate

```
20200117120000_user_nation.php
20200117120000_user_nation_up.sql
20200117120000_user_nation_down.sql
```

in this way no core modification would be need to the migration engine, just to the CLI and to create a new template.

But lately, the really cool thing about possibly using SQL files, is the capability to create migrations without having the CLI or composer installed, just raw SQL inside a convenction-named file created.

That would be helpful to maintain developing tool at minimum and concentrate them on the run environment side.

Thanks.

**Comment by jackie-d** [comment]
As for example purpose, here's a script I prepared with the suggestion I got from you.
With this we can run the migration and it will include all the SQL file inside a specific subfolder of the migration folder.

```
<?php

use Phinx\Migration\AbstractMigration;

class Setup extends AbstractMigration
{
    public function up()
    {
        $sql = '';
        $currentDir = __DIR__;
        $subDir = 'setup';
        $dir = "$currentDir/$subDir";
        if ($handle = opendir($dir)) {
            while (false !== ($entry = readdir($handle))) {
                if ($entry != "." && $entry != ".." && strpos($entry,'.sql') === strlen($entry) - 4) {
                    $path = "$dir/$entry";
                    $fileSql = file_get_contents($path);
                    $sql .= $fileSql;
                }
            }
            closedir($handle);
        }

        $this->execute($sql);
    }

    public function down()
    {

    }

}
```

**Comment by JRDuncan** [comment]
@jackie-d I think RAW SQL is supported refers to using $this->execute($sql);
I do it sometimes especially when using MS SQL 
So you still have php migration files but inside the php file you have the RAW SQL inside the 
$this->execute function call

**Comment by dereuromark** [comment]
As this already works, we can close this at this point.

**Comment by JRDuncan** [comment]
@dereuromark I think we can close it

**Comment by jackie-d** [comment]
Yeah, finally I used the SQL-like solution I proposed just to give my app a first backward-compatibility bootstrap, later on, I switched totally to Phinx-like php migration that are quite effective.

The feature would still be useful but you can close this for me too.

**Comment by willy0275** [comment]
I'm a bit late to the party but I'm currently in a situation where I've got an existing project with SQL dump files which are currently imported manually in PHPMyAdmin when creating a new environment, and these files are maintained. As our process sucks, we want to switch to a migration system but although the file_get_contents technique "works" I thought it would have been much cleaner to do something like Flyway and allow .sql migration files.
