### ISSUE TITLE
Necessity of features, PR, timings, discussion lifecycle

### ISSUE THREAD

**Issue by jackie-d** [cakephp/phinx#1697]
Hi,
 I would need to ask the team how to proceed in order to get some new feature inside phynx.

Specifically, I'm going to use Phynx inside one of my project as main migration tool, as from my last day researches it seems to be one of the best tool around for migration in PHP.

But I have some specific needs (i.e.):
- Be able to run raw SQL migrations
- Seeding rollback (or at least, idempotence)
- Extend the TextWrapper support (already submitted a first PR)

These are some examples (quite all I would need btw) and I would be able to develop them by myself, but my question is: **how does the discussion, PR approval and timing works with this repositories and its maintainers?**

Of course I would like to include it in the master branch to have the possibility to keep it updated by the parent repo new updates for future security, bugfixing, improvements etc.

Is there a way I could contact you directly or the GitHub would just be enough? In both cases how many time would you usually need to review a PR,  release an updated version and distribute it on the composer channel?

Thanks for your minutes of attention.

**Comment by dereuromark** [comment]
This repo is not too actively maintained, but the core team tries the best to get things moving and merged.
It helps to provide a complete PR, green and with tests. Then we can directly approve and merge within days or even hours.

**Comment by jackie-d** [comment]
Yes, thank you for the suggestions about the test cases, I'll take care of it eventually next time.

Could you please tell me: usually how often new versions are released on the composer channel?

**Comment by othercorey** [comment]
There is no set release schedule. A new release recently happened to allow support for cakephp 4.0 through cakephp/migrations.
