### ISSUE TITLE
postgres schema is redirected when only a pdo connection is given

### ISSUE THREAD

**Issue by kimberv** [cakephp/phinx#1705]
I use postgres with multiple schemas in one database, and I hand in my pdo connection via phinx config rather than specify dsn settings. Though my pg connection is already properly set to point to the right schema, phinx is resetting schema to public if config.schema is not given ([see CakeAdapter line 63](https://github.com/cakephp/migrations/blob/master/src/CakeAdapter.php#L63)).

The easy workaround is to specify schema in the config, but it seems unnecessary. Preferred would be that, if I hand phinx a pdo connection via config, it would trust it and leave it alone. An uneducated suggestion would be to change line 63 to something like:

```
    if (!isset($config['connection']) && $connection->getDriver() instanceof Postgres) {
```

**Comment by corpsee** [comment]
@kimberv I guess you should create issue in [cakephp/migrations](https://github.com/cakephp/migrations) repository.

**Comment by MasterOdin** [comment]
@dereuromark this issue can be closed given that it's for a different repo.
