### ISSUE TITLE
Rollback Phinx migrations with Deployer

### ISSUE THREAD

**Issue by GlennM** [cakephp/phinx#1707]
Hi,

I'm using [Deployer](https://deployer.org/) for my deployment process.
Unfortunately, I'm experiencing some issues with the rollback of Phinx migrations.

Is anyone of you by any chance using Deployer & Phinx and can point me to the right direction?

Issue is over here:
https://github.com/deployphp/deployer/issues/1987

**Comment by dereuromark** [comment]
So far now feedback, closing for now.
