### ISSUE TITLE
binary for postgres with limit option throws exception

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1736]
Using the following migration:
```php
        $this->table('users')
            ->addColumn('col', 'binary', ['limit' => 32])
            ->create();
```

generates the following SQL:
```sql
CREATE TABLE "public"."users" ("id" SERIAL NOT NULL, "col" BYTEA (32) NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
```

which throws the following exception / error:
```
PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR:  type modifier is not allowed for type "bytea"
LINE 1: ...BLE "public"."users" ("id" SERIAL NOT NULL, "col" BYTEA (32)...
                                                             ^ in /Users/mpeveler/Work/Github/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:184
```

It would feel like the appropriate thing would be to just drop the limit and generate the following SQL:
```sql
CREATE TABLE "public"."users" ("id" SERIAL NOT NULL, "col" BYTEA NOT NULL, CONSTRAINT "users_pkey" PRIMARY KEY ("id"));
```

Should this be documented in the docs that limit cannot be used with `binary` for postgresql, or should the limit just be dropped implicitly for postgresql adapter?

**Comment by dereuromark** [comment]
I think you should be using https://github.com/cakephp/phinx/pull/1734 :)
Please check and we can continue with that.

**Comment by MasterOdin** [comment]
Changed the limit to be something not `16` to make the issue not tie into the binaryuuid stuff at all.

**Comment by dereuromark** [comment]
Jep, I adjusted my comment. Sry for that ;)
