### ISSUE TITLE
Method to add unique constraint for postgres

### ISSUE THREAD

**Issue by sooners87** [cakephp/phinx#174]
DB: postgres

$table = $this->table('test_table')
                    ->addColumn('test_field', 'string', array('limit' => 10))
                    ->save();

$this->execute("ALTER TABLE ONLY test
                        ADD CONSTRAINT test_key UNIQUE (test_field);");

Has a method to add unique index. But could not see a method to add constraint, so i am doing a separate alter table to do it. Is there a method to add unique constraint?

**Comment by ohchi** [comment]
I think `addIndex` is not what sooners87 is looking for...
He is looking for a method to add constraint, not index.

**Comment by celorodovalho** [comment]
:+1: for this feature!
ADD CONSTRAINT is essential.
"CREATE INDEX" is different of "ADD CONSTRAINT".

Constraints have a name.
