### ISSUE TITLE
Add binaryuuid type support to sql server

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1746]
From https://github.com/cakephp/phinx/pull/1734#issuecomment-612300523, https://github.com/cakephp/phinx/pull/1734#issuecomment-612337231

> For SQLServer, binaryuuid would probably map to the same type as static::PHINX_TYPE_UUID, namely uniqueidentifier, though like the postgresql adapter, you would not be able to do a comparison against static::PHINX_TYPE_BINARYUUID on saved columns in a table.

The `static::PHINX_TYPE_BINARYUUID` was added to MySQL, PostgreSQL, and SQLite. Needs to be added to SQL Server, this issue acting as a reminder for that.

**Comment by geoidesic** [comment]
So how do we use this for primary key?

**Comment by dereuromark** [comment]
We should add unit tests for all DBs here that support it to make sure it works for primary keys.
