### ISSUE TITLE
Test against minimum and maxium versions of mysql and postgres

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1760]
Right now, phinx is tested only against mysql 5.7 and postgres 9.6. The latest versions of mysql is 8.0 and postgres is 12.2. It would be good for Phinx to define what versions of databases it supports and to also test against the minimum and maximum of that range, especially given things like #1759 which showed that phinx users are going to encounter a breaking change if they move their database from 5.7 to 8.0 and rely on column widths for integers in some way. It would also be good for as I continue working on the geometry stuff for mysql 8, it gets tested continuously and not just skipped.

Proposed changes would be to expand the Travis-CI configuration to specify those versions, and to use Docker to spin-up containers for the given version. For example, for the currently specified versions, the run commands would look something like:

```
docker run --env MYSQL_DATABASE=phinx_testing --env MYSQL_ALLOW_EMPTY_PASSWORD=yes -p 3306:3306 mysql:5.7 --default-authentication-plugin=mysql_native_password --default-authentication-plugin=mysql_native_password
docker run --env POSTGRES_DB=phinx_testing -p 5432:5432 postgres:9.6
```

**Comment by othercorey** [comment]
mysql8 container in travis has shown to be very slow. I recommend just copying the mysql8 github action from cakephp/cakephp to setup a single test environment.

**Comment by MasterOdin** [comment]
So make a single github workflow for just mysql 8 and leave everything the way it is (in Travis and appveyor)? I'm really not sure what you're asking for here and in https://github.com/cakephp/phinx/pull/1759#issuecomment-625575279. Rewrite all CI stuff to just use GitHub actions?

> I recommend just copying the mysql8 github action from cakephp/cakephp to setup a single test environment.
Sure, which uses docker with a similar command as I put above. Either way you slice it, docker here is the way to do mysql 8 regardless of platform.

**Comment by othercorey** [comment]
> Rewrite all CI stuff to just use GitHub actions?

I said the opposite. Just create the test you need.

> Just need to create a single mysql 8 environment - not rewrite every test.
