### ISSUE TITLE
Make primary key unsigned by default

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1780]
Given that #1763 is a breaking change on default options for table creation, it's probably also a good opportunity to also make the primary key column unsigned by default. This was discussed in #657. The [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/example-auto-increment.html) recommend doing it (though strangely enough it's not in their starting example):

> Use the UNSIGNED attribute if possible to allow a greater range. For example, if you use TINYINT, the maximum permissible sequence number is 127. For TINYINT UNSIGNED, the maximum is 255.

**Comment by dereuromark** [comment]
Also bools should be unsigned by default IMO, there is no point in allowing negative range for something that should only be 0 or 1.

**Comment by othercorey** [comment]
There is no unsigned type in postgresql. How would you resolve the expectation here?

**Comment by dereuromark** [comment]
Wouldn't it just ignore that part here on this DB type? But allowing the others to act accordingly?

**Comment by othercorey** [comment]
In general that might feel ok, but I'm not sure promising a certain ID range and then not providing it is the best for a primary key.

**Comment by dereuromark** [comment]
I don't think you can promise more than the DB can offer. And we are talking about a very high number here anyway, So this is fair to apply IMO.

**Comment by othercorey** [comment]
I think the same argument suggests we don't need it.

**Comment by dereuromark** [comment]
I agree that we dont need it :) That doesn't mean we don't need to do it.
It seems to make sense for the DBs that offer it.

**Comment by MasterOdin** [comment]
Postgresql uses a `serial` column type that has a range of 1 to 2147483647, sql server uses `identity` which limits between -2147483648 to 2147483647 (though we just go from 1 upward). SQLite has unsigned, but it's also kind of goofy in how it does affinity and stuff.

The reason to not do this would be to keep a similar max value as other adapters, but a value would be for people who only use mysql would gain space.

**Comment by othercorey** [comment]
It just feels like mysql is the special case here and it's suggesting things for other dbs that don't exist just to avoid a mysql special case.

serial is not a real data type. it's just an integer.

**Comment by dereuromark** [comment]
As long as phinx is defaulting and handling this internally without having to specify things on user side, this is a win for everyone. The invalid ranges are gone where possible, less space used by default here, and other engines are not bothered.

**Comment by othercorey** [comment]
I would suggest adding a psuedo-type for the default incremental/serial type here then. It is an alias for a documented type for each DB.

**Comment by MasterOdin** [comment]
I think I'd also like to be more specific in that this would only affect the default `id` column that phinx creates, not a user specified column where they set `identity => true`. If they set `id` to false or to a custom string, then it will be up to the user to define if they want it signed or unsigned. In that way, how a primary key gets done is more "DB implementation detail" than anything else and a user can be somewhat oblivious to that detail if they so choose (and also benefit from an increased size by default for mysql).

This is different from say `decimal` and precision handling and what should phinx do in those cases (where I advocate for forcing defaults across data providers as all do different defaults, one of which is totally incompatible with the others, see https://github.com/cakephp/phinx/issues/1481#issuecomment-626274282 and #1632).

**Comment by MasterOdin** [comment]
The principle reason I would see not to do it is that it does make writing foreign key constraints harder for old tables before this change and new style tables, but I think just providing a simple example of how to upgrade your tables in the "migrate to Phinx 0.13" (or whatever version this land) docs would suffice.

**Comment by othercorey** [comment]
Sounds like that good be fine then.

**Comment by dereuromark** [comment]
@MasterOdin Did you want to provide a PR here for those defaults?
I think we would all be on board of that.

**Comment by MasterOdin** [comment]
@dereuromark the milestone here should probably be 0.13.x given its a BC breaking change, and my PR targets the `0.next` branch.
