### ISSUE TITLE
Version dropdown on https://book.cakephp.org/phinx has broken links

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1793]
The two versions there link to:

0.12: https://book.cakephp.org//phinx/12/en
0.11: https://book.cakephp.org//phinx/11/en

It looks like the docs do not support displaying minor versions?

**Comment by dereuromark** [comment]
@markstory might have more info here.

**Comment by saeideng** [comment]
> It looks like the docs do not support displaying minor versions?

only major versions supported , so just we have `0` here

**Comment by markstory** [comment]
His should be fixed now.
