### ISSUE TITLE
database credentials obfuscation in stack trace

### ISSUE THREAD

**Issue by maikezan** [cakephp/phinx#1796]
Hello, while trying to integrate phinx in a project, i've been faced with some concern about possible database credentials exposure. During a test the script was unable to connect to my database, and it rightfully throwed an expection. My issue is that within the error stack trace, the connection config is exposed clearly (of course i've covered the details, but you can see the point) :
![Annotazione 2020-05-28 113446](https://user-images.githubusercontent.com/61838461/83125381-c020a880-a0d7-11ea-8ffb-f0bfa69d53e5.png)

Is there any way to avoid this?

**Comment by dereuromark** [comment]
Since PHP7.3 the default for production on stack trace arguments is off afaik.
Make sure it is set to this on your prod system.
And for local debug this is a non issue IMO.

**Comment by maikezan** [comment]
Thanks for the quick reply.
Of course local debug this is no issue. 
I thought you were referring to having the display_errors off, tested and still i can see the logs containing the exposed credentials. So I've checked and i think you referring to an ini addition which is available from php7.4 and in fact disables arguments by default. 

`zend.exception_ignore_args is a new INI directive for including or excluding arguments from stack traces generated from exceptions.`

Unfortunately we're currently still on 7.3 so this is not (yet) an option.
Thanks for pointing in the right direction, i can close this since it is not really an issue with your package anyway :)
