### ISSUE TITLE
"Valid Column Types" wrote twice in documentation.

### ISSUE THREAD

**Issue by yolong-lin** [cakephp/phinx#1802]
As the title says, I find the same heading in the documentation.
https://book.cakephp.org/phinx/0/en/migrations.html#valid-column-types
https://book.cakephp.org/phinx/0/en/migrations.html#id3

Furthermore, their contents are not the same.
I don't know which one should follow.

**Comment by dereuromark** [comment]
Can we update the docs here maybe?
