### ISSUE TITLE
Adding foreign key fails.

### ISSUE THREAD

**Issue by paddelboot** [cakephp/phinx#1805]
Hello,

I am trying to create the following table:

        public function change() {

        $inbound = $this->table( 'inbound_out' );
        $inbound->addColumn( 'inbound_id', 'integer' )
            ->addColumn( 'primary_id', 'integer', [ 'null' => TRUE ] )
            ->addColumn( 'uuid', 'string', ['limit' => 36] )
            ->addColumn( 'destination', 'string', ['limit' => 40, 'null' => TRUE] )
            ->addColumn( 'description', 'string', ['limit' => 200, 'null' => TRUE] )
            ->addColumn( 'duration_ringing', 'integer', ['limit' => MysqlAdapter::INT_SMALL] )
            ->addColumn( 'duration', 'integer', ['limit' => MysqlAdapter::INT_SMALL] )
            ->addColumn( 'success', 'integer', ['limit' => MysqlAdapter::INT_TINY] )
            ->addColumn( 'hangup_cause', 'string', ['limit' => 200, 'null' => TRUE] )
            ->addColumn( 'date_time', 'datetime' )
            ->addIndex( ['uuid'], ['unique' => true] )
            ->addForeignKey('primary_id', 'tags', 'id', ['delete'=> 'SET_NULL', 'update'=> 'CASCADE'])
            ->create();
    }

Upon migrating, I get

`PDOException: SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint in /app/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:167`

When I run a `$phinx rollback` to revert the table creation and fix my migration code, I get

`Cannot reverse a "Phinx\Db\Action\ChangeColumn" command`

So what exactly is the issue I am facing here? Thanks.

**Comment by paddelboot** [comment]
Oops, the referenced table `tags` is wrong. But why does the rollback command not work?

**Comment by garas** [comment]
Migration was aborted, so there you don't need to rollback it.

Previous successfully executed migration has `changeColumn()` action which cannot be automatically reverted. That migration should have `up()` and `down()` to be reversible by defining reverse action of `changeColumn()`.

**Comment by paddelboot** [comment]
I accidentally deleted the referenced table, and I cannot rollback because I didn't know that `changeColumn` needs an up and down method. So now I have a big migrating mess here.

How to proceed in situations like this when you're stuck in the migrating process? Thanks again.

**Comment by garas** [comment]
Check current state with `phinx status`.

You can restore from backup, manually fix database, or run all migrations from beginning depending how big mess you have.

**Comment by paddelboot** [comment]
Thanks, but how can I run all migrations from the beginning if I cannot rollback?
