### ISSUE TITLE
Add command to test DB connection

### ISSUE THREAD

**Issue by Bilge** [cakephp/phinx#1808]
There should be a command that just tests connectivity.

**Comment by garas** [comment]
There is already `phinx test` command which verify configuration file and connection.

https://github.com/cakephp/phinx/blob/master/src/Phinx/Console/Command/Test.php

**Comment by Bilge** [comment]
It only verifies the config file.

**Comment by garas** [comment]
Specify environment and it will be checked

https://github.com/cakephp/phinx/blob/a1552300e1056d2cc8d6a6f0db7cc33deb10a28f/src/Phinx/Console/Command/Test.php#L91-L92

**Comment by Bilge** [comment]
I see. Probably that should be stated explicitly in the command line help? It's not very intuitive currently.
