### ISSUE TITLE
How do I get current environment PDO adapter?

### ISSUE THREAD

**Issue by Marcin-TA** [cakephp/phinx#1812]
Hi! I'm creating unit tests with Phinx. I created migrations and seeds and ran it on my test database. However, I do need DB adapter do past to my DB models. How can I get it?

I run that code on my unit tests and it would be good to extract DB pgsql connection from these classes, but I didn't found a way to do it.

```php
$phinx = new PhinxApplication();
$phinx->setAutoExit(false);
$phinx->run();

self::$T = new TextWrapper($phinx);
self::$T->getMigrate("testing");
self::$T->getSeed("testing");
```

[ 1 ] Or at least how to get environment configs with one of these classes? ^
[ 2 ] Or maybe there is a way to pass custom adapter to `PhinxApplication`?

**Comment by MasterOdin** [comment]
Your best bet would be to probably to not go through the PhinxApplication, but rather directly call down into `\Phinx\Migration\Manager.php->migrate` method. You would then be able to construct a Config object for the manager to use and you can directly set a specific PDO connection as part of that.

**Comment by Marcin-TA** [comment]
Good idea, but it won't work on my project as we used lumina/zend factory DB connection. There is no way that Zend Factory will return PDO interface, so no way to integrate it with Phinx config and Manager :/ Anyway. Is there any way to change the migration path on the fly? During the run of the unit test? Thanks!

**Comment by MasterOdin** [comment]
I would just construct a new phinx Config object with the settings you want. If you really want to change the path without constructing a new object, you'll need to extend the Object and add a new method to allow you to set the path on the fly.

**Comment by rquadling** [comment]
How about something along these lines?

```php
$phinxManager = Container::build()->get(\Phinx\Migration\Manager::class);
$pdo = $phinxManager->getEnvironment('development')->getAdapter()->getConnection();
```

I'm using PHP-DI for the container, and have the following in my `di-config.php` script:

```php
    Phinx\Config\ConfigInterface::class => function () {
        return \Phinx\Config\Config::fromPhp(\WorkflowUtilities\Directories::getRootDirectory().'/phinx.php');
    },
    Symfony\Component\Console\Input\InputInterface::class => function () {
        return new \WorkflowUtilities\Input(array_get($_SERVER, 'argv', []));
    },
    Symfony\Component\Console\Output\OutputInterface::class => function (ContainerInterface $c) {
        return PHP_SAPI == 'cli'
            ? new \Symfony\Component\Console\Output\ConsoleOutput()
            : $c->get(\WorkflowUtilities\BufferedOutput::class);
    },
```

And the little extras there ...

```php
<?php

namespace WorkflowUtilities;

class BufferedOutput extends \Symfony\Component\Console\Output\BufferedOutput
{
    /**
     * {@inheritdoc}
     *
     * Also removes the escaping of <fg> and <bg> tags.
     */
    public function write($messages, $newline = false, $options = self::OUTPUT_NORMAL)
    {
        // $tagRegex and the preg_replace regex are taken from \Symfony\Component\Console\Formatter\OutputFormatter::format()
        $tagRegex = '[a-z][a-z0-9_=;-]*+';

        parent::write(
            array_map(
                function ($message) use ($tagRegex) {
                    return preg_replace("#\\\(?=<(($tagRegex) | /($tagRegex)?)>)#ix", '', $message);
                },
                (array) $messages
            ),
            $newline,
            $options
        );
    }
}

```

and

```php
<?php

namespace \WorkflowUtilities;

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputDefinition;

class Input extends ArgvInput
{
    public function __construct(array $argv = null, InputDefinition $definition = null)
    {
        parent::__construct($argv ?? $_SERVER['argv'] ?? [], $definition);
    }

    /**
     * Expose the setTokens method to allow us to inject URL params into an ArgvInput
     * without needing to create a new ArgvInput.
     *
     * @param array $tokens
     */
    public function setTokens(array $tokens)
    {
        parent::setTokens($tokens);
    }
}

```

**Comment by Marcin-TA** [comment]
Thank you guys! I have created TestDabase and set up all I needed in that class :) Any idea about zero-downtime deployment? Does Phinx cope with that? :) Thanks!

**Comment by dereuromark** [comment]
That part depends on your deployment strategy, but it is possible using phinx. 
Closing then now.

**Comment by Marcin-TA** [comment]
It's quite important to support Zero Downtime Deployment with a Database. I can see that Phinx wraps all the migrations into SQL transaction, but that's not enough. It would be good to have Zero Downtime Deployment support with DB table locks.

**Comment by Vitexus** [comment]
My Current solution:
```php
        if ($this->adapter->getAdapterType() != 'sqlite') {
            $table
                ->changeColumn('id', 'biginteger', ['identity' => true, 'signed' => false])
                ->save();
        }
```
