### ISSUE TITLE
Support looking up named foreign keys in sqlite

### ISSUE THREAD

**Issue by MasterOdin** [cakephp/phinx#1857]
In the sqlite adapter, when using the `hasForeignKey` function with a named constraint, it will currently issue an exception:

https://github.com/cakephp/phinx/blob/dd6607115169b1f5cf6e8307d1eadc97723cdd7e/src/Phinx/Db/Adapter/SQLiteAdapter.php#L1118-L1122

While it is true that sqlite does not offer direct support for looking up a named constraint directly via looking at the `foreign_key_list` pragma, we could work around this by using a call to `getDeclaringSql` with regex to parse out the foreign key constraints to combine with the information in `foreign_key_list` to generate a list that contains the name (if available). Given the amount of gymnastics we go through with altering a table to get around sqlite's various deficiencies, there seems to me no reason not to add the support for this.

This would in-theory pave the way for allowing to drop a foreign key constraint using its name within sqlite, which is also marked as unsupported.

**Comment by othercorey** [comment]
> This would in-theory pave the way for allowing to drop a foreign key constraint using its name within sqlite, which is also marked as unsupported.

How would it drop the foreign key?

**Comment by MasterOdin** [comment]
I think as a similar fashion as the deleting a foreign key by columns, where get the create table DDL, then use regex to remove the named foreign key looking to remove, run that new query to generate a new table, copy data from old table to new, drop old table, rename new. I think the regex in question here can be used both for the `hasForeignKey` and this function, and that it would be easier to start with the non-destructive case first to get it written.

**Comment by othercorey** [comment]
This will have issues with foreign key constraints on that table.

**Comment by MasterOdin** [comment]
What sort of issues would removing a named foreign key constraint have that removing an unnamed foreign key constraint using the same general method not have?

**Comment by othercorey** [comment]
None that I'm aware of. Its just a dependency issue in general.
