### ISSUE TITLE
Silent failure exit code 3

### ISSUE THREAD

**Issue by Pi-George** [cakephp/phinx#1874]
I don't really have much to go on here, running phinx status gives me no issues although it takes about 5 minutes just to give me that (I have no idea why it's taking so long). And running phinx migrate just seems to spit out exit code 3 and nothing else. This is all running on CircleCI.

Does anyone know what exit code 3 actually means for phinx so I can try and debug this, I couldn't find anything in the documentation.

**Comment by MasterOdin** [comment]
The only command that should give exit code 3 is `phinx status`, and that will only do that if there are down migrations within your system. `phinx migrate` should only give an exit code of 0 or 1, unless symfony is setting it to 3 for some reason.

Do you get any output at all from running `phinx status` or `phinx migrate` on CircleCI?

**Comment by Pi-George** [comment]
Ah that probably explains it, it's likely CircleCI reacting to the exit code from the phinx status on the previous line and dying, and it's not the phinx migrate at all. Since I got a nice output from the phinx status I assumed it was the command after that which was failing. Thanks for your help
