### ISSUE TITLE
Collation and encoding for other text column types

### ISSUE THREAD

**Issue by pe1uca** [cakephp/phinx#1876]
Currently phinx throws and exception when trying to use encoding or collation for column types that are not `char, string, text`

As described in the [character set and collation](https://dev.mysql.com/doc/refman/8.0/en/charset-column.html) documentation of MySQL 
> Every “character” column (that is, a column of type CHAR, VARCHAR, a TEXT type, or any synonym) has a column character set and a column collation 

Going to the [TEXT documentation](https://dev.mysql.com/doc/refman/8.0/en/blob.html) we can see this
> The four TEXT types are TINYTEXT, TEXT, MEDIUMTEXT, and LONGTEXT

Also in the [ENUM documentation](https://dev.mysql.com/doc/refman/8.0/en/enum.html) under "Handling of Enumeration Literals" it mentions collation can be used.

We can see in the code here is the reason for collation
https://github.com/cakephp/phinx/blob/61c4710dd15bb15b796ed8869d8527ffb25262a2/src/Phinx/Db/Table/Column.php#L644-L658
And for encoding
https://github.com/cakephp/phinx/blob/61c4710dd15bb15b796ed8869d8527ffb25262a2/src/Phinx/Db/Table/Column.php#L679-L693

Can that list of `$allowedTypes` be expanded to the possible values?
Would it be better to remove that check since the list can get pretty big and the DB already checks for that?

**Comment by dereuromark** [comment]
Feel free to make the PR here.
