### ISSUE TITLE
Fix version 0.11.7  Error: Call to undefined method Cake\Database\Query::fetchRow()

### ISSUE THREAD

**Issue by EOM** [cakephp/phinx#1883]
Hi method undefined in version 0.11.7 ..?

CODE Example:
`       
   public function up(){ 
        $tabla = 'configuraciones_parametros';

        // create the table
        $table = $this->table($tabla);

        $builder = $this->getQueryBuilder();
        $builder->select(['count' => $builder->func()->count('*')])->from($tabla)
            ->where(['flag' => 'app_filtrar_abm_por_deposito_segun_usuario']);
        // Get data
        //  $yaExite = $builder->execute()->fetchRow();
        $yaExite = $builder->fetchRow();
        exit(var_dump($yaExite));

        if ($this->isMigratingUp() && $yaExite===0) {
            $table->insert([[
                'flag' => 'app_filtrar_abm_por_deposito_segun_usuario',
                'parametro' => 0,
                'descripcion' => '[APP]: .......',
                'tipo_de_dato' => 'bool'
            ]])->create();
        }
    }
`

ERROR Print:
![image](https://user-images.githubusercontent.com/1219132/94284780-3c61b600-ff29-11ea-9155-3bd444485e73.png)

**Comment by MasterOdin** [comment]
`getQueryBuilder()` returns a [`Cake\Database\Query`](https://api.cakephp.org/3.8/class-Cake.ORM.Query.html) object where you must use the [`execute`](https://api.cakephp.org/3.8/class-Cake.ORM.Query.html#_execute) method which returns a [`StatementInterface`](https://api.cakephp.org/3.8/class-Cake.Database.StatementInterface.html). From there, you can either use [`fetch`](https://api.cakephp.org/3.8/class-Cake.Database.StatementInterface.html#_fetch) or [`fetchAll`](https://api.cakephp.org/3.8/class-Cake.Database.StatementInterface.html#_fetchAll) to get results.

**Comment by EOM** [comment]
> `getQueryBuilder()` returns a [`Cake\Database\Query`](https://api.cakephp.org/3.8/class-Cake.ORM.Query.html) object where you must use the [`execute`](https://api.cakephp.org/3.8/class-Cake.ORM.Query.html#_execute) method to trigger it, and which returns a [`StatementInterface`](https://api.cakephp.org/3.8/class-Cake.Database.StatementInterface.html). From there, you can either use [`fetch`](https://api.cakephp.org/3.8/class-Cake.Database.StatementInterface.html#_fetch) or [`fetchAll`](https://api.cakephp.org/3.8/class-Cake.Database.StatementInterface.html#_fetchAll) to get results.
> 
> For example, from your code, you would do something like this to get the first entry in the first row of your result (the count):
> 
> ```
>     $yaExite = $builder->execute()->fetch()[0];
> ```

Hi, ok , Gracias
