### ISSUE TITLE
Index include columns

### ISSUE THREAD

**Issue by JRDuncan** [cakephp/phinx#1893]
public function change()
{
    $table = $this->table('users');
    $table->addColumn('email', 'string')
          ->addColumn('firstname','string')
          ->addColumn('lastname','string')
          ->addIndex(['email'], ['include' => ['firstname' , 'lastname']])
          ->create();
}

**Comment by othercorey** [comment]
@JRDuncan This issue does not provide us with any information. Is this a question or a feature request? What is the context?

**Comment by MasterOdin** [comment]
I suspect it is to support the ability to include columns in an index in SQL Server: https://docs.microsoft.com/en-us/sql/relational-databases/indexes/create-indexes-with-included-columns?view=sql-server-ver15

**Comment by othercorey** [comment]
Closing as this isn't a valid issue.

**Comment by JRDuncan** [comment]
@MasterOdin @othercorey 

It is to Create Indexes with Included Columns. Supported by SQL server and Postgresql

**Comment by MasterOdin** [comment]
Recreated this as #1903 with sufficient detail on what is being asked for, links to related documentation for databases, and your original example, which was lacking here, which is more what I think @othercorey referred to saying this is not a valid issue.

**Comment by JRDuncan** [comment]
Thank you @MasterOdin
