### ISSUE TITLE
Postgresql cannot change column type from text to integer

### ISSUE THREAD

**Issue by qWici** [cakephp/phinx#1940]
Migration code:
```php
$products = $this->table('products');
$products->changeColumn('product_id', 'biginteger')
         ->save();
```

Error:
```sh
PDOException: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "product_id" cannot be cast automatically to type bigint
HINT:  You might need to specify "USING product_id::bigint". in /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:181
Stack trace:
#0 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(181): PDO->exec()
#1 /vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(112): Phinx\Db\Adapter\PdoAdapter->execute()
#2 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(606): Phinx\Db\Util\AlterInstructions->execute()
#3 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(981): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps()
#4 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(484): Phinx\Db\Adapter\PdoAdapter->executeActions()
#5 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(434): Phinx\Db\Adapter\AdapterWrapper->executeActions()
#6 /vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(153): Phinx\Db\Adapter\TimedOutputAdapter->executeActions()
#7 /vendor/robmorgan/phinx/src/Phinx/Db/Table.php(722): Phinx\Db\Plan\Plan->execute()
#8 /vendor/robmorgan/phinx/src/Phinx/Db/Table.php(629): Phinx\Db\Table->executeActions()
#9 /vendor/robmorgan/phinx/src/Phinx/Db/Table.php(688): Phinx\Db\Table->update()
#10 /db/migrations/20201208150956_update_products_columns.php(15): Phinx\Db\Table->save()
#11 /vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(109): UpdateProductsColumns->up()
#12 /vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(383): Phinx\Migration\Manager\Environment->executeMigration()
#13 /vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration()
#14 /vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate()
#15 /vendor/symfony/console/Command/Command.php(255): Phinx\Console\Command\Migrate->execute()
#16 /vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#17 /vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#18 /vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun()
#19 /vendor/symfony/console/Application.php(166): Phinx\Console\PhinxApplication->doRun()
#20 /vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#21 {main}
```

This is because it is not easy to change the field type if the table contains data. Since the varchar type was used, PostgreSQL can't determine if the value belongs to integer.

The problem can be solved by using USING - the expression specified in the error message. So we will perform data conversion to integer correctly:
```sql
ALTER TABLE products ALTER COLUMN product_id TYPE bigint USING (product_id::bigint);
```

**Comment by dereuromark** [comment]
Do you want to make a PR with your suggested changes? That would be awesome.

**Comment by qWici** [comment]
> Do you want to make a PR with your suggested changes? That would be awesome.

I am not very familiar with the architecture of this package. If you tell me how best to do it, I will.

**Comment by MasterOdin** [comment]
@qWici You would want to change the [`getChangeColumnInstruction`](https://github.com/cakephp/phinx/blob/master/src/Phinx/Db/Adapter/PostgresAdapter.php#L540) function for the adapter in question (postgres), adding the `USING ($column::$type)` as appropriate. You'll then want to add a test to [PostgresAdapterTest](https://github.com/cakephp/phinx/blob/master/tests/Phinx/Db/Adapter/PostgresAdapterTest.php) where you create a column as string, insert string numerics, then convert the column to bigint. The [testChangeColumn](https://github.com/cakephp/phinx/blob/master/tests/Phinx/Db/Adapter/PostgresAdapterTest.php#L819-L834) and [testInsertData](https://github.com/cakephp/phinx/blob/master/tests/Phinx/Db/Adapter/PostgresAdapterTest.php#L1825-L1847) functions should demonstrate how to do these steps.

**Comment by qWici** [comment]
@MasterOdin Yes, postres will return an error `[22P02] ERROR: invalid input syntax for integer: "some"`. It's ok? Or need to throw some Exception?

**Comment by MasterOdin** [comment]
Nope, you will not need to add any sort of error handling / throw code for your patch. Phinx will automatically surface the database exception.

**Comment by qWici** [comment]
Related PR  - #1941
