### ISSUE TITLE
Using auto incremental number as migration file name instead of timestamp

### ISSUE THREAD

**Issue by joseph-cs** [cakephp/phinx#1942]
Is there any way i can use auto incremental number as phinx migration filename instead of timestamp ? And use '--target' to migrate up / down to specific file ?

**Comment by dereuromark** [comment]
That is not a useful requirement for real life (multi person team) scenario.
The main reason for the timestamp is collision change reduction of multiple people developing migrations.
This way, when migrating, you don't run into duplicates.
If all teams would increment as such, there would always be collisions.
