### ISSUE TITLE
Create migration problem when PHP 8.0 used.

### ISSUE THREAD

**Issue by crlam0** [cakephp/phinx#1945]
I got error :
Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in D:\httpd\htdocs\boot.nsk.ru\vendor\robmorgan\phinx\src\Phinx\Util\Util.php:111
The problem is in the order of the arguments for the implode:
Was:
`$fileName = static::getCurrentTimestamp() . '_' . strtolower(implode($arr, '_')) . '.php';`
This is correct:
`$fileName = static::getCurrentTimestamp() . '_' . strtolower(implode('_', $arr)) . '.php';`

**Comment by MasterOdin** [comment]
This has been fixed in master, and should be part of the upcoming 0.12.0 release.

**Comment by dereuromark** [comment]
Lets prepare the patch release.

**Comment by JoyceBabu** [comment]
Unless something major is pending, could you please create a patch release soon?
