### ISSUE TITLE
Allow parameters to be bound to migration SQL statements

### ISSUE THREAD

**Issue by Roy-Orbison** [cakephp/phinx#1954]
It would be preferable to use the convenience methods (that add to the migration timer) rather than having to manually pull out the connection (from `$this->getAdapter()->getConnection()`) and prepare PDO statements when migrating data. This would avoid having to cast, sanitise, and/or validate values used in schema alterations.

https://github.com/cakephp/phinx/blob/9457e3879b0abc02a4022941a6a535141889432e/src/Phinx/Migration/AbstractMigration.php#L196
https://github.com/cakephp/phinx/blob/9457e3879b0abc02a4022941a6a535141889432e/src/Phinx/Migration/AbstractMigration.php#L204

 [Phinx's minimum PHP version](https://github.com/cakephp/phinx/wiki#version-and-branch-overview) is listed as 5.6 so the signatures could be made variadic:
```php
public function execute($sql, ...$params)
```
so developers can choose either:
```php
$this->execute($sql, ...$params);
```
or:
```php
$this->execute($sql, $param1, $param2, $param3);
```

**Comment by garas** [comment]
This would be very useful.

But signature would be `public function execute($sql, array $params = [])` as placeholders can be `:named` or `?`.

**Comment by Roy-Orbison** [comment]
Variadic is ideal because the number of bound values for a query is 0 to *n*. Named parameters are less useful because `$sql` will always be required, the spread operator already makes `$params` optional, and there aren't several other parameters with default values. Horses for courses.

**Comment by Roy-Orbison** [comment]
Sorry, I misread your comment as named PHP arguments, your signature would be preferable in that case.

If `:named` are supported then shouldn't types be? If so, it'd probably best to add a tiny helper class that represents a parameter, e.g. `MigrationStatementParameter` where the ctor is passed the value and type. Then, when iterating the `$params` to call `PDOStatement::bindValue` on each, encountering an instance of it can change the type from the default of string.

**Comment by garas** [comment]
I think it should stay simple and be simple array. It would be just proxy to [PDOStatement::execute($parameters)](https://www.php.net/manual/en/pdostatement.execute.php), thus all values are binded as `PDO::PARAM_STR`.

For advanced use, user still can get connection from `$this->getAdapter()->getConnection()`.

**Comment by Roy-Orbison** [comment]
It does make for simpler code, but half the problem is that using the raw connection does not add to the timer. This makes it hard to judge the impact of a migration.

**Comment by garas** [comment]
Timers for `execute`/`query` would be added by adding methods to `Phinx\Db\Adapter\TimedOutputAdapter`.

But this would still not add timers when using raw connection.

**Comment by Roy-Orbison** [comment]
Could probably tack the parameters from `PDOStatement::fetchAll()` onto `AbstractMigration::query()` as well.

**Comment by MasterOdin** [comment]
@Roy-Orbison, With #1962, using bound parameters will be supported in 0.13, and this issue can be closed, and perhaps a separate one opened about the thread on timers?

**Comment by Roy-Orbison** [comment]
@MasterOdin Don't think timers needs another issue. I hadn't realised till [this comment](https://github.com/cakephp/phinx/pull/1962#issuecomment-784652775), that one can manually start the timer before running statements with an unwrapped connection.

**Comment by MasterOdin** [comment]
@Roy-Orbison @dereuromark could we close this issue?
