### ISSUE TITLE
Phinx cookbook download?

### ISSUE THREAD

**Issue by mehov** [cakephp/phinx#1970]
Hi everyone,

I would like to download the full Phinx cookbook similarly to how I can [download the CakePHP cookbook in e.g. PDF](https://book.cakephp.org/4/_downloads/en/CakePHPCookbook.pdf), but the closest mention I could find is #1698. So instead of hijacking someone else's issue, I thought I'd ask here if there simply are any plans to make it available? 

Since it looks like both cookbooks are using the same backend documentation HTML generator, I'd guess it should be easy to convert? I may be wrong though. Either way, please let me know. Thank you!

**Comment by markstory** [comment]
So far we haven't been generating PDFs for standalone package sites as the main PDF is low usage and PDF generation takes a bit of on each build. With that said it is doable with some work to https://github.com/cakephp/docs-builder and this repositories make files to also build the latex and pdf targets that sphinx has.
