### ISSUE TITLE
is there such an Clickhouse adapter?

### ISSUE THREAD

**Issue by rusboard** [cakephp/phinx#1978]
Has anyone seen an adapter for working with ClickHouse? it would be very cool.

**Comment by MasterOdin** [comment]
To my knowledge there is no clickhouse adapter for phinx. Writing one would unfortunately not be super trivial due to a number of differences that Clickhouse has with the SQL standard, like having its own type system and the myriad of options on creating a table with regards to pivots, engine, etc.
