### ISSUE TITLE
How to change the default primary key  data type when  creating a table ? I want to set it to 'bigint'

### ISSUE THREAD

**Issue by lovealan** [cakephp/phinx#1982]
[setType](https://github.com/cakephp/phinx/blob/bdd8f337fcdf24c20d0b708664a85ca9b8d5dbe2/src/Phinx/Db/Adapter/MysqlAdapter.php#L270)

**Comment by garas** [comment]
https://book.cakephp.org/phinx/0/en/migrations.html#creating-a-table

Set `'id' => false` and create `bigint` column with `addColumn`

```php
$table = $this->table('mytable', ['id' => false, 'primary_key' => ['id']])
    ->addColumn('id', 'bigint')
```
