### ISSUE TITLE
how create fulltext index with parser ngram for mysql?

### ISSUE THREAD

**Issue by du365** [cakephp/phinx#1984]
As the title , How should I create a table like below ?
a fulltext index should use ngram parser. thanks 
```
CREATE TABLE articles (
      id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
      title VARCHAR(200),
      body TEXT,
      FULLTEXT (title,body) WITH PARSER ngram
    ) ENGINE=InnoDB CHARACTER SET utf8mb4;
```

**Comment by garas** [comment]
You can run custom query if Phinx doesn't support something directly.

`$this->execute('ALTER TABLE articles ADD FULLTEXT (title,body) WITH PARSER ngram');`

**Comment by du365** [comment]
got it . thank you .
