### ISSUE TITLE
Allow addTimestamps to skip one of the columns

### ISSUE THREAD

**Issue by igorsantos07** [cakephp/phinx#1985]
In some scenarios, the developer may not want both timestamp columns. I instinctively tried to supply `false`, but it results in an error caused by an empty field name.

My suggestion is either to:
- throw an error when a non-string/null value is supplied to either field names
- threat `false` as "skip this column" (and, of course, throw an error if both are false)

I would greatly support the latter (and probably provide a PR if greenlighted) since I see that happening a lot around my current project. A simple example: a logging table never gets updated entries, so `updated_at` makes no sense. The current method to achieve that is calling `addColumn()` by hand.

**Comment by dereuromark** [comment]
This sounds useful.
A PR is sure welcome.

I agree that it only makes sense to disable one of the two, never both together.
