### ISSUE TITLE
seed:run error

### ISSUE THREAD

**Issue by Smilekoer** [cakephp/phinx#1986]
When I run the seed:run command, it prompts  No adapter was specified for environment: dev

**Comment by MasterOdin** [comment]
In the phinx configuration file, you must specify an `adapter` key that specifies what type of database phinx is interacting with. See https://book.cakephp.org/phinx/0/en/configuration.html#supported-adapters for more details on possible values.

**Comment by Smilekoer** [comment]
> In the phinx configuration file, you must specify an `adapter` key that specifies what type of database phinx is interacting with. See https://book.cakephp.org/phinx/0/en/configuration.html#supported-adapters for more details on possible values.

I have set up the adapter, I reinstalled the composer package, and it works now, thank you very much
