### ISSUE TITLE
Cannot define the display width for mediumints with MysqlAdapter

### ISSUE THREAD

**Issue by yohanleafheart** [cakephp/phinx#1996]
Greetings all, 

There is a bug/missing implementation on treating `mediumint(n)` for the MysqlAdapter. If you go to `phinx/src/Phinx/Db/Adapter/MysqlAdapter.php:1005`, you will see on the case statements that there are handles for tiny,small and bigints, so that you can specify the limit, and it will write the query as, for example, `tinyint(2)`. This works for all special mysql types, except `mediumint`.

The fix appears to be easy, just add another case statement and a procedure for when we don't pass the limit (mediumint is the only one with a value on the `$limit` array.

**Comment by dereuromark** [comment]
Are you willing to make a PR here.

**Comment by yohanleafheart** [comment]
Hey dereu, I am. I will make the change and do a pull request
