### ISSUE TITLE
Using seeds for default data

### ISSUE THREAD

**Issue by yohanleafheart** [cakephp/phinx#2003]
Greetings all,

When using seeds to populate a data base, the only method that is show is the insert to insert new data. In my case, I have a range of rows that are default and  if, for some reason it was changed on the client, I need to revert to the previous one. In other words, I would like to have a replace method for data that could be called on the seeds.

For now I'm using a query and calling it by hand with execute, but it is not ideal. Is there a chance this implemented? If I were to make a pull request for it, could you give me a tip on where I should make changes? The previous PR I did was much easier to locate and change/validate

**Comment by AdrienPoupa** [comment]
Maybe you could use this? https://github.com/cakephp/phinx/pull/1939

**Comment by yohanleafheart** [comment]
Thank you, that indeed sounds like something we can use.
