### ISSUE TITLE
addTimestamps(null, false) per documentation is not in sync with the latest production release

### ISSUE THREAD

**Issue by sinkaszab** [cakephp/phinx#2010]
Documentation for `0.12.7` says:
```php
// Only add the created_at column to the table
$table = $this->table('books')->addTimestamps(null, false);
```
[Current documentation](https://book.cakephp.org/phinx/0/en/migrations.html)

But if you pass `false`, it will be coerced to an empty string and migration fails, because MySQL will not accept empty string as column name.

`false === null ? 'updated_at' : false`

php > var_dump((string) false);
php shell code:1:
string(0) ""

**is:** [The problematic expression](https://github.com/cakephp/phinx/blob/0.12.7/src/Phinx/Db/Table.php#L544)
**should be:** [The correct implementation per the documentation](https://github.com/cakephp/phinx/blob/c9fb2a7f3465189d02c44383f12c65919416e83c/src/Phinx/Db/Table.php#L533)

`dev-master` version on Packagist includes the right code to match the documentation.

**Comment by MasterOdin** [comment]
@markstory is it possible to turn off auto-publishing of documentation from master, and only push on new releases? Or should the workflow be amended so that all work goes into a `dev` branch and then only push to `master` when a new release is cut? Feels like this is not the first time something like this has happened.

**Comment by MasterOdin** [comment]
Additionally, @dereuromark should a new 0.12.8 release but cut with the latest stuff on master?

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/releases/tag/0.12.8

**Comment by markstory** [comment]
> is it possible to turn off auto-publishing of documentation from master, and only push on new releases? 

It is. I can make docs build only on tags publish if you'd prefer that.

**Comment by sinkaszab** [comment]
Release `0.12.8` works as expected. Thanks for the quick release!

Documentation per tags (versions) would be very nice to have btw.

**Comment by MasterOdin** [comment]
Yeah @markstory, I think that would be preferable. There's not really many PRs that update the docs site to target prior releases compared to the number of changes that are tied to an upcoming release.

**Comment by othercorey** [comment]
> It is. I can make docs build only on tags publish if you'd prefer that.

We do want to verify doc commits build, but only want to publish on tag pushes, right?

**Comment by markstory** [comment]
Ok. Going forward the phinx docs will only redeploy when new tags are published.

**Comment by MasterOdin** [comment]
How are the docs built? How would one tell if the docs are failing to build before making a release?

**Comment by markstory** [comment]
The docs get built and deployed by Jenkins. The docker file in this repo is used to build the documentation. We could add a CI task to build the docs so problems could be caught when changes are made.

I can put that together if you would like.
