### ISSUE TITLE
0.13 release

### ISSUE THREAD

**Issue by dereuromark** [cakephp/phinx#2029]
Prep:

- [ ] 0.13 regression/compatibility test as `dev-... as 0.12` inside https://github.com/cakephp/migrations run
- [ ] Creating release notes and possible migration guide/info
- [x] Making sure master of 0.12 is released and merged upstream
- [ ] Merging to master as new 0.13 and tag as such

**Comment by MasterOdin** [comment]
At this point, I'd like to go ahead and just release 0.13.0 and not block on cakephp/migrations. Not having it be released and the primary branch to work from is definitely affecting my mood to work on this library. It's easy enough to make patch releases if there's something that ends up needing to be changed to make it work with `cakephp/migrations` with the BC stuff, or we can always still backport whatever to 0.12.0 for the time being.

**Comment by dereuromark** [comment]
Shall we do the 0.13 release then now?
Best to merge the branch to master IMO
I will before make a 0.12 branch of sorts to keep the old one in case we need to make bugfixes

**Comment by MasterOdin** [comment]
The latest commit on 0.x has already gone out in a release, so it would now just be a matter of landing 0.next onto the 0.x branch, and then making a 0.13 release. Similar to the 0.11.x branch, I'll make a 0.12.x branch and we can use that to make new 0.12.x releases as needed, though hopefully the transition to 0.13 is not so bad to require that.

Unless there's any objections, I can handle doing this during this upcoming week or so.

**Comment by dereuromark** [comment]
I merged 0.next into 0.x, we can now tag our stable major release (0.13)
Do we have a changelog already as draft?

**Comment by MasterOdin** [comment]
I am (slowly) working on a changelog / migration guide on my local computer. I can migrate these to a draft release and work from there.

**Comment by MasterOdin** [comment]
@dereuromark Please let me know what you think of https://github.com/cakephp/phinx/releases/tag/untagged-1e6e4f75442d6c939cf5.

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/releases/tag/0.13.0
