### ISSUE TITLE
Export migrations to SQL file

### ISSUE THREAD

**Issue by jruedaq** [cakephp/phinx#2058]
I don't have acces to direct connection on a database but i have acces to phpmyadmin and execute commands, is possible export the migrations on sql file ?

**Comment by dereuromark** [comment]
You can also use mysqldump or alike, of course.

**Comment by MasterOdin** [comment]
You should also be able to do `phinx migrate --dry-run --no-info` to get an output of just the SQL statements for migrations that you could save to a file.
