### ISSUE TITLE
Add a "clean" command to remove **MISSING** migrations from the phinxlog table

### ISSUE THREAD

**Issue by saada** [cakephp/phinx#206]
I'm proposing a "phinx clean" command that would basically find and remove all **MISSING** migrations from the `phinxlog` table. This happens when you delete a migration FILE after it was added to the database.

**Comment by zvaehn** [comment]
this may help:
1. check your database for a table called `phinxlog`.
2. remove the `** MISSING **` columns.

**Comment by rquadling** [comment]
Take a look at using my breakpoint pull request (https://github.com/robmorgan/phinx/issues/494 https://github.com/robmorgan/phinx/pull/497).

My team and I use this for multi-branch development. Switching between branches requires a ``vendor/bin/phinx rollback -t 0`` to rollback to the last breakpoint, which is set whenever master is deployed and the migrations migrated.

**Comment by joelperry93** [comment]
I've also been having troubles with switching branch to one where newer migrations do not exist. I need to rollback the migrations to the state of the branch I've switched to. Has anyone got a solution for this?

All I can think of is that it'd need to store the 'down' SQL into the migrations table every time you migrate up. That way, when the migration files disappear, we can figure out which migrations are missing (from the database table) and run the 'down' SQL in order. 

My use case is that I'm switching between branches that are further along than other branches, and I'd like to rollback automatically for the branch that I've changed to.

**Comment by saada** [comment]
whatever we do, it should perhaps be designed with git hooks in mind. Things like [post-checkout](https://git-scm.com/docs/githooks#_post_checkout) so that phinx can run the proper commands automagically. We'd have to do some diffing between migrations in previous branch vs current branch and then do like @joelperry93 mentioned. Rollback any missing migrations in current branch vs previous branch.
