### ISSUE TITLE
Add database locking

### ISSUE THREAD

**Issue by martinssipenko** [cakephp/phinx#207]
Would it be possible to add a database locking feature, so that in case migration is ran from two instances, that share same database, only one process is ran, other should either exit or wait while first one completes.

I image this could be done by locking sql table, but now all database systems will support that. Another option would be to insert some row in migration table before running first migration, and remove after last one is complete, then we could check for existence of this entry, in case two processes are ran at the same time.

**Comment by lgandras** [comment]
@robmorgan Hi, a bit late, but did you try with https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_get-lock?

**Comment by robmorgan** [comment]
Hi @lgandras, no I never pursued this request any further. See my comment above: https://github.com/cakephp/phinx/issues/207#issuecomment-39185918.

The main reason again is I don't see it as a good approach to have multiple instances or servers trying to migrate the same database at the same time. If people were to scale their servers horizontally, they would simply add further pressure to their database. My suggestion is the same as before - invest in and consider modifying your deployment process to run migrations from a single server.

**Comment by martinssipenko** [comment]
My strategy is not to deploy to instances one by one, so first runs migrations and on further instances they are already ran.
