### ISSUE TITLE
Identity Column support for PostgreSQL

### ISSUE THREAD

**Issue by romanzks** [cakephp/phinx#2070]
It would be great to be able to create tables with an **Identity Column**.

The **old** PostgreSQL approach for creating identifiers:
```
CREATE TABLE test_old (
    id serial PRIMARY KEY,
    payload text
);
```
The **new** PostgreSQL approach for creating identifiers:
```
CREATE TABLE test_new (
    id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    payload text
);
```

**Comment by ajibarra** [comment]
@romanzks  Resolved in MR #2085 . Pending review and merge

**Comment by swiffer** [comment]
Would be great to have this reviewed / merged

**Comment by ajibarra** [comment]
Since it has been merged already it looks the issue can be closed
