### ISSUE TITLE
How to use sqlsrv 2019?

### ISSUE THREAD

**Issue by ingLomeland** [cakephp/phinx#2093]
Hi,

using docker with mssql image _mcr.microsoft.com/mssql/server:2019-latest_

how to set up phinx with _TrustServerCertificate=true_ ?

Getting this error when trying to migrate 
`PDOException: SQLSTATE[08001]: [Microsoft][ODBC Driver 18 for SQL Server]SSL Provider: [error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:self signed certificate] in /var/www/api/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:84`

**Comment by ingLomeland** [comment]
update: 

found the issue. _TrustServerCertificate=true_ needs to be added toSqlServerAdapter.php here

![image](https://user-images.githubusercontent.com/87584165/168838307-f44fc824-ed4f-4d51-96a2-79ab3c6f4f02.png)

@markstory

**Comment by markstory** [comment]
Sounds like you have a good amount of context on this. Any chance you'd be able to add a pull request for this change?
