### ISSUE TITLE
Relying on the static property "$defaultName"

### ISSUE THREAD

**Issue by zdenekgebauer** [cakephp/phinx#2104]
DEPRECATION: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Phinx\Console\Command\Init" class instead.

tested on PHP 8.1, phinx  version 0.12.12 installed vith composer

**Comment by dereuromark** [comment]
@MasterOdin Did we take care of this in the upcoming 0.13 already?

**Comment by MasterOdin** [comment]
This was able to be fixed in a BC way so I've put out a new 0.12 release with it. It'll also be included in the 0.13 release.

**Comment by dereuromark** [comment]
Great!
