### ISSUE TITLE
Deprecation warning in PHP 8.1 with Phinx 0.13.0

### ISSUE THREAD

**Issue by swiffer** [cakephp/phinx#2110]
<b>Deprecated</b>:  Return type of Phinx\Config\Config::offsetGet($id) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in <b>/var/www/html/elternsprechtag/vendor/robmorgan/phinx/src/Phinx/Config/Config.php</b> on line <b>510</b><br>

**Comment by MasterOdin** [comment]
Thanks for reporting this. I'm looking to put out a 0.13.1 release with this and some other fixes asap.
