### ISSUE TITLE
Cannot run with php 8.0?

### ISSUE THREAD

**Issue by paddelboot** [cakephp/phinx#2132]
My client's server runs php 8.0, after updating phinx from an older version (~0.10) I always get the error:

    ./vendor/bin/phinx create UtilityProvider
    Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

If I do a `composer show --tree` I indeed see that even older versions of phinx seem to depend on php 8.1 now because of a symfony package:

    robmorgan/phinx 0.10.8
    [...]
    └──symfony/deprecation-contracts ^2.1|^3
            └──php >=8.1

I don't quite understand, does this mean that even phinx 0.10.x can only be run on php >= 8.1? Right now it means that I cannot create migrations.

**Comment by garas** [comment]
You've installed Composer packages using PHP 8.1, so it chose to install `symfony/deprecation-contracts 3.0`. With PHP 8.0, it would install version 2.5.

Use 8.0 when installing Composer packages, or add this to `composer.json` to tell Composer what PHP version to use when deciding what package version to install:
```json
"config": {
    "platform": {
        "php": "8.0.0"
     }
}
```

**Comment by paddelboot** [comment]
Yes, I am using a composer docker image which always uses the latest php version apparently. I understand that this is not a Phinx issue, so thanks.
