### ISSUE TITLE
Setting a value for a column fails when we try to pass a string as values

### ISSUE THREAD

**Issue by AlekseiMaryasov** [cakephp/phinx#2139]
PHP 7.3
Invalid type cast. When the value is a string.
Example:
```
...
->addColumn('orderExample', 'enum', ['values' => 'first, second', 'default' => 'first'])
...
```
`$values = 'first, second';`
https://github.com/cakephp/phinx/blob/50585ced02cd53a7fc326a728d00c38c5cee43f5/src/Phinx/Db/Table/Column.php#L632
The result is the string `'Array'`.

Thanks!

**Comment by dereuromark** [comment]
Can you check if https://github.com/cakephp/phinx/pull/2140 solves it?
That was a stupid mistake done by trying to get PHPStan green I guess.
