### ISSUE TITLE
Using Literal for creating virtual columns throws error on MariaDB

### ISSUE THREAD

**Issue by oskarkregar** [cakephp/phinx#2157]
When using Literal class to create a virtual column in MariaDB like so:
``` 
$this->table['imaginary_table']->addColumn('imaginary_column', Literal::from("varchar(30) COLLATE utf8mb4_general_ci GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`json_column`, '$.json_value'))) VIRTUAL"));
```

it throws MySQL error 
```
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NOT NULL
```
as `NOT NULL` is not allowed after creation of virtual column. `NOT NULL` is by default added on https://github.com/cakephp/phinx/blob/343645c64bcba1327f706dd6a3de5bca8bdb2ae6/src/Phinx/Db/Adapter/MysqlAdapter.php#L1365
Virtual column is set as `NULL` in MariaDB as default and cannot be changed so also if create statement is rewritten to:
``` 
$this->table['imaginary_table']->addColumn('imaginary_column', Literal::from("varchar(30) COLLATE utf8mb4_general_ci GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(`json_column`, '$.json_value'))) VIRTUAL", [
    'null' => true
]));
```
note `['null' => true]` as the option, it returns an error of
```
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL
```

I suggest rewriting: https://github.com/cakephp/phinx/blob/343645c64bcba1327f706dd6a3de5bca8bdb2ae6/src/Phinx/Db/Adapter/MysqlAdapter.php#L1365
to:
```
if (!($column->getType() instanceof Literal) || strpos($this->getConnection()->getAttribute(PDO::ATTR_SERVER_VERSION), "MariaDB") === false) {
    $def .= $column->isNull() ? ' NULL' : ' NOT NULL';
}
```

Tested on MariaDB and MySQL and works as expected.

Any thoughts?

Regards, Oskar

**Comment by dereuromark** [comment]
Feel free to make a PR here with suggested changes

**Comment by oskarkregar** [comment]
#2158 PR for the issue

**Comment by dereuromark** [comment]
PR open for discussion, please add the explanations there in the opening comment.
