### ISSUE TITLE
Composer/Packagist wrong branch?

### ISSUE THREAD

**Issue by rikgirbes** [cakephp/phinx#2164]
When installing through composer/packagist with version number 0.13.3, it apparently uses the `cake5` branch.
Which does not have all the latest commits.
For now im using 0.x-dev in composer.json.. just to get the latest changes..

Is this intended this way? Seems strange to me.

**Comment by dereuromark** [comment]
We need to use semantic branch name and removing branch aliasing. 
I will look into it

**Comment by dereuromark** [comment]
I removed that branch, the 1.x one should be used instead.

**Comment by rikgirbes** [comment]
1.x still is 7 commits behind. missing for example #1810 (https://github.com/cakephp/phinx/commit/be5f9005c0ee1a8c0d40ea56ade69670b819dc66)

Are we waiting for a new release?
If so, I have to use 0.x for now, until this is released.

**Comment by MasterOdin** [comment]
You will want to keep using the 0.x releases for now. There is not yet an expected release date for a 1.x release.

**Comment by rikgirbes** [comment]
Thanks!
