### ISSUE TITLE
How To Reuse Phinx's Database Connection In Other PHP Scripts?

### ISSUE THREAD

**Issue by tyfai** [cakephp/phinx#2187]
Hi,

How do I reuse Phinx's database connection in other PHP scripts?

For example:

* I've got Phinx set up and working well
* I run migrations via the CLI and they execute correctly
* Now I need to create a tiny public facing PHP script which sits in another directory
* In that PHP script I just need to make a database connection and output a list of tables as JSON
* It seems overkill to import an ORM (like Eloquent) to do this
* Phinx is already able to connect to the database... can I reuse its connection in another PHP script?

I know Phinx has a database connection class somewhere inside it which can do what I want (because I can use the `fetchAll()` and `table()` methods when writing migrations). But how do I access/instantiate it?

I can see I need to get an `Adapter` and insert that into the `Table` class? Am I on the right track?

Thanks! :)

**Comment by MasterOdin** [comment]
If you wanted to reuse phinx internals for getting a connection, then you would probably be best served by loading the options via a `Config::from*` method (e.g. `Config::fromYaml`) and then pass that into a new `Environment` object, and then use `$env->getAdapter()` to get the adapter, and then you could then run direct queries against that.

However, much easier would probably be to make use of the fact you can pass a `PDO` object for the connection in the configuration file (see first example in https://book.cakephp.org/phinx/0/en/configuration.html), and then you'd just have a shared file that sets up that PDO object you'd use for both phinx and your application.

**Comment by tyfai** [comment]
Excellent advice! Thank you, I've got this working now. :)

Here's my solution in case anyone else stumbles across this issue:

```
use Phinx\Config\Config;
use Phinx\Migration\Manager\Environment;
use PDO;

// $config = Config::fromYaml(__DIR__ . "/../phinx.yml");
// $config = Config::fromJson(__DIR__ . "/../phinx.json");
$config = Config::fromPhp(__DIR__ . "/../phinx.php");

$environmentName = $config->getDefaultEnvironment();
$environment = new Environment($environmentName, $config->getEnvironment($environmentName));
$pdo = $environment->getAdapter()->getConnection();

$statement = $pdo->prepare("SELECT name FROM sqlite_master WHERE type = \"table\";");
$statement->execute();
$rows = $statement->fetchAll(PDO::FETCH_ASSOC);
```
