### ISSUE TITLE
Write a Doctrine DBAL adapter

### ISSUE THREAD

**Issue by robmorgan** [cakephp/phinx#219]

**Comment by antonienko** [comment]
Maybe here is not the best place to post this, but since is about doctrine integration...

What I find that Phinx is lacking (maybe I didn't see it and you have plans for adding it) is the ability to auto-generate the migrations code (sort of what [doctrine migrations do with ./doctrine migrations:diff](http://docs.doctrine-project.org/projects/doctrine-migrations/en/latest/reference/generating_migrations.html))

Is there any plans to do something like that in the future?

**Comment by fkrauthan** [comment]
Yeah the migrations:diff command for phinx would be amazing. Just spend a couple of hours searching if something like that exists.

**Comment by TomasVotruba** [comment]
What's the best solution at moment?

**Comment by hypeJunction** [comment]
I think I came here too late after trying and failing miserably. I am trying to get in-memory sqlite going for testing purposes and for that to work I would need to have a shared connection between Phinx and the app which already uses DBAL (just as a PDO wrapper). So, when I am running Phinx without `connection` specified everything goes smoothly, but when I tried to inject wrapped DBAL `connection` into Phinx things went to hell - I end up with all kinds of weird issues, from duplicate indexes to SQL syntax errors.

**Comment by lorenzo** [comment]
@hypeJunction have you tried doing the opposite? Inject the PDO object into the Doctrine Dbal connection

**Comment by Blackskyliner** [comment]
You can just inject the PDO Object used by Doctrine

`$doctrine->getConnection()->getWrappedConnection()`

This way you will get a `Doctrine\DBAL\Driver\PDOConnection` which extends `\PDO` an you are good to go.

Full Example for a phinx configuration.php:
```
$connection = Doctrine\DBAL\DriverManager::getConnection(['url' => 'mysql://root:root@localhost/mydb?charset=UTF8']);

return [
    'environments' => [
        'default_database' => "local",
        'local' => [
            // Database name
            'name' => $pdo->query('select database()')->fetchColumn(),
            'connection' => $connection->getWrappedConnection(),
        ],
    ],
];

**Comment by dereuromark** [comment]
Closing as this has become stale and no one was interested in providing a pull request. If someone wants to PR it, go ahead.
