### ISSUE TITLE
PHP Deprecated (php version 8.1.15)

### ISSUE THREAD

**Issue by jiangjiangdev** [cakephp/phinx#2194]
when I run this command "vendor/bin/phinx init .", I got a warning: 
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ***/vendor/symfony/console/Helper/HelperSet.php on line 104

**Comment by garas** [comment]
What version of `symfony/console` is installed? Check with `composer info`.

Symfony has fixed this issue in v4.4.30/v5.3.7/v6.0.0, Phinx requires `^3.4|^4.0|^5.0|^6.0`, so it should be able install fixed version, unless some other dependency is blocking newer version. Try `composer update`.

**Comment by jiangjiangdev** [comment]
My Symfony version:
symfony/console               v3.4.47 Symfony Console Component

composer.json:
```
"require": {
    "php": ">=7.2",
    "workerman/webman-framework": "^1.5.0",
    "monolog/monolog": "^2.0",
    "robmorgan/phinx": "^0.11.7",
    "illuminate/database": "^10.9",
    "vlucas/phpdotenv": "^5.5",
    "psr/container": "^2.0",
    "illuminate/redis": "^10.9",
    "symfony/cache": "^6.2",
    "webman/blade": "^1.5"
},
```

**Comment by garas** [comment]
Phinx 0.11 requires symfony/console ^3.4|^4.0|^5.0.

Upgrade Phinx to 0.12 or 0.13 to allow install symfony/console 6.0.

Other versions of symfony/console are blocked because they indirectly require PHP 7.

**Comment by jiangjiangdev** [comment]
Thanks! It works!
