### ISSUE TITLE
run "vendor/bin/phinx create MyFirstMigration " get wrong

### ISSUE THREAD

**Issue by zhaofenghao** [cakephp/phinx#2215]
>phinx create MyFirstMigration
Phinx by CakePHP - https://phinx.org.

PHP Fatal error:  Uncaught Error: Call to undefined method Phinx\Util\Util::relativePath() in D:\work\tp5\vendor\robmorgan\phinx\src\Phinx\Console\Command\AbstractCommand.php:292

**Comment by zhaofenghao** [comment]
> > phinx create MyFirstMigration
> > Phinx by CakePHP - https://phinx.org.
> 
> PHP Fatal error: Uncaught Error: Call to undefined method Phinx\Util\Util::relativePath() in D:\work\tp5\vendor\robmorgan\phinx\src\Phinx\Console\Command\AbstractCommand.php:292

**Comment by liuhuapiaoyuan** [comment]
How did you handle this issue?
