### ISSUE TITLE
What happened to v2.0.x releases?

### ISSUE THREAD

**Issue by PabloKowalczyk** [cakephp/phinx#2221]
Hello, there were `v2.0.0`, `v2.0.1` and `v2.0.2` releases ([still available on Packagist](https://packagist.org/packages/robmorgan/phinx#2.0.2)), what happened to them, were they deleted? Should I downgrade to `v0.15`?

**Comment by othercorey** [comment]
There was an accidental release that caused confusion. I believe @MasterOdin will add this to the release notes.

Basically, the latest release is `0.15` and includes all the changes from the short-lived `2.0` release along with some other fixes and changes that were meant to be included.

**Comment by MasterOdin** [comment]
I've added a note to the [release notes](https://github.com/cakephp/phinx/releases/tag/0.15.0) indicating that the releases were deleted. Given that we still have breaking changes on just regular functionality, we are sticking with `0.x` releases for the time being.

We are working to remove the tags from packagist as well.

**Comment by PabloKowalczyk** [comment]
OK, thanks for clarification.

**Comment by dereuromark** [comment]
The 2.x tags have now been removed on packagist it seems.

**Comment by mbrodala** [comment]
Which is bad IMO. You should never delete tags since this causes a chain of issues. E.g. we did upgrade and now Compose is unable to install the package.

**Comment by MasterOdin** [comment]
I would agree that it took too long for the version to be wiped from composer + other places, though I disagree that it's a mistake to never delete tags that were mistakenly created, especially around major versions. I am sorry it happened, and I'd like to believe it won't happen again, but software development is a human endeavor and to err is human after all.

**Comment by othercorey** [comment]
I believe packagist removed the deleted releases the same way it removes deleted branches. There in a delay between the github change and the branch being removed from their servers.

**Comment by othercorey** [comment]
> Which is bad IMO. You should never delete tags since this causes a chain of issues. E.g. we did upgrade and now Compose is unable to install the package.

We apologize for the pain this is causing you. Unfortunately, the fix was delayed as we were missing changes meant to be in the original release and this is the fallout.

**Comment by mbrodala** [comment]
Of course, mistakes happen, we are all human after all. Still this could have been handled differently depending on the further plans / roadmap. E.g. continue in 2.x with non-breaking changes and raise to 3.x, 4.x, etc. on breaking changes. There is no problem raising the major version, that's what it is meant for.

Aside from that I'd be more curious why this wasn't 1.x instead. Was this intentionally skipped?

**Comment by othercorey** [comment]
> Aside from that I'd be more curious why this wasn't 1.x instead. Was this intentionally skipped?

The 2.0 release was a mistake, there was no intention to skip 1.0 with it. @MasterOdin would like to release 1.0 with a stable version sometime in the future, but these changes weren't ready for that.

**Comment by mbrodala** [comment]
OK, thanks for the explanation. :+1:
