### ISSUE TITLE
migration --fake command not working

### ISSUE THREAD

**Issue by demmmmios** [cakephp/phinx#2229]
Hi i found out that after update to new version --fake option for migration command is not working. The issue is here https://github.com/cakephp/phinx/commit/eccc64b53e585608da8ac073a2a4728447e6d98b because it was moved from fake condition. Is this intended or bug?

**Comment by MasterOdin** [comment]
Yup, definitely a bug, I think can narrow the `if (!$fake)` check to be just around running the migration, fine to do the transaction stuff regardless if we're running the migration or just inserting a log of it. Will need to think about writing up a test for this so we can catch this sort of regression. Thanks for reporting it.

**Comment by dereuromark** [comment]
@demmmmios Do you want to make a PR here? We can fast track the merge and release here.
