### ISSUE TITLE
Are tables with SYSTEM VERSIONING (available in MariaDB v10.3+) supported?

### ISSUE THREAD

**Issue by mp-improvement-it** [cakephp/phinx#2244]
I am aware SYSTEM VERSIONING is not entirely database agnostic across different databases. 

I could not find any mention of it in your documentation. Nor could I find it in your source code. Is it possible to create tables with SYSTEM VERSIONING using your migrations? If not, is there any intention of including this over time? Thanks.

**Comment by dereuromark** [comment]
I dont think that is within the scope.
