### ISSUE TITLE
Support Symfony Console 7.0

### ISSUE THREAD

**Issue by PAXANDDOS** [cakephp/phinx#2250]
The package now conflicts with apps running Symfony Console 7.0.

I see a commit from two weeks ago that resolves this issue (https://github.com/cakephp/phinx/commit/a81c0846256fb9131c4c06d119fbff9d01cbc198), basically just updating the composer file... 
When can we expect the release?

**Comment by dereuromark** [comment]
Shortly,
You can use 0.x-dev until then.

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/releases/tag/0.15.5
