### ISSUE TITLE
Use the Symfony Table Class in the Migration Manager

### ISSUE THREAD

**Issue by robmorgan** [cakephp/phinx#231]
http://symfony.com/doc/master/components/console/helpers/tablehelper.html

**Comment by rquadling** [comment]
One potential issue to be aware of is that the table will only be displayed once ``render()`` is called. So if there is an issue before that point, we will lose the output.

What other benefits exist for this?

**Comment by robmorgan** [comment]
Render() can calculate all the column widths so we don't have to do it all manually. Also the Manager class can start becoming less concerned with the presentation.

**Comment by rquadling** [comment]
I see. Good points.

**Comment by dereuromark** [comment]
@ anyone interested in continuing here? Otherwise we can close.
