### ISSUE TITLE
ErrorException: Undefined array key "`adapter`" in AbstractCommand.php:470

### ISSUE THREAD

**Issue by zeleznypa** [cakephp/phinx#2311]
https://github.com/cakephp/phinx/blame/2e9d7d2fd6aa81187bc1c09892d0a9a6e321765b/src/Phinx/Console/Command/AbstractCommand.php#L470

When the Pninx environment is defined via the "connection" like in the https://book.cakephp.org/phinx/0/en/configuration.html, the "adapter" is not a part of the `$envOptions`, so it fails on error:

```
ErrorException: Undefined array key "`adapter`" in /opt/srv/super-secret-project/vendor/robmorgan/phinx/src/Phinx/Console/Command/AbstractCommand.php:470
```

**Comment by MasterOdin** [comment]
Thanks for reporting the issue. I've released [0.16.4](https://github.com/cakephp/phinx/releases/tag/0.16.4) that has a fix for this bug.
