### ISSUE TITLE
PSQL - Issue with Phinx if migration_table is not in the public schema

### ISSUE THREAD

**Issue by JulienChavee** [cakephp/phinx#2315]
Hello,

Since #2309 there is an issue with Phinx if the migration_table is not in the default public schema.
Currently we specify the schema in the configuration, but as the class variable in the PostgresAdapter is assigned after the parent::setOptions($options), and as the verification if the table exists is done in this function as well, when it resolves the schema name it uses the default one, instead of taking the one from the configuration.

**Comment by MasterOdin** [comment]
Thanks for the bug report! This has been fixed in the newly released [`0.16.5`](https://github.com/cakephp/phinx/releases/tag/0.16.5).
