### ISSUE TITLE
Consider collision avoidance on create

### ISSUE THREAD

**Issue by dereuromark** [cakephp/phinx#2324]
https://github.com/cakephp/phinx/blob/0.x/src/Phinx/Console/Command/Create.php
You could apply sth similar here we currently evaluate for Migrations:
https://github.com/cakephp/migrations/pull/773

When you generate multiple ones, this will otherwise create exceptions when reading/using.

**Comment by MasterOdin** [comment]
Interesting bug, not sure how often it'd come up before now. I think that my preferred solution would be to take the timestamp, and if there's an existing one, then just increment it by 1 until we hit a timestamp that's valid. This would be BC, and that I don't think anyone _really_ cares about the timestamp prefix value beyond it just enforcing the right numerical order of files in the file tree / migration list.

**Comment by dereuromark** [comment]
Isnt that exactly how I fixed it in the linked PR? :)

**Comment by MasterOdin** [comment]
Hah, for some reason I swear I thought that your PR was appending an incrementing `##` to the end of the timestamp if there was a collision. My bad, yeah, that looks pretty perfect to port into phinx as well.
