### ISSUE TITLE
Add packing to .phar, to install system-wide

### ISSUE THREAD

**Issue by mcd-php** [cakephp/phinx#242]

**Comment by robmorgan** [comment]
I'm confused, whats packing?

**Comment by KingCrunch** [comment]
It would be useful to have single phar-file as standalone tool. For example habe a look at [Box](https://github.com/box-project/box2). This would decouple this tool from the projects dependencies.

**Comment by robmorgan** [comment]
@KingCrunch you can easily produce a PHAR using box. See the README: https://github.com/robmorgan/phinx#as-a-phar

**Comment by lukecyca** [comment]
+1 for having a PHAR of the latest release available for download. This would make it much easier to install Phinx system-wide from Ansible (or any automated server provisioning system).

I want to install Phinx as a system-wide standalone utility (as I do git) and not as a project dependency (as using composer would imply).

**Comment by dereuromark** [comment]
Seems like there is no interest here to continue.

**Comment by dkreuer** [comment]
Is there any chance that phinx will be published as phar on release tags? Would help to install it via phive (phar.io).

**Comment by lorenzo** [comment]
@dkreuer I would appreciate help for having this as part of our travis pipeline or something similar. Is this something you can help with?

**Comment by dkreuer** [comment]
Sure, I can try.

**Comment by lorenzo** [comment]
@dkreuer thanks! We have some instructions in our readme to build the phar file, so maybe you can add those steps to the travis build and make it deploy the result on tags.
