### ISSUE TITLE
Default value now() for timestamp

### ISSUE THREAD

**Issue by sooners87** [cakephp/phinx#261]
Like to add a default value of now() to timestamp column. But could not do so.

**Comment by HughbertD** [comment]
I've just run into this issue and ended up here: http://stackoverflow.com/questions/168736/how-do-you-set-a-default-value-for-a-mysql-datetime-column

In my case the issue was due to being on MySQL < 5.6.5

To get around this I used a TIMESTAMP column instead:

```
public function change()
    {
        $table = $this->table('tablename');
        $table
            ->addColumn('columnName', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->save();
    }
```

Which worked as expected :)

**Comment by t1gor** [comment]
> In my case the issue was due to being on MySQL < 5.6.5
> 
> To get around this I used a TIMESTAMP column instead:
> ...
> Which worked as expected :)

Yeah, the idea was to have a `date` or `datetime` column, not timestamp. But still - this is not a phinx issue, MySQL just can't do that.
