### ISSUE TITLE
Support for primary key

### ISSUE THREAD

**Issue by djordje** [cakephp/phinx#28]
Support for defining custom primary key may be useful in some cases.

Currently phinx add ìd` column as auto increment primary key.
It should be possible to override this behavior, so we can create tables w/out primary key, w/out auto increment.

**Comment by glensc** [comment]
`'id'=>false,'primary_key' => 'foo'` does not work as expected.

it indeed creates primary key but the `AUTO_INCRMENT` is lost.

```php
        $this->table('api_token', ['id' => false, 'primary_key' => ['apt_id']])
            ->addColumn('apt_id', 'integer', ['length' => 10, 'signed' => false])
```

this creates: 

```sql

CREATE TABLE `api_token` (
  `apt_id` int(10) unsigned NOT NULL,
...
  PRIMARY KEY (`apt_id`),
) ENGINE=MyISAM DEFAULT CHARSET=utf8
```

but i need it to be:

```sql

CREATE TABLE `api_token` (
  `apt_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
...
  PRIMARY KEY (`apt_id`),
) ENGINE=MyISAM DEFAULT CHARSET=utf8
```

**Comment by glensc** [comment]
so far i've solved the problem by finding primary key and adding `identity` flag to it so `AUTO_INCREMENT` would be added to DDL.

```php

    public function change()
    {
        $table = $this->table('api_token', ['id' => false, 'primary_key' => 'apt_id'])
            ->addColumn('apt_id', 'integer', ['length' => 10, 'signed' => false]);
        $this->getPk($table)->setIdentity(true);
        $table->create();
    }

    /**
     * Get Primary Key column from Pending Table Operations.
     * Hack for AUTO_INCREMENT being lost when defining custom Primary Key column
     *
     * @link https://github.com/robmorgan/phinx/issues/28#issuecomment-298693426
     * @param Table $table
     * @return Table\Column
     */
    protected function getPk(Table $table)
    {
        $options = $table->getOptions();
        if (!isset($options['primary_key'])) {
            throw new LogicException('primary_key column required');
        }

        $name = $options['primary_key'];
        $columns = $table->getPendingColumns();
        foreach ($columns as $column) {
            if ($column->getName() == $name) {
                return $column;
            }
        }
        throw new LogicException('primary_key column not found');
    }

```

**Comment by glensc** [comment]
`$table->getPendingColumns()` is gone, yet there's still no way to define custom primary key and have auto increment on it.

i.e the problem reported in this note: https://github.com/cakephp/phinx/issues/28#issuecomment-298693426

**Comment by MasterOdin** [comment]
I believe, you'd want to do something like:
```
$this->table('api_token', ['id' => 'apt_id', 'signed' => false])->create();
```
As a string for the `id` key will cause the adapter to fall into this branch of code:
https://github.com/cakephp/phinx/blob/76c96c851b737f93598d7ae7765a5cd2cc99ae7a/src/Phinx/Db/Adapter/MysqlAdapter.php#L232-L242

which should give you a custom named auto increment primary key column.

**Comment by glensc** [comment]
currently i kept the previous hack, but needed to hack even more because the `actions` is not accessible.

https://github.com/eventum/eventum/pull/388/commits/eb121e3d8f37cd745a613782f32b663bd6354fba

i'll check your solution next.

**Comment by glensc** [comment]
okay. it works, but result is not identical

```sql
CREATE TABLE `api_token` (
  `apt_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
```

the `int(11)` is incorrect, should be `int(10)`, but it's kind of same to mysql anyway.

**Comment by MasterOdin** [comment]
You can only specify the signed key there. You should be able to do this I believe to get what you want:
```
$this->table('api_token', ['id' => false, 'primary_key' => 'apt_id'])
    ->addColumn('apt_id', 'integer', ['limit' => 10, 'signed' => false, 'identity' => true])
    ->create();
```

**Comment by glensc** [comment]
@MasterOdin indeed. that works now as the changes are batched together. thanks!

**Comment by glensc** [comment]
i think this can be closed. at least problem i mentioned in comments is solved.
