### ISSUE TITLE
DB entry created even if migration fails

### ISSUE THREAD

**Issue by shadyb** [cakephp/phinx#280]
Hey Rob,

I have noticed that when a migration fails, it is still written to the phinxlog table; when subsequent fixes to the migration are pushed they are not applied (since phinx already thinks the migration has run when it failed). I then have to manually remove that migration entry from the database and re-run phinx.

When a migration fails, a db entry should not be created for the phinxlog table.

**Comment by mohammed-elhakim-sociomantic** [comment]
I can confirm this issue. Why was it closed?
