### ISSUE TITLE
add 'from' version support

### ISSUE THREAD

**Issue by adamski** [cakephp/phinx#283]
In our case, I needed to add support for a 'from' version, as we have a database for each client at different versions and so this way I can manually specify a start point for migrations, before that information is added to phinxlog table. I have based it on @detook schema-dump branch. 
Its at https://github.com/adamski/phinx/tree/schema-dump-from

**Comment by dereuromark** [comment]
The workaround seems to be fair enough, closing for a lack of support on this one.
