### ISSUE TITLE
Issues with custom primary key column

### ISSUE THREAD

**Issue by rchouinard** [cakephp/phinx#292]
Tested with v0.3.6 and v0.3.7, using MySQL 5.6

Documentation says this is possible:

>    $table = $this->table('followers', array('id' => 'user_id'));
>    $table->addColumn('user_id', 'integer');

However, this causes an error:

```
[PDOException]                                                               
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'user_id'
```

It appears the id column is created automatically, making the `addColumn()` call redundant. I'd say this a documentation error and call it done, however the main reason I'm doing this is to set my PK to unsigned:

```
$table = $this->table('followers', array('id' => 'user_id'));
$table->addColumn('user_id', 'integer', array('signed' => false));
```

Ideally, this would work as documented. Actually, ideally the PK would be unsigned by default.

**Comment by jmacedo** [comment]
Actually, in version v0.4.2 you have to do this:
``$table = $this->table('followers', array('id' => false, 'primary_key' => 'user_id'));``
``$table->addColumn('user_id', 'integer', array('signed' => false));``

If you want auto increment:
``$table->addColumn('user_id', 'integer', array('signed' => false, 'identity' => true));``

I agree with the issue that auto id column should be unsigned.  :+1:

**Comment by dereuromark** [comment]
We should fix the docs.
Are you able to provide a pull request with your suggested changes there?

Making auto ids unsigned sounds like an improvement that could also be PRs separately from this.
