### ISSUE TITLE
PDOException Syntax error 42000

### ISSUE THREAD

**Issue by AndreasBackx** [cakephp/phinx#307]
I'm getting the following error:

```
[PDOException]                                                                                                    
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes  
```

After trying to migrate to this migration:

```
<?php

use Phinx\Migration\AbstractMigration;

class IndexesAndLocation extends AbstractMigration {
    /**
     * Change.
     */
    public function change() {
        $storesTable = $this->table('stores');
        // 7 decimal places is precise to 11mm and should suffice
        $storesTable->addColumn('latitude', 'decimal', ['precision' => 10, 'scale' => 3])
                    ->addColumn('longitude', 'decimal', ['precision' => 10, 'scale' => 3])
                    ->addIndex(['name', 'country', 'province', 'zip_code', 'city', 'street', 'number', 'latitude', 'longitude'])
                    ->save();
    }

    /**
     * Migrate Up.
     */
    public function up() {

    }

    /**
     * Migrate Down.
     */
    public function down() {

    }
}
```

It probably is because of the multiple indexes that I'm adding.

**Comment by jeffreyroberts** [comment]
Greetings, I am wondering if we can re-open this ticket as I am only applying an index to one or two columns...

    public function change()
    {
        $table = $this->table('domains_mailto');
        $table->addIndex(['mailto_address', 'domains_host_id']);
        $table->save();

        $table = $this->table('domains_software_metas');
        $table->addIndex(['domains_host_id','meta_property']);
        $table->addIndex(['domains_host_id','meta_name']);
        $table->addIndex(['domains_host_id','meta_property','meta_name']);
        $table->save();

        $table = $this->table('domains_software_rss_feeds');
        $table->addIndex(['domains_host_id','rss_feed_url']);
        $table->save();

        $table = $this->table('domains_hosts');
        $table->addIndex(['domain_host']);
        $table->save();

        $table = $this->table('domains_software_versions');
        $table->addIndex(['software_version']);
        $table->save();

        $table = $this->table('domains_software');
        $table->addIndex(['domains_domain_id']);
        $table->save();
    }

and I am getting the following error

    Exception: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes in [/Users/jlroberts/Projects/JeffreyLRobertsCom/Dashbored/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 338]

**Comment by pmparviz** [comment]
> This can be fixed by spreading the addIndex over 2 lines:
> 
> ```
> ->addIndex(['name', 'country', 'province', 'zip_code'])
> ->addIndex(['city', 'street', 'number', 'latitude', 'longitude'])
> ```

here to say thank you 10 years later
