### ISSUE TITLE
Add a primary key on an existing table

### ISSUE THREAD

**Issue by liawlim** [cakephp/phinx#335]
Hello guys,

How we can add a primary key on an existing table ?

I try to do this but the table dont be updated :

``` php
    public function up()
    {
        $this->table('toto', array('id' => true))
            ->save();
    }
```

But Table::update() method was call and this method didn't create primary key ...

**Comment by sergejkaravajnij** [comment]
I have exactly the same task and not found any solution except using ALTER TABLE ... :(
But in this case I couldn't use _change()_ method.

**Comment by DerMika** [comment]
You should be able to create a primary key by creating an index of type "PRIMARY" just as you can create a unique key. However, the current implementation only looks at the UNIQUE type. 

I was expecting `$table->addIndex(['someId', 'someOtherId'], ['type' => 'PRIMARY'])` to work, but I found out that any index type besides 'unique' is ignored.

With that said: here is my vote for fixing this bug.

**Comment by berarma** [comment]
+1

**Comment by daniel-gomes-sociomantic** [comment]
+1

**Comment by purpleweb** [comment]
+1

**Comment by burzum** [comment]
Can we add a method `addPrimaryKey()` :)

**Comment by lorenzo** [comment]
Thats. correct. Thanks for pointing that out @djcvijic
