### ISSUE TITLE
Multiple write databases

### ISSUE THREAD

**Issue by BardiaAfshin** [cakephp/phinx#338]
In a multiple read write database environment, If you have to write databases that the migrations need to get applied to, it'd be nice to have a nested phinx yaml configuration that apply the migrations to more the one database when you kick off the migration. That is, take in the credentials for all write databases and connects and runs the valid migrations one by one.

Upon error, I'd see the migration doing a down and recovering with the proper algorithm that ensures application integrity and uptime. This will require further development as the community provides input on their requirements.

**Comment by keithy** [comment]
The library http://github.com/keithy/primo-pdo-php has this basic tools for this feature.

In this example, the migration is applied to all environments. (choices)
It is applied to a configuration which is derived from the base environment, but adds a prefix to the database name.
```
$reader = new Primo\Phinx\ConfigReader( __DIR__ . "/_fixtures/phinx.php");

$clean = true; 
foreach( $clients as $client ) 
{
  foreach( $reader->choices() as $choice )
  {
    $reader->choose($choice)->which('per-client')->atPut('%%CLIENT%%',  "$choice_$client")->create(true);
  }
}
```

```
'sqlite' => [
    'which' => [
        'per-client' => [ 
          'name' => '%%CLIENT%%'
     ]
]
```
