### ISSUE TITLE
having phinx create a database for you during init

### ISSUE THREAD

**Issue by ghost** [cakephp/phinx#345]
What's the communities thought of having phinx create the database for you during init?

The catch here is that the current process looks for a database specified in phinx.yml file before it does anything with a migration. I was originally thinking along the lines of creating a migration that encapsulates creating the database, but it looks like during phinx's current architecture that's not the case.

Thoughts?
@robmorgan

**Comment by adamski** [comment]
@ianring have a look at shema:dump branch on @detook's fork. 
I am using that to generate schema, then copy the generated schema.php and renaming it to be the first migration, just remove the phinxlog table if its there already!
