### ISSUE TITLE
Error when trying to run init 

### ISSUE THREAD

**Issue by ahmarov** [cakephp/phinx#360]
platform: windows8
trying to run: php vendor/bin/phinx init
output result:
SRC_DIR="`pwd`"
cd "`dirname "$0"`"
cd "../robmorgan/phinx/bin"
BIN_TARGET="`pwd`/phinx"
cd "$SRC_DIR"
"$BIN_TARGET" "$@"

**Comment by shadowhand** [comment]
Is this issue still ongoing, or has it been resolved?

**Comment by RQuadling** [comment]
``vendor\bin\phinx`` is the unixy shell script.
``vendor\bin\phinx.bat`` is the windows batch script.

Neither of them are PHP scripts, and so, using PHP is not going to do anything here.

If you run ``vendor\bin\phinx.bat`` and then ``SET BIN_TARGET``, what output do you get? I am expecting something like ``BIN_TARGET=C:\wamp\www\******\vendor\bin\/../robmorgan/phinx/bin/phinx``

The ``BIN_TARGET`` **is** the PHP script.

You could therefore try ``php -d error_reporting=-1 %BIN_TARGET%``. This should show the normal help screen. If not, what errors/output?

**Comment by RQuadling** [comment]
Alternatively, don't run ``php vendor\bin\phinx init``, just ``vendor\bin\phinx init``.

**Comment by avlastenok** [comment]
On windows running vendor\bin\phinx init will result in the same error result
What i found out was just go to the source instead 
vendor\robmorgan\phinx\bin\phinx 
I am on windows 8 right now this works like a charm and just setup a alias for it so you do not have to write all that every single time you want a new migrations.

**Comment by RQuadling** [comment]
@avlastenok, Ideally I'd (and probably everyone else) would like to know why your environment is not working with the default setup.

You shouldn't need to do any aliasing.

Could you try the suggestions I made in https://github.com/robmorgan/phinx/issues/360#issuecomment-68865221?

The output you are seeing in your initial question is the output of the unix shell script. Which, for the command you entered, completely appropriate. You ran the PHP interpreter with the unix script. No php exists in the script, so you get the script content as is. All exactly as expected.

But you also say that when you run ```vendor\bin\phinx init``` you get the same error. That is very odd.

Of course, you could have a borked install of phinx. Maybe worth just refreshing it.

**Comment by avlastenok** [comment]
It's rare that I work on my windows pc, normally I work on my ubuntu work station, also switched back over to that machine and everything is working as expected there.
But with the command: vendor\bin\phinx init i do get the shell output even after refreshing the installation.

**Comment by jwoodcock** [comment]
I'm running into the same issue on OSX with php 5.6.8. 

Running php vendor/bin/phinx migrate gives me the same output. I'm not running init as it's a project that has already been setup on another box. 

`vendor\bin\phinx.bat` does not exists for me, so I can not run that as mentioned in comment 68865221.

Here's what I've done:
- Cloned repo from github
- Run composer install
- Updating Phinx yml with new db connections
- Run phinx using `php vendor/bin/phinx migrate`

Running just `./vendor/bin/phinx migrate` gives me this error
`./vendor/bin/phinx: line 7: /Users/jwoodcock/code/Tandum.Api_Domain/vendor/robmorgan/phinx/bin/phinx: Permission denied`

**Comment by rquadling** [comment]
@jwoodcock, 

The ```phinx.bat``` file is JUST for windows. No one else. And not even for unixy shells running on Windows. Just windows.

Try ```sudo vendor/bin/phinx migrate```. You've got a permissions issue with your setup. 


@shadowhand Close this one as I don't think there is anything else to add.

**Comment by zhanjh** [comment]
change the last line in vendor/bin/phinx:
"php" "$BIN_TARGET" "$@"

#!/usr/bin/env sh
SRC_DIR="`pwd`"
cd "`dirname "$0"`"
cd 'vendor/robmorgan/phinx/bin'
BIN_TARGET="`pwd`/phinx"
cd "$SRC_DIR"
"php" "$BIN_TARGET" "$@"

**Comment by markushausammann** [comment]
@jwoodcock hey, (how) did you solve this? I'm getting exactly the same problem on a vagrant ubuntu box (laravel homestead) on an OSX host. I really don't get how this can be explained and I've tried lots of solutions already.

**Comment by markushausammann** [comment]
@zhanjh Changing code of the package is out of the question.

**Comment by jwoodcock** [comment]
@markushausammann I believe I did this:

```
php vendor/robmorgan/phinx/bin/phinx migrate
```

This skips the bin build and using the php phinx file directory.

**Comment by markushausammann** [comment]
@jwoodcock thanks, I did the same, works.

**Comment by jwoodcock** [comment]
:+1:

**Comment by dot5enko** [comment]
windows uses \ as a directory separator, when unix - /. so, to properly call phinx on windows you must call ` vendor\bin\phinx ` and everything would be ok

**Comment by rquadling** [comment]
Could it be the lack of a default shell defined in the environment?

For those having the problem, what is the value of `sh` for the user running phinx?

**Comment by rquadling** [comment]
@dot5enko It is always a surprise when people don't know the difference between \ and / and how PHP "helps" windows users by allowing \ and /, but not unix users. Almost more hassle than it is worth!

What documentation changes would be recommended here?

**Comment by tariquesani** [comment]
Not really a bug? Just documentation needed?
