### ISSUE TITLE
Exception with chain creating migrations has duplicate version

### ISSUE THREAD

**Issue by BardiaAfshin** [cakephp/phinx#362]
when you chain create migrations 

./bin/phix create CreateSomeTable && ./bin/phinx create AddAnotherColumnToSomeTable

you end up with duplicate timestamps and get following error

``` php
[InvalidArgumentException]
  Duplicate migration - "20141121000413_add_some_data_to_another_table.php" has the same version as "20141121000413"
```

**Comment by robmorgan** [comment]
unfortunately Phinx is too fast, if only it slept for 1.01 seconds in `create` ;)

**Comment by tariquesani** [comment]
This is a bug but we are essentially saying 'WontFix'? And it is OK to not fix this, perhaps  a note in the docs would suffice.

**Comment by markstory** [comment]
Closing as this seems like an uncommon use case and something that is not worth taking on additional complexity to solve.
