### ISSUE TITLE
Problem connecting to mysql

### ISSUE THREAD

**Issue by ghost** [cakephp/phinx#387]
I have a situation where mysql is installed and when attempting to run a migration I get InvalidArgumentException:

``` shell
  [InvalidArgumentException]
  There was a problem connecting to the database: SQLSTATE[HY000] [2002] No such file or directory
```

But I can connect to mysql find with the credentials, from command line

**Comment by karolsenami** [comment]
Hey there, I'm struggling with the same issue for all day long and I can't find a solution.
I'm on Mac OS

Here's my yaml file (sorry for the dirty paste):
`
paths:
    migrations: %%PHINX_CONFIG_DIR%%/db/migrations
    seeds: %%PHINX_CONFIG_DIR%%/db/seeds
`
`
environments:
    default_migration_table: phinxlog
    default_database: development
    production:
        adapter: mysql
        host: localhost
        name: production_db
        user: root
        pass: "
        port: 3306
        charset: utf8
`

    development:
        adapter: mysql
        host: localhost
        name: development_db
        user: root
        pass: "
        port: 3306
        charset: utf8

    testing:
        adapter: mysql
        host: localhost
        name: testing_db
        user: root
        pass: "
        port: 3306
        charset: utf8
`

Here's my Exception trace :
`Exception trace:
 () at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php:115
 Phinx\Db\Adapter\MysqlAdapter->connect() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:238
 Phinx\Db\Adapter\PdoAdapter->getConnection() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:346
 Phinx\Db\Adapter\PdoAdapter->query() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:364
 Phinx\Db\Adapter\PdoAdapter->fetchAll() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:409
 Phinx\Db\Adapter\PdoAdapter->getVersionLog() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php:238
 Phinx\Migration\Manager\Environment->getVersionLog() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:116
 Phinx\Migration\Manager->printStatus() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/src/Phinx/Console/Command/Status.php:84
 Phinx\Console\Command\Status->execute() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/symfony/console/Application.php:820
 Symfony\Component\Console\Application->doRunCommand() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/symfony/console/Application.php:187
 Symfony\Component\Console\Application->doRun() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php:83
 Phinx\Console\PhinxApplication->doRun() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/symfony/console/Application.php:118
 Symfony\Component\Console\Application->run() at /Users/maxjourd/Documents/DEV/WEB/Slim Framework/Slim-Skeleton-master/vendor/robmorgan/phinx/bin/phinx:28`

**Comment by qsricardosevero** [comment]
Hi, I had the same issue when using phinx with mysql in a separate docker container. The cause was configuring the host as localhost in the phinx env file. After changing the host to 127.0.0.1 it worked!

**Comment by jesusalive** [comment]
Be

> Hi, I had the same issue when using phinx with mysql in a separate docker container. The cause was configuring the host as localhost in the phinx env file. After changing the host to 127.0.0.1 it worked!

SO GOOOOOOOOOD. Worked for me
