### ISSUE TITLE
test style 

### ISSUE THREAD

**Issue by trilopin** [cakephp/phinx#406]
i have two ideas for testing:

**Replace assertions based in tested class methods**

``` php
public function testCreateTable()
{
        $table = new \Phinx\Db\Table('ntable', array(), $this->adapter);
        $table->addColumn('realname', 'string')
               ->addColumn('email', 'integer')
               ->save();
        $this->assertTrue($this->adapter->hasTable('ntable'));
        $this->assertTrue($this->adapter->hasColumn('ntable', 'id'));
        $this->assertTrue($this->adapter->hasColumn('ntable', 'realname'));
        $this->assertTrue($this->adapter->hasColumn('ntable', 'email'));
        $this->assertFalse($this->adapter->hasColumn('ntable', 'address'));
}
```

This test check CreateTable feature but use hasTable and hasColumn for assertions. 
If hasColumn method break, all tests with assert like those will fail (plus hasColumn itself) and test results wll be more complicated to read.

In the other hand, rewrite tests with pure sql for assertions is more complex to mantain...

**Make some unit tests**

Current tests are functional, execute code from start to end and assert results.
It will be nice have some unit tests with database mocking:
- this tests will be faster
- mocking real db, expecting generated sql -> it can be readed as sql generation documentation  

I say this as a proposal, not an attack of current tests.
I can help in both ideas (with mysql at least) 

what do you think?

Thanks

**Comment by shadowhand** [comment]
@trilopin are you going to submit a pull request with these new tests? :)

**Comment by trilopin** [comment]
@shadowhand just created it, i was waiting for some review but is better to do in pr.
