### ISSUE TITLE
Provide auto-update during the creation of a migration

### ISSUE THREAD

**Issue by weaintplastic** [cakephp/phinx#408]
I don't know what the best workflow for the following scenario is, so please don't hesitate to educate me.

Imagine you create a migration file. Usually you already performed all the migration statements on your database before writing your migrations, right? Setting the state of your database up to date (according to `phinxlog`) you only have the option to run `phinx migrate`. Depending on your migration file this can cause issues or wrong results, since you are performing the same changes through Phinx which you've already applied before. Currently I see three ways out of this dilemma:
1. Create save migrations
   Add statements that check if your changes have already been applied to the related tables and if so, skip the process of executing these changes again. (Could be very complex)
2. Rollback by hand
   Undo your manual changes in your database in order to apply them again during `phinx migrate`` (May also be very complex and time consuming)
3. Upgrade by hand
   Add the created migration version to the `phinxlog` table by hand (Feels a little bit dirty)

Since I don't like both of these solutions I want to suggest the following feature:

What if `phinx create` provides an additional flag in order to control, if the changes described in the created migration file need to be performed on your database instance (thats the behavoir right now and should be default) or if theses changes are already applied and therefore the 'phinxlog` can be updated to the new version without executing the migration.

This is maybe a stupid idea, but currently I'm not sure how to handle this properly. So feel free to correct me if I'm on the wrong path.

**Comment by dereuromark** [comment]
One trick to apply it locally without re-running the actual queries:
Just `return;` in your migration when running them. They are now marked as run without touching the DB.

Of course this should only be done if you must change the DB manually beforehand.
Otherwise you would usually write the migration file and let phinx handle the actual DB modification.
