### ISSUE TITLE
Postgres timestamp with timezone support

### ISSUE THREAD

**Issue by glena** [cakephp/phinx#410]
Hi,

Is there any way or workaround to enable timestamp with timezone support for PostgreSQL databases?

I have been checking the code and adding this type to the adaptes seems not to be enough.

Thanks.

**Comment by celorodovalho** [comment]
If I want to work with DateTime? (not DateTimeTz).
The difference are in the "microseconds":
DateTime:
2016-08-04 14:34:34

DateTimeTz:
2016-08-04 14:34:34.367606

If I use:
$table->addColumn('due_date', 'timestamp', array('timezone' => true));
I get:
ADD COLUMN due_date timestamp without time zone

But, If I want DateTime (without microseconds) I must to do:
ADD COLUMN due_date timestamp(0) without time zone

But now way to do that with Phinx.

Maybe if add the option "limit" in type "timestamp", this way I can add the option number in timestamp.
