### ISSUE TITLE
Dependency Injection / Inversion

### ISSUE THREAD

**Issue by shadowhand** [cakephp/phinx#413]
To allow Phinx to be fully extensible, it needs to apply [Dependency Inversion](http://en.wikipedia.org/wiki/Dependency_inversion_principle) to allow for dependency injection. The simplest way to approach DI compatibility would be to provide a "class map" that can be overloaded by configuration. This avoids the need to add a container dependency to Phinx.

Along with applying IoC, many methods that have hard-coded lists (eg `Column::setOptions`) should be split into multiple smaller methods to allow more precise modifications by extension. This helps satisfy the [LSP](http://en.wikipedia.org/wiki/Liskov_substitution_principle) part of [SOLID](http://en.wikipedia.org/wiki/SOLID_%28object-oriented_design%29).

Useful links on the subject:
- http://aspiringcraftsman.com/2008/12/28/examining-dependency-inversion/
- http://www.theserverside.com/news/1321158/A-beginners-guide-to-Dependency-Injection
- http://docs.structuremap.net/DependencyInjection.htm
- http://richardmiller.co.uk/2011/05/19/when-dependency-injection-goes-wrong/

**Comment by dereuromark** [comment]
Anything here to be done still? Or can this be closed?
