### ISSUE TITLE
TextWrapper options should default to: 'parser' => 'yaml'

### ISSUE THREAD

**Issue by adamski** [cakephp/phinx#461]
If I run 

``` php
$wrap = new Phinx\Wrapper\TextWrapper($app, array('configuration' => BASEPATH.'../phinx.yml')); 
```

I get:

> The "--parser" option requires a value.

Should this not behave the same as the command line version and default to 'yaml' ?

**Comment by dereuromark** [comment]
@adamski 
Are you able to provide a pull request with your suggested changes?

**Comment by MasterOdin** [comment]
@dereuromark I think this can be closed. I was able to run the code snippet from the OP without problem as the parser, if not given, is automatically determined based off file extension of the config file, defaulting to yaml.
