### ISSUE TITLE
ANSI colours translated to HTML in TextWrapper

### ISSUE THREAD

**Issue by adamski** [cakephp/phinx#462]
Very a much a "nice to have" feature request:
Option to transform ANSI colours to HTML tags when using TextWrapper.

**Comment by alexbowers** [comment]
Any progress @shadowhand ?

**Comment by shadowhand** [comment]
@alexbowers I'd take a PR for this, but don't see a pressing need for it.

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?
otherwise we must close this for a lack of activity.
