### ISSUE TITLE
Consider merging TablePrefixAdapter, AdapterWrapper & ProxyAdapter

### ISSUE THREAD

**Issue by robmorgan** [cakephp/phinx#467]
`TablePrefixAdapter`, `AdapterWrapper` & `ProxyAdapter` all collect and/or override commands proxied to real adapters. Could they somehow be merged into one?

**Comment by shadowhand** [comment]
@robmorgan I don't think so... AdapterWrapper is the abstract base for ProxyAdapter and TablePrefixAdapter, where the concrete implementations overload the specific methods that are modified from the wrapper. This is exactly how it should work.

**Comment by robmorgan** [comment]
What about ProxyAdapter and TablePrefixAdapter then? To me it seems a bit weird to have an adapter that handles table prefixes/suffixes. Whilst it was easier to build it this way, maybe the logic should be in the adapter implementations themselves.

**Comment by shadowhand** [comment]
Personally, I like the way it works right now. There's no downside, and it proves that Phinx can be extended very cleanly.
