### ISSUE TITLE
Rolling back creating table with change() doesn't work

### ISSUE THREAD

**Issue by elliotwms** [cakephp/phinx#476]
Steps to reproduce:
- Create migration making a table
- Run that migration
- Roll back the migration
- Run the migration again
- Feel the pain

Results in a PDOEXCEPTION:

```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'table_name' doesn't exist
```

**Comment by elliotwms** [comment]
Looks like this happens when adding more than one foreign key to a table you're creating. MySQL really seems to wig out

**Comment by dereuromark** [comment]
Is this still an issue?
