### ISSUE TITLE
Add double column type

### ISSUE THREAD

**Issue by naquad** [cakephp/phinx#498]
MySQL has a `double` column type. Please add it.

**Comment by sidz** [comment]
It will be great.

My workaround:
$this->execute('ALTER TABLE `table` ADD COLUMN `amount` DOUBLE(13,4) NOT NULL;');

**Comment by george-oakling** [comment]
Yes, please, it is a must have :)

**Comment by tendallas** [comment]
+1

**Comment by BallisticPain** [comment]
+1

I'm not sure why this isn't supported out of the gate. Both Postgres and MySQL have a Double. Maybe not for the other adapters I don't know.

Has anyone attempted to submit a PR for @robmorgan?

**Comment by codercms** [comment]
+1

**Comment by daniel-gomes-sociomantic** [comment]
+1

**Comment by rquadling** [comment]
Make a PR and I'll look at it. Going for a release over the weekend. Small things like this are going in.

If anyone cares to trawl through the backlog and find other column types that are missing too then that would make things a little easier on me. Of course, all code changes that require update to documentation also needs to be done too!

Thank you! 😸

**Comment by BallisticPain** [comment]
I'll peek into this once I get my other PR completed.

**Comment by BallisticPain** [comment]
Won't have time to do this one I don't think, but I'll let you know if that changes. Otherwise I'll attempt this one immediately following regardless.

**Comment by dereuromark** [comment]
Pr open.
