### ISSUE TITLE
Additional options for column not supported by Phinx

### ISSUE THREAD

**Issue by naquad** [cakephp/phinx#500]
In MySQL there are options that are not explicitly supported by Phinx. Such as `CHARACTER SET` for exmaple. I suggest to add another column attribute `tail` which if given will be simply concatenated to column definition so user would be able to set database-specific options per column.

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?

**Comment by naquad** [comment]
I can't as Phinx is not used anymore in project I'm working on :(
