### ISSUE TITLE
Is it possible to set configuration without a separate file?

### ISSUE THREAD

**Issue by dasper** [cakephp/phinx#512]
I am needing to include database migrations into our automated system and we do not have a compatible way of passing our variables for each environment in a yaml/php file. 

I have been attempting to rummage through the source to see if there is some way do do the following:

```
$this->app = require __DIR__ . 'path/to' . /robmorgan/phinx/app/phinx.php';
$this->app->setConfig(new Phinx\Config\Config($this->config));
$this->app->run();
```

I see it is set though an interface so I believe what I am attempting to do is possible. Is there away to inject the configuration data or am a approaching this the wrong way?

Thank you for your time on this.

**Comment by m1ome** [comment]
We are using Phalcon, and we maked our own `phinx.php` file:

```php
<?php

// Require global config from Phalcon
$config = __DIR__ . '/app/config/config.php';

if (!isset($config)) {
  die('You must create config first in: ' . $config . PHP_EOL);
} else {
  $config   = require_once($config);
  $database = isset($config['database']) ? $config['database'] : null;

  if ($database === null) {
    die('In your config you not set a database key' . PHP_EOL);
  }

  if (!isset($database['host'])) {
    die('You not set database host in your config' . PHP_EOL);
  }

  if (!isset($database['username'])) {
    die('You not set database username in your config' . PHP_EOL);
  }

  if (!isset($database['password'])) {
    die('You not set database password in your config' . PHP_EOL);
  }

  if (!isset($database['dbname'])) {
    die('You not set database name in your config' . PHP_EOL);
  }

  return [
    'paths' => [
      'migrations' => 'app/migrations',
    ],
    'environments' => [
      'default_migration_table' => 'phinxlog',
      'default_database' => 'production',
      'production' => [
        'adapter' => 'mysql',
        'host'    => $database['host'],
        'name'    => $database['dbname'],
        'user'    => $database['username'],
        'pass'    => $database['password']
      ]
    ]
  ];
}
```

**Comment by m1ome** [comment]
You can do something similar. Even if you using `.xml` or `.ini` file, you can parse them and then return properly formed php array in `phinx.php`

**Comment by dasper** [comment]
Thanks for your reply. Sadly I am not sure if I have this capabilities. We have a deployment/cron server already in place that we want to handle the migrations and we have different users that have different paths with different db connections we are trying to manage on one server. Creating an phinx.php file would require us putting it in at least 3-5 different places or changing the deployment script where its working path is and then changing it back for other parts of the deployment and changing the way it currently works is involving IT, Infrastructure, and Development to make some changes.  I was hoping there would be a clean way of handling this without getting other departments involved more than they have already.

I am working on some solutions now. Again, thanks for your response. I wish our deployment system was not so complex at times.

**Comment by dasper** [comment]
Long story short, I created a migrations class that then sets the config in this fashion

````
    private function setConfig()
    {
        $this->cwd = getcwd();
        $this->path = __DIR__;
        $this->config = include_once $this->path . '/phinx.php';
        //print_r($this->config); die('PHP_EOL');
        chdir($this->path);
    }

    private function restoreCWD()
    {
        chdir($this->cwd);
    }
````

then I call phinx like so:

````
$this->setConfig();
$this->app->run();
$this->restoreCWD();
````

This way, the user executing the deployment will get the proper db credentials for the appropriate server.

**Comment by dereuromark** [comment]
Closing as answer has been given
If someone is willing to PR a documentation addition, that would be very welcome!
