### ISSUE TITLE
Ability to separate pre and post-deploy migrations

### ISSUE THREAD

**Issue by acoulton** [cakephp/phinx#529]
We generally aim for zero-downtime migrations/deployments, which usually means splitting migrations to ensure that the database is always in a valid state for either old or new production code.

For example, new columns need to be added before the code is deployed, but code needs to be deployed before old columns can be removed.

As standard, we run migrations before deployment (and take care to write safe migrations for that context). When we need to run a destructive migration we usually change the code and deploy without adding a migration, leaving a `@todo` tag somewhere to come back later and do any cleanup on the DB.

The downside is that this leaves work for later, makes it harder to see the relationship between application and DB changes in source control, and makes pull requests etc harder to review.

It would be great instead if there was a way to write the pre and post deploy migrations at the same time, but tag them so that phinx could run them in two batches. We would then have a deploy flow like:
- `bin/phinx migrate --phase=pre-deploy`
- deploy code and do whatever checks that the deploy was happy, potentially waiting to see it in production a while
- `bin/phinx migrate --phase=post-deploy`

This could be implemented something like:

``` php
class AbstractMigration
{
  public function shouldApplyInPhase($phase)
  {
    // by default migration will run on the next migrate command, as now.
    return TRUE;
  }
}

class RemoveAColumn extends AbstractMigration
{
  public function shouldApplyInPhase($phase)
  {
    return $phase === 'post-deploy';
  }
}

class Phinx\Migration\Manager {
  public function migrate($environment, $version)
  {
      //...
      foreach($migrations as $migration) {
            if ($migration->getVersion() > $version) {
                break;
            }

           if (!$migration->shouldApplyInPhase($env->getMigrationPhase()) {
                continue;
           }

           if (!in_array($migration->getVersion(), $versions)) {
                $this->executeMigration($environment, $migration, MigrationInterface::UP);
            }
      }
  }
}
```

Alternatively, it could be done by including a prefix in the filename eg `20150326100000_post-deploy_remove_a_column.php` and filtering them at load-time.

This would only be relevant for migrate, for rollback it would be assumed the site had been taken offline for recovery.

pre and post deploy seem like the two most logical phases, but it would be easy to allow end users to use whatever phases suited them. For example you might define an extra 'maintenance-window' migration phase for more intensive cleanup tasks that should happen at some point but weren't required immediately post-deploy.

What do you think?

**Comment by dereuromark** [comment]
Any feedback here from the team?

**Comment by daidais** [comment]
Would be really cool to have this possibility indeed.

**Comment by lulco** [comment]
@acoulton just remove not necessary columns / tables in next version of application

or create separate migration folder for post-deploy with post-deploy-phinx config file and run phinx with this config in post-deploy phase

**Comment by acoulton** [comment]
@lulco waiting to remove in the next version is OK, but it's a bit messy to keep track of and harder to review the complete set of changes related to a new feature etc in a single pull.

Since this request we have started to use a separate directory for post-deploy migrations as you suggest - we don't run them automatically post-deploy but instead manually move them across to the live directory as and when : experience has shown that some cleanups are fine to run immediately, others we might want to hold off to see the new code running in production a bit longer.

We're shortly planning to set up our CI to run the code both with and without all the post-deploy migrations to give even better confidence. But as-is it's been really helpful to have the future migrations already written and visible in the same PR as other changes.

I think I'll actually close this : what we have is working OK for us now and I think my original idea maybe wouldn't be flexible enough in practice.
