### ISSUE TITLE
Ability to populate tables (fixtures)

### ISSUE THREAD

**Issue by Lo-X** [cakephp/phinx#530]
Hi,

It would be nice to have something to populate the tables with random (or not) values.
At the moment we have to do it by hand by doing `$this->query("INSERT INTO ...");` or doing sql scripts or whatever not handy solution.

It would be awesome to have it in the command line like : `CreatePosts title:string content:text --populate=n` where n is the number of random generated rows we want in the table we are creating.

I can't figure an elegant way of doing the same to populate a table with specific values. Perhaps a new command like : `PopulateUsers username:admin password:qwerty1234`

I know this is a lot of job, I'll fork and give it a try.

**Comment by dereuromark** [comment]
This is often handled by the frameworks using this, e.g. CakePHP provides this, as does sure many others using some random-data providers.

From the lack of support here it seems that most dont see this as a direct phinx responsibility.
Feel free to PR any such addition for further discussion, however.
