### ISSUE TITLE
Default value for UUID in Postgresql

### ISSUE THREAD

**Issue by srigi** [cakephp/phinx#539]
I want to be able to do this:

``` php
$this->table('users')
    ->addColumn('uuid', 'uuid', ['default' => 'uuid_generate_v4()'])
```

However column option gets quoted so it leads to error

```
[PDOException]
  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for uuid: "uuid_generate_v4()"
```

Are you open to this request?

**Comment by RQuadling** [comment]
http://stackoverflow.com/questions/22446478/extension-exists-but-uuid-generate-v4-fails maybe?

**Comment by srigi** [comment]
@RQuadling that's not the issue. Phinx is quoting that column option so it literally creates table like

```sql
CREATE TABLE user (
  uuid uuid DEFAULT 'uuid_generate_v4()'
);
```

that function call is wraped in quotes which is wrong. I got extension enabled.

**Comment by steffkes** [comment]
looks like i've overlooked this one while opening #625 - underlying problem is the very same, though this one is missing a solution or at last proposal for one. @srigi is this still a relevant request for you?

**Comment by srigi** [comment]
SQL Literal is a way to go for me. If that gets implemented, this would become irrelevant.

**Comment by karllhughes** [comment]
I know this is old, but what's the workaround? Can I write raw sql to make the id an auto-generated uuid?

**Comment by daneren2005** [comment]
I updated this thinking it would have been fixed in the past two years, but it's still broken.  Is this not going to be fixed?

**Comment by rquadling** [comment]
If someone can produce a PR with unit tests, then we will certainly consider it. I don't have any experience with Postgres to determine what would be a suitable option.

I would guess a simple string test to see if the supplied default is a predefined constant, then treat the default as is without quoting.

**Comment by karllhughes** [comment]
@rquadling I made a PR for this. Let me know if there's anything else I can do to improve it. https://github.com/robmorgan/phinx/pull/1065

**Comment by dereuromark** [comment]
PR open

**Comment by tertek** [comment]
For anyone still coming here. It has been resolved by using Literals:

https://book.cakephp.org/phinx/0/en/migrations.html#custom-column-types-default-values
