### ISSUE TITLE
Simple questions

### ISSUE THREAD

**Issue by IngwiePhoenix** [cakephp/phinx#541]
Hey there.

I am working with a Yii app, but I am not really happy with the built-in migration mechanism. Currently I am using the `1.x` series of releases.

In order to properly incorporate Phinx into my app, I would like to know a few things:
- I saw that one can specify a template. How do I make one?
- Are there top-level commands for `CREATE DATABASE`?
- The docs that I found only talked about creating and coding a migration, but I have not seen anything about the config file. Thing is that I am utilizing a custom config folder for all the files that configure one or another component. What has to go into a config and which format(s) can I use?

Kind regards, Ingwie!

**Comment by IngwiePhoenix** [comment]
Ok, there are DB functions.

https://github.com/robmorgan/phinx/blob/0.4.x-dev/src/Phinx/Migration/AbstractMigration.php#L191

...but what is `$options` supposed to have?

**Comment by BardiaAfshin** [comment]
you should reference this http://docs.phinx.org/en/latest/

**Comment by IngwiePhoenix** [comment]
There also is no remark for `createDatabase()`'s usage, although the inline code comment reads "inherit from docs". So I still dont know how this function is to be used correctly.

The rest of my questions can be answered in these docs though.

**Comment by chenjin0624** [comment]
How to create a db,not found in [http://docs.phinx.org/en/latest/](url)
