### ISSUE TITLE
Adding "bootstrap" handling (via an external PHP file)

### ISSUE THREAD

**Issue by enygma** [cakephp/phinx#549]
I have a situation where it would be helpful to be able to call a PHP bootstrap file prior to the execution of the migrations. Ideally it would be able to set configuration information back into the application, possibly called either from the command line:

```
vendor/bin/phinx migrate --bootstrap=/path/to/bootstrap.php
```

or in the configuration file:

```
paths:
    migrations: %%PHINX_CONFIG_DIR%%/migrations
    bootstrap: /path/to/bootstrap.php
```

I don't know if this functionality might be useful to anyone else out there but I could see it being handy for my personal needs.

**Comment by sergiors** [comment]
:+1:

**Comment by cassiosantos** [comment]
:+1:

**Comment by m1ome** [comment]
This is obvious a copy-of-functionality.
To achieve this you can use [php configuration files](http://docs.phinx.org/en/latest/commands.html#configuration-file-parameter)
