### ISSUE TITLE
Support YEAR field type for MySQL

### ISSUE THREAD

**Issue by neemzy** [cakephp/phinx#551]
The [`YEAR` field type](http://dev.mysql.com/doc/refman/5.0/en/year.html) allows one to store a year in a field, and have this field default to the current year.

Is it an option for Phinx to support this specific MySQL type, as it does for `ENUM` and `SET` ?

Thanks !

**Comment by Gregoire-M** [comment]
:+1:

**Comment by nicosomb** [comment]
:+1:

**Comment by neemzy** [comment]
Bump?

**Comment by bastientanesie** [comment]
I wish I had this field type right now... I'm working on a database relying heavily on year-based info, and I don't know how to work around this.

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?

**Comment by neemzy** [comment]
Unfortunately, I'm not working in a PHP environment anymore, so not really.
Maybe @Gregoire-M would be interested in submitting one? ;)

**Comment by Gregoire-M** [comment]
Well, it seems to be already implemented: 1eb069a500e9b78a442e01cd83ba6b6a80ae1855
