### ISSUE TITLE
Support dotenv files

### ISSUE THREAD

**Issue by alexbowers-tecmark** [cakephp/phinx#558]
Support for a dotenv file would be quite nice.

Instead of having the database username password and name put into both .env and phinx.yml, having the phinx.yml file allow lines such as 

user: {~/path/to/.env:mysql_user} where the first half is the path to the env file, and the second half is the name of the environment variable.

Either that, or supporting the dotenv project itself and having the .env file loaded into the environment variables, and then allowing {mysql_user} to recognise environment variables would be good.

**Comment by mamchenkov** [comment]
Here's the library that makes it trivial to support .env files:

https://github.com/vlucas/phpdotenv

**Comment by alexbowers-tecmark** [comment]
Yes, that is the one that I was meaning :)

**Comment by claudio-silva** [comment]
:+1: Please do!

As many people already use .env files on their projects, and it is something that is **becoming increasingly popular** (ex: the Laravel framework now also has it), adding support for .env in phinx would simplify integrating phinx into a Laravel application or any other app that uses .env, reducing the *barrier to adoption* that always happens when a developer needs to summon the courage to try out a new tool.

**Comment by DerMika** [comment]
:+1:

To be fair, there is a workaround. You could use the (badly documented) `phinx.php` config file and load settings using phpdotenv there.

**Comment by philsown** [comment]
How I implemented what @DerMika is saying. I used -c phinx.php and loaded dotenv in that file, like so:

```php
<?php

$dotenv = new Dotenv\Dotenv(__DIR__);
$dotenv->load();

return [
    'paths' => [
        'migrations' => __DIR__ . '/migrations',
    ],
    'environments' => [
        'default_migration_table' => 'phinxlog',
        'default_database' => getenv('APP_ENV'),
        'develop' => [
            'adapter' => getenv('DB_ADAPTER'),
            'host' => getenv('DB_HOST'),
            'name' => getenv('DB_NAME'),
            'user' => getenv('DB_USER'),
            'pass' => getenv('DB_PASS'),
            'port' => getenv('DB_PORT'),
        ],
    ],
];
```

That was probably obvious, but if it saves someone some time...

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?

**Comment by philsown** [comment]
@dereuromark Sure. I made a quick pass at it. Any particular branch you want me to make a pull request against? Master?

**Comment by dereuromark** [comment]
if it is bc master should be fine.

**Comment by dereuromark** [comment]
ping

**Comment by philsown** [comment]
The PR I submitted is here:  https://github.com/cakephp/phinx/pull/1236
