### ISSUE TITLE
Add a verbose dry-run feature

### ISSUE THREAD

**Issue by stephenlawrence** [cakephp/phinx#567]
All of our database changes must be approved by our DB guys. In order to assist with this it would be helpful if we could run a "dry-run" command that would output the SQL that would have been executed during the migration run.

**Comment by elliotwms** [comment]
That sounds interesting. Perhaps a command-line argument like `--pretend`

**Comment by robmorgan** [comment]
something like this will be included in the future. We need to log all SQL statements first then add a command to simulate.

**Comment by robmorgan** [comment]
no timeline yet though

**Comment by daniel-gomes-sociomantic** [comment]
+1

**Comment by rquadling** [comment]
+1 for --dry-run. Matches the same expectation with many other Symfony console based applications.

**Comment by daniel-gomes-sociomantic** [comment]
implemented it in https://github.com/robmorgan/phinx/pull/746

**Comment by berarma** [comment]
+1

This feature would be a big timer saver. Right now debugging non-trivial migrations is a serious pain.

Rob, what's your take on this? Would it help that we tested Daniel's pull request?

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?

**Comment by berarma** [comment]
There's already a PR that got closed (#746) because another one doing the same (#1127) was already merged. I think this issue can be closed.
