### ISSUE TITLE
Insert into phinxlog with many schemes

### ISSUE THREAD

**Issue by ipoz** [cakephp/phinx#575]
I have many schemes in my database(postgresql), when I run migarte then script throw excpetion:

> [PDOException]  
> SQLSTATE[42P01]: Undefined table: 7 ERROR:
> LINE 1: INSERT INTO phinxlog (version, start_time, end_time) VALUES ...

Problem is solved by changes in src/Phinx/Db/Adapter/PostgresAdapter.php line 997 and 1008:
`$this->getSchemaTableName(),`
to
`$this->quoteTableName($this->getSchemaTableName())`

**Comment by rafcis** [comment]
:+1:

**Comment by dereuromark** [comment]
You even got upvotes for upvotes here :)

Are you able to provide a pull request with your suggested changes?
That would be awesome!

**Comment by ipoz** [comment]
Yes, I'll do that

**Comment by dereuromark** [comment]
PR open
