### ISSUE TITLE
Add option to customize timestamps field names

### ISSUE THREAD

**Issue by topikito** [cakephp/phinx#576]
When calling method `addTimestamps()`, the fields are named by default (hardcoded). Would be ideal to have a way to customize the names of these fields to match each projects own conventions.

As a secondary nice to have, I'd say to specify the type of that field, as you may use native MySQL timestamp or perhaps want to use integer to match php `time()`.

**Comment by danielfh** [comment]
+1

**Comment by samizdam** [comment]
Hm, when I try find this feature, I don't see this issue and create #706  and implement with #707 
So, +1)

**Comment by dereuromark** [comment]
Seems implemented according to 2nd link.
