### ISSUE TITLE
Notice triggered when $options['host'] is not set

### ISSUE THREAD

**Issue by topikito** [cakephp/phinx#577]
On `src/Phinx/Db/Adapter/MysqlAdapter.php:87`, if no host is set in the config, the index "host" would not exist, therefor it will trigger a Notice:

`PHP Notice:  Undefined index: host in .../vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php on line 87`

However, I guess the PDO class falls back to "localhost" because the connection actually succeeds. I would fix it myself, but I don't know if you'd prefer to trigger an Exception or rather fallback to a "localhost" default (the same as PDO?).

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?
As this triggers currently a notice but then does sth correct, it seems an exception might be a bit too BC breaking (and can be considered for a major jump).
Localhost fallback as a shortterm solution sounds like a good idea.

**Comment by topikito** [comment]
Hi @dereuromark - Im no longer using it so I guess if nobody else have complained, it may not be worth looking into (?)

**Comment by dereuromark** [comment]
Closing then for now.
