### ISSUE TITLE
Determining the environment in the migration class.

### ISSUE THREAD

**Issue by ivstefano** [cakephp/phinx#579]
Currently there is no way to determine the environment in the migration class. 

You are going to ask why this is necessary. The answer is the following: 

When using MySQL, if a primary key has to be dropped then the command is `ALTER TABLE sampleTable DROP PRIMARY KEY;`. When doing the same thing for SQL Server, the specific CONSTRAINT NAME should be known: `ALTER TABLE sampleTable DROP CONSTRAINT constraintName;`. 

Currently, if there is a difference in the name of the PRIMARY KEY CONSTRAINT in DEV and PROD databases, then there should be two identical migration files where the `constraintName` is the only difference. Isn't it a better idea to be able to check the environment inside the migration file and do different things based on that?

**Comment by elliotwms** [comment]
Out of curiosity why do you have a divergence in the SQL implementation between your development and production environments?

**Comment by robmorgan** [comment]
Hi @zigivicious you should always avoid environment specific code in your migrations if you can help it.. Ideally you want to run the exact same migrations on dev, staging and prod. That's what proper QA is all about.

**Comment by robmorgan** [comment]
I'm leaving this issue open because it will be implemented at some stage in the future (even though I strongly recommend against it).

**Comment by zigivicious** [comment]
I agree with you, the idea is that both are the same. Initially I had this misconception about SQL Server generating it's own Contraint Key Names. But apparently they can be customized which I found a bit later.

**Comment by DerMika** [comment]
Hello @robmorgan, my usecase  is that I have to insert different data into the database depending on which environment I'm doing the migration for.

For example: I am not allowed to give all production users access to the staging instance, so I need to be able to insert a small subset of users in staging. 

In my case there is no difference in schema's, but there is different data to be inserted depending on the environment.

**Comment by daniel-gomes-sociomantic** [comment]
this was implemented in https://github.com/robmorgan/phinx/pull/794/files
