### ISSUE TITLE
Add method hasIndexByName

### ISSUE THREAD

**Issue by laurin1** [cakephp/phinx#580]
So if I want to check to see if an index exists before I attempt to drop it, I can't because this code checks against column names and not key names. That's fine if all of your index are a single column and named the same as the column, but I rarely do that.

If this is expected behavior, then can we add a method called hasIndexKeyName() or something to that effect? I can write the PR for it, but want some feedback first.

**Comment by laurin1** [comment]
Same issue with hasForeignKey()

**Comment by laurin1** [comment]
So there is a dropIndexByName, but not a hasIndexByName. Strange.

**Comment by laurin1** [comment]
Ok, I've forked and written the code for all adapters for this new method. I have never submitted a pull request on Github. So I need to install all database systems (I have MySQL already) and write the unit tests for each of these methods and then submit the pull request?

**Comment by robmorgan** [comment]
Hi @laurin1, yes as you are extending `AdapterInterface` you must provide implementations for all supported DB adapters including Sql Server. If you do not have access to Sql Server you can always test your code using tools like Appveyor.

**Comment by laurin1** [comment]
Will it work with SQL Server Express?

**Comment by robmorgan** [comment]
Yes it will if you install the Sqlsrv PDO driver.

**Comment by dereuromark** [comment]
Looks like this can be closed?
