### ISSUE TITLE
Phinx should support PHP as a configuration file parser

### ISSUE THREAD

**Issue by awbn** [cakephp/phinx#59]
Phinx should support loading configuration options from a PHP file as well as from yaml.

Primary scenario:
I use PaaS providers such as [Pagodabox](http://pagodabox.com), [Dotcloud](http://dotcloud.com), [Appfog](http://appfog.com), etc.  I'd like to use Phinx to manage database versioning during deployments.  However, most providers provide database credentials in the form of environment variables.  These are easily read in native PHP, but cannot be accessed in yaml without writing a shim that outputs credentials to a .yml file (which negates the point of the env variables). Up until recently I could work around this as the Symfony yaml parser actually supported reading native PHP files through `Yaml::parse()` as long as they returned an array.  However, that support [is now deprecated](https://github.com/symfony/Yaml/blob/master/Yaml.php) and will be removed in future versions.

Secondary scenario:
Most frameworks provide a single settings file to store database credentials and environments.  If Phinx can support reading in configuration options through a PHP file, it makes it much easier to create a lightweight, app-specific shim that allows me to maintain database credentials in a single location rather than in both the framework settings file and in phinx.yml.

**Comment by rogoit** [comment]
How do i use dynamic folder there? http://stackoverflow.com/questions/39275065/phinx-path-with-subfolders
