### ISSUE TITLE
Wrap migration execution in a transaction

### ISSUE THREAD

**Issue by robmorgan** [cakephp/phinx#6]
Wrap the migration execution in a transaction if supported by the adapter. This will require a method in the adapter like `hasTransactions`

**Comment by LaGregance** [comment]
More than 10 years later, this is still not supported apparently (or maybe not supported on MySQL 5.7 ?).
But it's really a pain when building migration that fail in the middle without being rollback...
Is there plan to support it ?

**Comment by MasterOdin** [comment]
@LaGregance, not having support for transactions around a migration is a continuing limitation of MySQL. Even if Phinx were to try to implement some facsimile of transaction support similar to what other adapters have built-in, it would probably be a huge undertaking as it'd require a huge architecture restructure and it'd be tough to avoid any potential footguns. At this time, I've no real plans to try to do this.
