### ISSUE TITLE
Custom autoloading or initialization

### ISSUE THREAD

**Issue by emestee** [cakephp/phinx#611]
Hi,

I have a funny project structure which isn't fully compliant with the PSRs, because of prefixes to class names and suffixes in file names. I want to use a custom base migration but Phinx won't be able to load it because Composer doesn't allow us registering custom autoloaders so we load our own one manually in early stage of the application's initialization from an include file which Phinx won't be able to discover.

A hacky solution here would be to map this particular abstract migration class to a kludge that would load our autoloader and then load the class. However I'm thinking that this kind of thing should be configurable in Phinx itself, i.e.:
- The configuration file gets a new option `init_file`, this may be global or per environment
- `Phinx\AbstractCommand::bootstrap()` after loading the configuration sees if this option is set and then includes the requested file

This is more or less the same approach PHPUnit uses to better integrate into complex projects. It could also be a global command line option, although I can't think of an use case.

If this makes sense I'll try it out and submit a PR.

**Comment by rquadling** [comment]
There is an outstanding PR https://github.com/robmorgan/phinx/pull/472 which would allow you to assign aliases to the template generating classes, but I think the same issue applies though, non PSR class names.

Your autoloader could be attached to composer (https://getcomposer.org/doc/04-schema.md#autoload). Depending upon the number of classes, you _could_ use a classmap entry there. Maybe.

**Comment by emestee** [comment]
The composer approach isn't exactly useful because it'd load the file on every invocation regardless of context (including the app's web and cli, phpunit, some other integrated tools etc), so I'd need to have the code inside check which context it's been called from.

If Phinx supported a custom init file, I'd be able to specify there the necessary minimal configuration needed for our framework when executing from Phinx only (it's not just autoloading that needs to get bootstrapped; there's various config files and env vars that need to be examined, service registry seeding, developer mode safety filter injections etc). Naturally, #472 only address the autoload part of this problem.

So should I write a patch or not?

**Comment by rquadling** [comment]
Create a PR, sure. I don't know what the timescale for acceptance is going to be though. Still waiting on 2 of mine. :-/

**Comment by dereuromark** [comment]
bump
@emestee Are you able to provide a pull request with your suggested changes?

**Comment by emestee** [comment]
oh wow that was 2 years ago... I'll add this to my queue.

**Comment by simivar** [comment]
bump, @emestee how long is your queue? 😆

**Comment by emestee** [comment]
Oh lord, I'm doing python and systems at the same time. I'd say infinitely long. But lemme take a look.

**Comment by Nilithus** [comment]
I also came across this issue recently when I wanted to use a [boxxed](https://github.com/box-project/box2) phinx to run my migrations but my migrations used constants from classes defined in my application. I needed to essentially require my autoloader. I know I could use the migration init function but I had a lot of migrations and didn't want to duplicate code.

I'd be willing to take a stab at this if people are still interested.

**Comment by martijngastkemper** [comment]
Using constants from classes is risky because it creates a dependency between a migrations and the code. Code changes but the migration has to run of that code when creating a clean install.

**Comment by Nilithus** [comment]
@martijngastkemper You're absolutely right we've had thing bite us once or twice. 

But we found ways to mitigate the issues with by making sure to run all our migrations during our CI pipeline and putting some checks around code changes to anything thats shared with migrations. It's not something we do a lot just mainly around sharing names between migrations and our sql builders.
