### ISSUE TITLE
Introducing literals?

### ISSUE THREAD

**Issue by steffkes** [cakephp/phinx#625]
While using phinx more and more, i've had a problem using a function as `default` since it gets quoted all the time no matter what.

```
/**
 * Get the defintion for a `DEFAULT` statement.
 *
 * @param  mixed $default
 * @return string
 */
protected function getDefaultValueDefinition($default)
{
    if (is_string($default) && 'CURRENT_TIMESTAMP' !== $default) {
        $default = $this->getConnection()->quote($default);
    } elseif (is_bool($default)) {
        $default = $default ? 'TRUE' : 'FALSE';
    }
    return isset($default) ? 'DEFAULT ' . $default : '';
}
```

this snippet coming from `PostgresAdapter`, we do have a special check for `CURRENT_TIMESTAMP` which probably is an indicator that we already should have something like that in place :?

my idea would be something like:

```
$table->addColumn(
  'id',
  'uuid',
  [
    'default' => new WhateverTheNamespaceWillBe\Literal('gen_random_uuid()')
  ]
);
```

and extending `getDefaultValueDefinition` for a check on `Literal`, which - if true - would call `Literal#__toString` and use that w/o quoting. 

having used Doctrine ORM before, i'm pretty sure there are more places that could use Literals :)

all thoughts welcome! while waiting on #559 i've implemented that as additional check in my custom adapter, but would like to contribute that back.

**Comment by mvrhov** [comment]
Why don't you provide a PR with the Literal implementation. I'm sure it will get merged.

**Comment by steffkes** [comment]
@mvrhov i'm not using phinx anymore, at least not for the time being. i didn't come up with a PR straight away since i was not entirely sure that it would be something that would be helpful for others as well.

**Comment by dereuromark** [comment]
@mvrhov Are you able to provide a patch with your suggested changes as PR?

**Comment by mvrhov** [comment]
@dereuromark: Unfortunately no. I've switched away from phinx as I found it to limited.
I've decided to write my own migration tool which utilizes plain SQL with some templating sprinkled on top of everything to allow some things to change on runtime. 
With that I can define tables stored procedures etc with the DSL that database provides.
