### ISSUE TITLE
interactive input of username password

### ISSUE THREAD

**Issue by BardiaAfshin** [cakephp/phinx#631]
is there a way to pass the credentials of the environment/database via interactive??

**Comment by BardiaAfshin** [comment]
Also, separate issue

When using the sample PHP phinx configuration file version, I want to be able to change the applications/migrations to a different directory. When I change this to a full path of a different location, it gives exception

```log
 [UnexpectedValueException]
  Migrations directory "application/migrations" does not exist
```

now I try to run something like
```shell
 PHINX_CONFIG_DIR=/Users/me/workspace/dbs DB_HOST=localhost DB_NAME=dbx_development DB_USER=root DB_PASS='' DB_PORT=3306 phinx migrate
```

I get
```log
  [UnexpectedValueException]
  Migrations directory "dbx/migrations" does not exist
```

**Comment by robmorgan** [comment]
@BardiaAfshin just to be clear about your first issue, you want to pass credentials through ENV vars or using an interactive prompt?

**Comment by BardiaAfshin** [comment]
Correct



—

**Comment by BardiaAfshin** [comment]
Preferably through interactive mode, that way the credentials don't sit in bash history. 









—

**Comment by nguyenvuduc** [comment]
I need this feature, too. It is too scary to save password (especially for production database server) in phinx.yml file. If someone copy my phinx.yml without permission or if I accidentally commit the file, I am dead.

**Comment by robmorgan** [comment]
Hi @nguyenvuduc what about storing your password in an environment variable?

**Comment by dereuromark** [comment]
Env vars it is, otherwise please PR your suggested enhancement.
