### ISSUE TITLE
Pass direction to change() method

### ISSUE THREAD

**Issue by oligriffiths** [cakephp/phinx#64]
Hi

When running non-reversible functions in the change method, like drop column, you need to be aware of which way the change is going, up or down. For example, a down operation can't reverse a drop column (how would it know what to put in back in?), thus this needs to be conditional based on the direction.

Simple change to Manager/Environment.php: 103:

```
        if ($direction == MigrationInterface::DOWN) {
            // Create an instance of the ProxyAdapter so we can record all
            // of the migration commands for reverse playback
            $proxyAdapter = new ProxyAdapter($this->getAdapter(), $this->getOutput());
            $migration->setAdapter($proxyAdapter);
            $migration->change($direction);
            $proxyAdapter->executeInvertedCommands();
            $migration->setAdapter($this->getAdapter());
        } else {
            $migration->change($direction);
        }
```

Oli

**Comment by stevemarksmonii** [comment]
Sorry to bring up an old issue but I've just ran into a similar thing and I wonder if it's the documentation that's a little misleading here:

http://docs.phinx.org/en/latest/migrations.html#dropping-a-column

As you can see, `removeColumn` is being used within a `change` method

**Comment by SparK-Cruz** [comment]
Also, if removeColumn expected all the parameters an addColumn does, it would be reversible...

**Comment by Roy-Orbison** [comment]
Since this [still doesn't exist](https://github.com/cakephp/phinx/blob/3c6a171b0455225cf42716dc4864feb620da716f/src/Phinx/Migration/Manager/Environment.php#L120), and pull #1151 got closed without merge, just ~~hack~~ work around it, e.g.:

``` php
public function change()
{
	$going_down = $this->adapter instanceof \Phinx\Db\Adapter\ProxyAdapter;

	# normal reversible migration code

	if (!$going_down) {
		# populate data that would just get dropped in a rollback, maintaining reversibility
	}
}
```

**Comment by dereuromark** [comment]
Maybe we can add a convenince wrapper as boolean? goingUp() etc?

**Comment by Roy-Orbison** [comment]
Or maybe we could use the existing [`isMigratingUp()`](https://github.com/cakephp/phinx/blob/master/src/Phinx/Migration/AbstractMigration.php#L220) method, that I authored, but didn't remember. 🤦‍♂
