### ISSUE TITLE
Mixing of scope of config based settings and command line settings.

### ISSUE THREAD

**Issue by rquadling** [cakephp/phinx#643]
Hi.

Having set a default template in the phinx.yml file (so we get the up() and down() methods rather than change() as that's how we roll), we are happy.

We now ask Phinx to create a migration based upon one of our own migration classes (our Permission migration class).

We get an error.

```
  [InvalidArgumentException]
  Cannot use --template and --class at the same time
```

We are sad.

I certainly see why this is happening.

But I think the rules should be amended slightly.

Considering that template/class are mutually exclusive, then you could considered them as a single entity called WhereDoWeGetOurTemplateFrom (maybe).

So, if I have defined something in the config, I can override it on the command line, no matter if it is template or class that I've defined or supplied.

If I have defined templates:class AND templates:file then this is an error.
If I have supplied --template AND --class, then this too is an error.

But, templates:file AND --class (or templates:class AND --template) is not an error as the runtime option overrides the default config, not just for the one

I've created a PR https://github.com/robmorgan/phinx/pull/642

**Comment by rquadling** [comment]
Anything stopping this being merged?

**Comment by dereuromark** [comment]
https://github.com/cakephp/phinx/pull/698 seems to be long merged.
