### ISSUE TITLE
Adding a boolean column with "limit" causes an SQL error in Postgresql

### ISSUE THREAD

**Issue by steinkel** [cakephp/phinx#649]
Hi,

```
            ->addColumn('is_superuser', 'boolean', [
                'default' => 0,
                'limit' => 1,
                'null' => false,
            ])
```

Is causing an error in Postgresql 9.3

SYNTAX error near "(" in BOOLEAN (1)

Would make sense to detect boolean type and ignore the limit option in this case?

Thank you!

**Comment by dereuromark** [comment]
That makes sense IMO
Are you able to provide a pull request with your suggested changes?

**Comment by othercorey** [comment]
Added in https://github.com/cakephp/phinx/pull/1222
