### ISSUE TITLE
How to update column comments

### ISSUE THREAD

**Issue by misilot** [cakephp/phinx#654]
Hi,

How do I update column comments in a migration?

Thanks!

**Comment by ve3** [comment]
This is old issue but I found this from Google. 
In case someone who is looking for how to change/update column comments, here is the code.

```php
$my_table = $this->table('my_table');
$my_column = $my_table->getColumn('my_column');
$my_table
    ->changeColumn($my_column->getName(), $my_column->setComment('new comment is here.'))
    ->update();
```
