### ISSUE TITLE
Multiline SQL execution result depends on the first query only 

### ISSUE THREAD

**Issue by jaroslavlibal** [cakephp/phinx#663]
Hi,

imagine that I have many single line queries in a string and I want to execute all of them in my migration. 

When the problem occurs in any other than in the first query, then the migration/rollback result is taken as succesful what is actually not true.

``` php
public function up()
{

$sql = <<<SQL
INSERT INTO `table` (`foo`) VALUES ('bar');
syntax error
INSERT INTO `table` (`foo`) VALUES ('bar2');
SQL;

$this->execute($sql);

}

// All Done. Took 0.0082s
```

**Comment by rquadling** [comment]
Mysql doesn't return the errors in any meaningful way when the queries are a batch.

PDO/mysqlnd/mysqli/mysql/etc. all suffer from this. As well as tools like HeidiSQL, MySQL Workbench, even good old mysql CLI!

The solution my team uses is to put SQL statements in .sql files. We gain some things like syntax highlighting, auto formatting (so the team always writes the same structure - useful when debugging someone else's code).

We have 2 migration template classes for this - ByDirectory and ByDirection. Very similar. ByDirectory creates a directory ``./migrations/SQL/<migrationFileName>/up`` and ``./migrations/SQL/<migrationFileName>/down`` with .sql files in each directory which can be executed in order (we use 01 - task 1.sql, 02 - task 2.sql, etc. for each direction).

The ByDirection is similar but is for a single up.sql and down.sql file.

The migration template classes use our own extended AbstractMigration class to deal with the multiple .sql files.


Of course, you could simply execute the queries one at a time in a transaction and rollback upon failure.
