### ISSUE TITLE
Postgres: set and enum do not work

### ISSUE THREAD

**Issue by sameg14** [cakephp/phinx#670]
`set` and `enum` types are currently not supported using the postgres adapter. In postgres a sequence is created, and then attached to the field. Here is an example of this using PSQL

``` sql
CREATE TYPE field_type AS ENUM (
    'int',
    'float',
    'string',
    'array',
    'bool'
);

CREATE TABLE field (
    data_type field_type DEFAULT 'string'::field_type NOT NULL,
);
```

**Comment by Vitexus** [comment]
now i have make phinx migrations from mysql using enums thus i have to fix it (write) by myself ...

**Comment by Vitexus** [comment]
PostgreSQL "Set Emulation" 
https://github.com/Vitexus/phinx/commit/8ab5581e5dbf254ba021c9e3a2b275440fc87d61

**Comment by dereuromark** [comment]
Are you able to provide a patch with your suggested changes as PR?

**Comment by Vitexus** [comment]
Dear @dereuromark , my patch is tiny but now 3 yeas old. 
And i have no time to backport it into current upstream.

**Comment by dereuromark** [comment]
Closing in favor of https://github.com/cakephp/phinx/issues/891
