### ISSUE TITLE
Warn when table is not saved/created/updated

### ISSUE THREAD

**Issue by igorsantos07** [cakephp/phinx#680]
I'm not sure if I'm the only stupid around here, but usually when I'm writing a migration I forget to append `create()/update()/save()` to the end of the method chain. Even though, the migration is run just fine, and I spend a minute or two staring at the table structure in my IDE, wondering why it haven't changed... until I notice I forgot to `update()`.

I wonder if it would be possible to issue a warning inside the table's `__destruct()` if none of those three "final" methods have been called? It's not possible to throw an exception but maybe print/throw a plain warning would be fine, so other forgetful guys will know they made a mistake.

**Comment by igorsantos07** [comment]
Would be even cooler if the right method (save/create/update) could be called directly from `__destruct()`, but I guess this is not possible because they might throw exceptions, right? Also, I'm not sure if they would be called in the right order.

**Comment by rquadling** [comment]
You could subclass the Phinx::AbstractMigration class and add your own functionality. All supported by Phinx.

In your ``phinx.yml`` file, look for, or add ``migration_base_class:xxxx``, where xxx is your newly created AbstractMigration class. You shouldn't need to create your own template (you can if you want to add additional documentation to remind you that you are running a subclass).
