### ISSUE TITLE
Define timestamp columns via arguments

### ISSUE THREAD

**Issue by samizdam** [cakephp/phinx#706]
Now it's hardcoded as 'created_at' and 'updated_at' at https://github.com/robmorgan/phinx/blob/0.5.x-dev/src/Phinx/Db/Table.php#L557 
`
Table::addTimestamps($createdAtColumnName = 'created_at', $updatedAtColumnName = 'updated_at')
`
more flexible.

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?
