### ISSUE TITLE
Support Symfony LTS versions

### ISSUE THREAD

**Issue by Soullivaneuh** [cakephp/phinx#715]
I see on your `composer.json` file that you require Symfony `~2.8|~3.0` components.

The problem is developers that using Symfony full stack (`symfony/symfony`) won't be able to include your tools on their projects.

I would suggest you to support at least, LTS versions of Symfony.

Actual maintained LTS are: 2.3, 2.7 and 2.8. If SF 2.3 support is not possible, at least lock support to 2.7 and 2.8 would be a good start.

I could work on a PR for that if you want.

Please see: http://symfony.com/doc/current/contributing/community/releases.html#schedule

**Comment by mbrodala** [comment]
@robmorgan Could you have a look at this? I'd also like to see at least Symfony 2.7 supported since the current state prevents co-installation with [TYPO3 7.6 LTS](https://github.com/TYPO3/TYPO3.CMS/blob/255a973aa09a3531730b719f54c1d8acf9bfa745/composer.json#L39-L40).

**Comment by dereuromark** [comment]
Resolved.
