### ISSUE TITLE
Issue with automated phinx execution

### ISSUE THREAD

**Issue by IngwiePhoenix** [cakephp/phinx#723]
I am executing Phinx through an NPM script:

```
  "scripts": {
    "bower": "bower --allow-root",
    "compile": "webpack --config ./app/System/Config/webpack.js",
    "phinx": "php php_modules/bin/phinx --configuration=app/System/Config/phinx.php",
    "dbtool": "php util/dbtool.php",
    "artisan": "php util/artisan",
    "shell": "php util/artisan tinker",
    "start": "node app/bootstrap/main.js"
  },
```

When I just want to use the `list` command, I get an exception, that `--configuration is not supported`. Could you fix that somehow?

**Comment by rquadling** [comment]
Sure ...
```
  "scripts": {
    "bower": "bower --allow-root",
    "compile": "webpack --config ./app/System/Config/webpack.js",
    "phinx": "php php_modules/bin/phinx list",
    "dbtool": "php util/dbtool.php",
    "artisan": "php util/artisan",
    "shell": "php util/artisan tinker",
    "start": "node app/bootstrap/main.js"
  },
```

**Comment by IngwiePhoenix** [comment]
That is not what i meant.

When using the list command, and having the config flag still in, causes an exception.

Is there a way to make Phinx accept the config flag when running the list command?

**Comment by rquadling** [comment]
Why are you putting the option in at all? Nearly every program throws an exception/dies for an unrequired option. Even DOS! Symfony console (the underlying tech that does the validation) is acting consistently and appropriately.

**Comment by shadowhand** [comment]
I agree, this isn't a phinx problem.
