### ISSUE TITLE
prefixing commands

### ISSUE THREAD

**Issue by mvrhov** [cakephp/phinx#730]
Hi,

I'm trying to integrate the phinx into the symfony but the commands don't have any prefix and thus the look weird when displayed through symfony console.

Would there be any chance that 0.6 has commands prefixed with `phinx:` ?

**Comment by rquadling** [comment]
We do this. One issue is the new ```seed``` prefix means you end up with ```phinx:seed:create`` which doesn't look very nice. Symfony doesn't support layered commands ... hmmm ... FEATURE REQUEST!!!

So, our solution is ...

```php
        $phinxCommands = (isset($_ENV['IncludePhinx']) && in_array($_ENV['IncludePhinx'], ['1', 'on', 'true', 'yes'], true)) ?
            array_map(
            /**
             * @param Command $phinxCommand
             * @return Command
             */
                function ($phinxCommandName, $dbCommandName) {
                    $phinxClass = '\Phinx\Console\Command\\'.$phinxCommandName;
                    /**
                     * @var Command $phinxCommand
                     */
                    $phinxCommand = new $phinxClass;
                    $phinxCommand->setName(sprintf('db:%s', $dbCommandName ?: $phinxCommand->getName()));

                    return $phinxCommand;
                },
                [
                    'Init',
                    'Create',
                    'Migrate',
                    'Rollback',
                    'Status',
                    'Breakpoint',
                    'Test',
                    'SeedCreate', // db:seed:create => db:seed-create
                    'SeedRun', // db:seed:run => db:seed-run
                ],
                [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    'seed-create',
                    'seed-run',
                ]
            ) : [];
```

This gets an array ``Symfony\Command`` that you can use via ```$app->addCommands()```.

When you run your command, you should see ...

```
 db
  db:breakpoint               Manage breakpoints
  db:create                   Create a new migration
  db:init                     Initialize the application for Phinx
  db:migrate                  Migrate the database
  db:rollback                 Rollback the last or to a specific migration
  db:seed-create              Create a new database seeder
  db:seed-run                 Run database seeders
  db:status                   Show migration status
  db:test                     Verify the configuration file
```

Adapt to fit your need.

**Comment by rquadling** [comment]
Oh. You don't need the ``$_ENV`` bit. That's for our setup. The ``array_map()`` is the call you need. We did look, initially, at ``glob``bing the names, but this is low maintenance for us. Again, adapt as you see fit.

**Comment by mvrhov** [comment]
Wondering why there is no bundle for this :P.

**Comment by rquadling** [comment]
I guess, for a standalone app, there really isn't much need to for the namespace.

**Comment by mvrhov** [comment]
I know that there is no need for namespaces in standalone app.. But with embedding there is a need.

**Comment by rquadling** [comment]
True, but if you are embedding a standalone app, then renaming them is the simplest way I could find.

**Comment by dereuromark** [comment]
Are you able to provide a patch with your suggested changes as PR?

**Comment by mvrhov** [comment]
@dereuromark: Unfortunately no. I've switched away from phinx as I found it to limited.
I've decided to write and release my own migration tool which utilizes plain SQL with some templating sprinkled on top of everything to allow some things to change on runtime.
With that I can define tables stored procedures etc with the DSL that database provides.
