### ISSUE TITLE
Seeders can call other Seeders

### ISSUE THREAD

**Issue by robmorgan** [cakephp/phinx#737]
Similar to Laravel, Seed classes should be able to call other seed classes using a `call()` method.

This would allow developers to create parent seed classes and control the execution order of the children.

It might cause issues though as the default seed:run action is greedy and attempts to run everything. We are debating whether to go this route or use a priority flag instead.

**Comment by antonienko** [comment]
Tell me what do you think about [this proposal](https://github.com/robmorgan/phinx/pull/790)

**Comment by HavokInspiration** [comment]
+1 for the feature.
This would indeed be more convenient.
We currently have users asking for the same behavior as Laravel for the CakePHP migrations plugin.

Implementing a ``call()`` method should be enough. This would only run the seeder(s ?) passed as the argument(s) and would give more control to the users when seeding their DB.

**Comment by enygma** [comment]
+1 on this feature from me too. I just came across a setup where there's dependencies like this and it would be very handy.

**Comment by alejoluc** [comment]
+1 for this

**Comment by parfumix** [comment]
+1

**Comment by ratno** [comment]
wow the proposal is more than a year back #790 
+1 hopefully this will be merge soon..

**Comment by derpoho** [comment]
+1

**Comment by lorenzo** [comment]
People voting +1: would you like to send a pull request with the new feature?

**Comment by millejano** [comment]
+1

**Comment by lorenzo** [comment]
I'm going to lock this thread. If anyone ones to implement the feature, please open a pull request.

**Comment by dereuromark** [comment]
Closing as this has become stale and no one was interested in providing a pull request. If someone wants to PR it, go ahead.
