### ISSUE TITLE
Selectable migrate and rollback

### ISSUE THREAD

**Issue by comm1x** [cakephp/phinx#760]
When working with git and create migrations in different branches, often it turns out the situation, when we need to revert migration, which is located between the other migrations and it is not the last.

When I try to rollback it, I get an error, because phinx want to revert all interim migrations.

I propose to add the ability to make selective migration, and selective rollback. For example:

```
vendor/bin/phinx rollback --only AddSomeColumn
vendor/bin/phinx migrate --only 20160122100925
```

Thank you

**Comment by daniel-gomes-sociomantic** [comment]
@comm1x it looks like you have the same problem as https://github.com/robmorgan/phinx/issues/628 (I might be wrong), would https://github.com/robmorgan/phinx/pull/745 help you?

**Comment by daniel-gomes-sociomantic** [comment]
also, the ability to rollback individual migrations was already done in https://github.com/robmorgan/phinx/pull/451

**Comment by rquadling** [comment]
There are several possible solutions in the pipeline. Just need to get some input from the package maintainer. In the mean time, you can always fork the various PRs and roll your own version of Phinx.

**Comment by dereuromark** [comment]
A solution has been implemented.
