### ISSUE TITLE
renameTable random droptable

### ISSUE THREAD

**Issue by frazr** [cakephp/phinx#769]
Baked a migration in CakePhp and accidentally ran 
`$this->adapter->renameTable('article_attribute_values', 'articles_attribute_values');`
which resulted in 7 random tables beeing dropped.

Thought thas was very odd behavior for what i assume is a a wrong object call.

**Comment by HavokInspiration** [comment]
Hi @frazr.

You should open a ticket in the CakePHP migrations plugin repo : https://github.com/cakephp/migrations/issues

Please also add a bit more details (DB server, version of CakePHP / the plugin used and migrations file examples : everything that will help us reproduce the issue you are having).

Thank you !

**Comment by robmorgan** [comment]
@frazr very concerning. I'd be interested to know what is happening. please let myself or the CakePHP guys know!

**Comment by dereuromark** [comment]
@frazr any update?

**Comment by frazr** [comment]
Long time since this happens i have moved  on, u cancer discard the issue i
guess :)

Den 1 mars 2018 21:19 skrev "Mark Sch." <notifications@github.com>:

**Comment by frazr** [comment]
*can

Den 1 mars 2018 21:21 skrev "Nicklas Ring" <niklatz@gmail.com>:
