### ISSUE TITLE
Configuration for base class used in SeedCreate command

### ISSUE THREAD

**Issue by rewmike** [cakephp/phinx#773]
It would be great to have a configuration option [`seed_base_class`](https://github.com/robmorgan/phinx/blob/df8933786806848fbf330f88d69998f29c29d8c4/src/Phinx/Console/Command/SeedCreate.php#L117-L121) just like [`migration_base_class`](https://github.com/robmorgan/phinx/blob/df8933786806848fbf330f88d69998f29c29d8c4/src/Phinx/Console/Command/Create.php#L210-L214).

**Comment by dead23angel** [comment]
Join us, a very useful option. I use to create the migration Laravel Eloquent and would like to use oxides as a package from laravel, but it need this option

sory my bad english

**Comment by dead23angel** [comment]
I realized https://github.com/robmorgan/phinx/pull/898
