### ISSUE TITLE
Using hasTable() inside of change() method

### ISSUE THREAD

**Issue by viteksafronov** [cakephp/phinx#783]
I'm trying to bring phinx to my existing database. Now I'm rewriting my struct.sql into a set of the separate migrations.
Of course if I run these migrations, I get a 'table already exists' error, because all these tables are already in my DB with needed data.
Is it normal to check the table existense with hasTable() method inside of my change() method? Or I have to separate my change() to up() and down() for this case?
It's not clear for me from docs right now.

**Comment by otaruMendez** [comment]
Yes @viteksafronov. I think it is advisable to always check if a table exists before migrating.

**Comment by dereuromark** [comment]
Maybe someone can PR a note into the docs?
