### ISSUE TITLE
Feature Request: Update several columns in the database.

### ISSUE THREAD

**Issue by otaruMendez** [cakephp/phinx#786]
I would love to be able to update a column values in my DB, e.g:
`update table set col_1 = val where col_2 = val2`

**Comment by priidikvaikla** [comment]
What is the use case here, how would you use it. Can you provide some example?

**Comment by rquadling** [comment]
You can use ``$this->query('update table set col_1 = val where col_2 = val2');``, but you would have to manually code ``up()`` and ``down()`` separately.

**Comment by dereuromark** [comment]
Working solution seems enough then. Closing.
