### ISSUE TITLE
Cannot update table comment

### ISSUE THREAD

**Issue by WillGibson** [cakephp/phinx#802]
It's quite possible I'm doing something wrong, but I cannot get a table comment to update with this code...

```
$table = $this->table('some_table');
$table->setOptions(['comment' => 'No longer in use by the Something app']);
$table->save();
```

Is it me, or is this a bug?

**Comment by catharsisjelly** [comment]
Not a bug I think just not an implemented feature https://github.com/robmorgan/phinx/blob/0.5.x-dev/src/Phinx/Db/Adapter/MysqlAdapter.php#L251 allows you to add options which get done during table creation but there is no ALTER for just the table as far as I can see

**Comment by dereuromark** [comment]
Are you able to provide a patch with your suggested changes as PR?

**Comment by WillGibson** [comment]
@dereuromark I can't just now, all my spare time is being sucked up by looking for a new job, which is good really, I think.

**Comment by othercorey** [comment]
Added in https://github.com/cakephp/phinx/pull/1393
