### ISSUE TITLE
Feature Request: change several columns in single query

### ISSUE THREAD

**Issue by daniel-gomes-sociomantic** [cakephp/phinx#815]
Currently, when writing a migration like:

``` php
$table = $this->table('table')
    ->changeColumn('col1', 'type1', array('...'))
    ->changeColumn('col2', 'type2', array('...'))
    ->changeColumn('col3', 'type3', array('...'))
    ->save();
```

Phinx will execute this in 3 database queries like:

``` sql
ALTER TABLE `table` CHANGE `col1` `col1` type1 ...;
ALTER TABLE `table` CHANGE `col2` `col2` type2 ...;
ALTER TABLE `table` CHANGE `col3` `col3` type3 ...;
```

Which is fine for most cases, but I just had a situation where because of several columns with invalid default values, each of those operations would fail because of the other columns and the only way to successfully run the operation was to run all of the `CHANGE` bits at the same time like:

``` sql
ALTER TABLE `table` 
    CHANGE `col1` `col1` type1 ...,
    CHANGE `col2` `col2` type2 ...,
    CHANGE `col3` `col3` type3 ...;
```

So it would be nice to have a way to run multiple `changeColumn` operations (for the same table) in a single query.

Looking at the code, this doesn't look too difficult to implement, so I could PR it if there is indeed interest and it's not just me with a very edge case :-)

**Comment by dereuromark** [comment]
Yes, please do so and PR your suggested changes.

**Comment by ahfeel** [comment]
This would be REALLY REALLY useful. When touching big tables in productions if you add 2 columns it takes twice the amount of time needed..
@dereuromark @daniel-gomes-sociomantic Have you guys done anything towards fixing this ?

**Comment by lorenzo** [comment]
This is already implemented, and in the master branch. Will be released soon

**Comment by ahfeel** [comment]
Ahh great ! Thank you @lorenzo. Do you have any approx ETA for the next big release of Phinx ?

**Comment by lorenzo** [comment]
I expect a week or two, I'd like to add one more feature before releasing

**Comment by arnisjuraga** [comment]
Could You please reference how to use this method? Did not find any commits or documentation. 
I have exactly the same issue as @daniel-gomes-sociomantic

**Comment by lorenzo** [comment]
@arnisjuraga just use the latest release, you don't need to do anything specific to make this happen
