### ISSUE TITLE
execute() doesn't close PDO Cursor, blocks further queries

### ISSUE THREAD

**Issue by SilkAndSlug** [cakephp/phinx#816]
I'm trying to add a 'hasIndex' method, so I can call it before calling addIndex. It appears that execute() is leaving the PDO Cursor open, preventing the addIndex from succeeding. Here's some code that triggers the error:

```
public function up()  {
    $this->execute("SHOW KEYS FROM attendances WHERE Key_name = 'bar';");
    $this->table('attendances')->addIndex(array('baz'));
}
```

and here's the error:

```
[PDOException]
SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other 
unbuffered queries are active.  Consider using PDOStatement::fetchAll().  
Alternatively, if your code is only ever going to run against mysql, you 
may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY 
attribute.
```

I suggest that execute() call PDO::closeCursor.

**Comment by SilkAndSlug** [comment]
There's a workaround: instead of calling execute() and checking the return value, call fetchAll and count the rows.

**Comment by dereuromark** [comment]
Are you able to provide a patch with your suggested changes as PR?

**Comment by lorenzo** [comment]
This is expected for queries that returns rows. Use `query()` or the new query builder interface
