### ISSUE TITLE
how to generate migrations from an existing database

### ISSUE THREAD

**Issue by angusty** [cakephp/phinx#820]
how to generate migrations from an existing database, including indexes and foreign keys?

**Comment by jmbeekman** [comment]
I'm working on a script to extend https://github.com/gwa/MySQL2Phinx in an attempt to fully cover MySQL, and then probably PostGREs

**Comment by odan** [comment]
Hi! You could try to generate a migration with [odan/phinx-migrations-generator](https://github.com/odan/phinx-migrations-generator)

**Comment by yoX64** [comment]
Great work, @odan! Thank you so much!

**Comment by dereuromark** [comment]
You can link this in the docs maybe.

**Comment by delboy1978uk** [comment]
this is just what i was looking for :-D Is it able to create inserts for the existing data in the database?

**Comment by dereuromark** [comment]
Duplicate of https://github.com/cakephp/phinx/issues/350 ?
