### ISSUE TITLE
table name not quoted in PdoAdapter::getVersionLog()

### ISSUE THREAD

**Issue by qyanu** [cakephp/phinx#825]
PdoAdapter.php line 377  (in tagged version 0.5.3) reads:
`$rows = $this->fetchAll(sprintf('SELECT * FROM %s ORDER BY version ASC', $this->getSchemaTableName()));`

the identifier MUST be quoted, for example using $this->quoteTableName()

**Comment by qyanu** [comment]
made push request with fix, which just wraps table name with $this->quoteTableName()

**Comment by rquadling** [comment]
Same goes for SqlServerAdapter::migrated(), PostgresAdapter::migrated(), PdoAdapter::createSchemaTable(), PdoAdapter::migrated().

**Comment by dereuromark** [comment]
Resolved with https://github.com/cakephp/phinx/pull/1235 ?
