### ISSUE TITLE
Create migration in multiple postgres schema

### ISSUE THREAD

**Issue by rsdevigo** [cakephp/phinx#828]
So, I think is a good feature if u can create table with the schema name split by a dot in the migration file.
Like:

```
$table = $this->table('pga.contact', array('id' => false, 'primary_key' => array('id')));
$table->addColumn('id', 'integer', array('identity' => true))
            ->addColumn('_ws_fk_location', 'string')
            ->create();
```

Today the phinx create a SQL statement with CREATE TABLE ( [schema config phinx.yml].tablename .... )

I think if the table name has a dot the SQL statement can ignore the schema config phinx.yml.

**Comment by MikeVelazcoMtz** [comment]
I think that is not a wise option to alter different databases using only one block of migrations/seeds/configurations. check #180 and specifically the answer from @temperedvision

**Comment by rsdevigo** [comment]
But, the thing here is the different schema and not different databases. Cause the postgres allow u create different schema (sets of table) in the same database, for organization reasons.

**Comment by rquadling** [comment]
As you can now control your `migration_base_class`, you can subclass `\Phinx\Migration\AbstractMigration` and override the methods that receive a $table parameter.

In there, you can massage your $table as you see fit.

I would use the `init()` method to get a copy of the PhinxConfig into the subclass, and then use that to extract your postgres schema config entry and attach it where necessary to the $table in your subclass.

Hope that gives you some idea of how you can implement your own specifics without needing to have them supported in the main codebase.

Come back if you need any further help.

**Comment by dereuromark** [comment]
PR open
