### ISSUE TITLE
Cannot create migrations with paths using glob patterns

### ISSUE THREAD

**Issue by mbrodala** [cakephp/phinx#833]
Given a `migrations` path with a glob pattern new migrations will be created in a directory literally named after the pattern. Thus:

```
paths:
  migrations: foo/*/migrations
```

Executing `phinx create FooBar` will create a new migration in the path `foo/*/migrations/20160503134337_foo_bar.php` literally.

Not sure how to tackle this properly but maybe ask the user where to put the migration if a glob pattern is used?

**Comment by rquadling** [comment]
The use of glob patterns in the migrations path is not properly supported due to this issue. 

Make sure the documentation is updated too.

Could be worth looking at https://github.com/robmorgan/phinx/issues/232 also.

**Comment by mbrodala** [comment]
Yeah, everything works fine with the latest releases, thanks. :-)
