### ISSUE TITLE
Rollback question

### ISSUE THREAD

**Issue by karborator** [cakephp/phinx#837]
Hello , 

I have migration with method change , which rename the table name and after that adds new column.
Executing of this migration is all good.

But when I do rollback , it does not drop the column previously was added .  
So after I rollback the name of the table is reversed but the special_column is not removed .. 

Is there a way to run a fully rollback and how ?

```
class MrAscioContactHandle extends AbstractMigration
{ 
    public function change()
    {
        $table = $this->table('table_name');
        $table->rename('new_table_name');

        $renamedTable = $this->table('new_table_name');
        if (! $renamedTable->hasColumn('special_column')) {
            $renamedTable->addColumn('special_column', 'integer');
            $renamedTable->save();
        }

    }
}

```

**Comment by JoeBengalen** [comment]
Removing the column would be wrong behaviour I think, because it could be the case that the column was already there and it was not added during the migration. Doing a rollback this cannot be known, so  it cannot safely delete the column.

What happens when you remove the `hasColumn` check?
