### ISSUE TITLE
Is there a way to fake initial migration?

### ISSUE THREAD

**Issue by aalexgabi** [cakephp/phinx#841]
The idea is to create an initial migration and register it as applied in an existent database (phinxlog table). Here is an example [in Django migrations](https://docs.djangoproject.com/en/1.9/ref/django-admin/#cmdoption-migrate--fake-initial).

Is this possible with Phinx?

**Comment by aalexgabi** [comment]
I use things like `CREATE TABLE IF NOT EXISTS` as a workaround.

**Comment by adrian-enspired** [comment]
>I use things like `CREATE TABLE IF NOT EXISTS` as a workaround.

Same.  I'm considering adding a sanity check afterwards, like `SELECT col,names,i,expect FROM the_table WHERE false;`  …so a warning will be thrown if something went wrong (e.g., the table existed but was not in the state I expected it to be).

**Comment by adrian-enspired** [comment]
followup: I added an "initial" migration that actually checks the schema. Basically, I am looping and comparing the results of `DESCRIBE {$table}` to what the migration expects.  There are three possible results:
* schema is empty (i.e., a new install).
* schema exists and is as expected (good; do nothing).
* schema exists but doesn't match expected state (throw an error).

**Comment by odan** [comment]
Hi! You could try to generate a migration with [odan/phinx-migrations-generator](https://github.com/odan/phinx-migrations-generator)

**Comment by dereuromark** [comment]
Sounds like someone could write a few sentences here in docs.

**Comment by dereuromark** [comment]
I also sometimes use
```php
if ($this->hasTable(...)) {
    return;
}
```
