### ISSUE TITLE
use the input interface

### ISSUE THREAD

**Issue by LeniM** [cakephp/phinx#858]
Hi,

i am surprised to find out you can not access the input interface, as simple as it is for the output.

Requesting confirmation before updates can be very usefull and much nicer than displaying the query in the command line interface for the user to run it ...

Has anyone faced anything related to this feature ?

Cheers :)

**Comment by rquadling** [comment]
Strangely enough, looking at this right now. We have custom commands based around Phinx and needed to do some work in the init() method based upon the input criteria. Requires https://github.com/rquadling/phinx/tree/feature/SetOutputBeforeInit, which I'm waiting on some feedback from @robmorgan. I've nearly finished a new branch adding InputInterface throughout the code base (allowing a custom migration to access input parameters for custom commands).

**Comment by rquadling** [comment]
Take a look at https://github.com/rquadling/phinx/tree/feature/AddSupportForInputInterface.

This is sitting in PR #859.

**Comment by rquadling** [comment]
Released in 0.6.1
