### ISSUE TITLE
SQLite dropForeignKey causes all other columns data to be removed.

### ISSUE THREAD

**Issue by stevenimle** [cakephp/phinx#860]
When running a migration on an SQLite database, I created a table with a foreign key that had a unique index with another column in that table. I later added a table that would sit in between these two tables and tried to migrate the key to the new table. When moving the index, I performed an update on the columns and the data was updated successfully. When I removed the index, there was also no problem. However, when I dropped the foreign key, every other column (excluding the primary key) was set to NULL.

Please let me know what other information is needed to reproduce this bug.

**Comment by dereuromark** [comment]
Is this still an open issue?

**Comment by lorenzo** [comment]
This is the normal MYSQL behaviour when using a foreign key `CASCASE SET NULL`
