### ISSUE TITLE
Support milliseconds for timestamp columns on adapters that support it.

### ISSUE THREAD

**Issue by rquadling** [cakephp/phinx#904]
In mysql, `CURRENT_TIMESTAMP` can also be `CURRENT_TIMESTAMP(x)` where `x` is from 0 to 6.

In addition to that, `ON UPDATE CURRENT_TIMESTAMP(x)` can be used for the `updated_at` column, thereby providing an automatic record to a high resolution of when the row was updated.

For example, in MySQL

``` sql
  `createdAt` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updatedAt` TIMESTAMP(6) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(6),
```

Research what options exist for Postgres, Microsoft SQL Server and SQLite.

**Comment by dereuromark** [comment]
Is this still open?

**Comment by othercorey** [comment]
I believe support was added for both mysql and postgres.
