### ISSUE TITLE
Add a --dry-run option

### ISSUE THREAD

**Issue by rquadling** [cakephp/phinx#906]
We will soon have the ability to interact with migrations based upon execution time, rather than creation time.

In preparation of that, having a dry run option to operate with `-t|--target|-d|--date` and displaying the status page with an extra column, showing what will be migrated/rollbacked would be useful.

**Comment by dereuromark** [comment]
Are you able to provide a pull request with your suggested changes?

**Comment by lorenzo** [comment]
This is done already
