### ISSUE TITLE
Support for named foreign key constraint in MySQL adapter

### ISSUE THREAD

**Issue by tomzx** [cakephp/phinx#92]
Hi,

Based on the little experience I have with Phinx, it seems impossible to specify the name of the foreign key I want when creating a new foreign key. Based on the code in robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php, either you have a foreign key with a constraint name OR a foreign key with an automatically generated name.

See https://gist.github.com/tomzx/5663921/revisions for a "potential" quick fix.

**Comment by wrah** [comment]
Hi, Is this issue still up for grabs ? I would love to do the necessary to see it merged.

**Comment by ehowardtillit** [comment]
Hi, Is this issue still up for grabs ? I would love to do the necessary to see it merged.

**Comment by blaind** [comment]
+1

**Comment by nkoo** [comment]
+1

**Comment by Yess11** [comment]
+1

**Comment by Yess11** [comment]
Hello, what's the plan with this feature?

**Comment by jdenoc** [comment]
It looks like you can set a foreign key name using the `constraint` option.

```php
$table = $this->table('your_table');
$table->addForeignKey('foreign_id', 'reference_table', array('id'), array('constraint'=>'your_foreign_key_name'));
$table->save();
```


This is valid as of
```
$ vendor/bin/phinx --version
Phinx by Rob Morgan - https://phinx.org. version 0.6.5
```

**Comment by othercorey** [comment]
Constraint names are supported through the `constraint` option.
