### ISSUE TITLE
Configuration value for default schema

### ISSUE THREAD

**Issue by jradtilbrook** [cakephp/phinx#937]
I'm having issues where I want to set a default schema for all environments. The current settings do not pick up a 'default_schema' (or similar YAML property) and I must declare 'schema' for each environment. I think this feature would be quite useful.

**Comment by rquadling** [comment]
Extending `\Phinx\Config\Config::getEnvironment()` to merge all/any non-array properties whose name starts with `'default_'` into the environment could be an option here. Or adding `'default_schema'` to a small list that include the current `'default_migration_table'` and pulling in that list into the environment.

Either a prefix based merge or a whitelist approach, both would get the job done.

Do you think you could make a pull request?

**Comment by jradtilbrook** [comment]
Sure thing! What branch would you prefer for the changes?

**Comment by rquadling** [comment]
0.7.x-dev please.

**Comment by jradtilbrook** [comment]
I'm closing this to remove it from my pending list. The associated PR I did ended up not being accepted
