### ISSUE TITLE
Rollback with target id

### ISSUE THREAD

**Issue by jradtilbrook** [cakephp/phinx#938]
There is an issue with rolling back using the -t option and not passing a valid parameter. If passing a string or a number with a missing digit it will rollback all migrations. This is because from https://github.com/robmorgan/phinx/blob/0.6.x-dev/src/Phinx/Migration/Manager.php#L390 to line 409 the logic is wrong. As long as any number supplied is less than the first migration, it will rollback all. It should be an explicit check for 0, not a comparison against the first migration id.

The current concept of rolling back to a target "id" doesn't make much sense anyway. Would it not be better to specify the migration name rather than the migration id since the -d date parameter basically does what -t does?

**Comment by rquadling** [comment]
Can you take a look at 0.7.x-dev branch. A LOT of reworking has been done there. It isn't released yet as we are still testing. More eyes on it would be REALLY useful.

**Comment by rquadling** [comment]
And can you rebase your code onto the 0.7.x-dev branch. :-)

**Comment by jradtilbrook** [comment]
Yeah I'll take a deeper look. I've already seen that this fix isn't implemented yet. Will do!

**Comment by tariquesani** [comment]
#945 seems to fix this but for some reason was closed. The failing tests in #945 just need to be re-triggered.

**Comment by lorenzo** [comment]
@tariquesani would you like to fix that PR?

**Comment by lorenzo** [comment]
@tariquesani as in, clone his branch and open another pull request that will trigger new tests.

**Comment by jradtilbrook** [comment]
Project owners could just hit retest in this thread or Travis. Or I could try re-pushing to trigger the webhooks if that's easier?

**Comment by tariquesani** [comment]
+1 there will be a retest option available to you @lorenzo or @jradtilbrook could push something again. I don't need to takeover the PR

**Comment by lorenzo** [comment]
@jradtilbrook please re-push, I currently have no access to travis

**Comment by lorenzo** [comment]
I'm closing this as there is a candidate PR that solves the issue
