### ISSUE TITLE
Add auto increment property to Column class

### ISSUE THREAD

**Issue by czogori** [cakephp/phinx#94]
We can add autoIncrement property to Column class.

Then we can write in Phinx\Db\Adapter\MysqlAdapter (line 792)

``` php
 $def .= ($column->isIdentity() && $column->isAutoIncrement()) ? ' AUTO_INCREMENT' : '';
```

instead of

``` php
 $def .= ($column->isIdentity()) ? ' AUTO_INCREMENT' : '';
```

At this point PK is always auto increment.

Btw. for example in Postgres we can add many columns with auto increment ergo this is feature for the future ;)

**Comment by frazr** [comment]
Not working "auto_increment" is not a valid column option.

**Comment by VladimirKatrich** [comment]
@frazr, you can try use **'identity' => true** option:

`->addColumn('id', 'integer', array('signed' => false, 'identity' => true))`

**Comment by Largit** [comment]
"identity" is not a valid column option.
At least in v0.4.0
