### ISSUE TITLE
Migration path(-es) per environment

### ISSUE THREAD

**Issue by garex** [cakephp/phinx#948]
Example use case:
- Different environments per db driver

Possible workaround is to use another config, but same could be said for environments: just use different config per environment.

**Comment by rquadling** [comment]
It could be possible to introduce additional config per environment, but I don't see how it could be done per db driver as there is no per-db config as such. Maybe the credential set is different depending upon the driver, but they are tied to an environment.

**Comment by dereuromark** [comment]
Are you able to provide a patch with your suggested changes as PR?
