### ISSUE TITLE
Status code in bash when migration fails 

### ISSUE THREAD

**Issue by Mykolaichenko** [cakephp/phinx#963]
Hello, i have some bad issue with phinx migrate. 
We have deploy pipeline, that including one step with migrations. In our case **migration is fails**, but **phinx reported to shell that all is ok** - status code 0. 

Please, review this: 

```
 == 20160912134015 Un6064UsersContract: migrating


  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for
  the right syntax to use near '
              from users WHERE company_id IS NOT NULL and delete_date = 0
              GROUP BY com' at line 2
```

```
echo $?
0
```

Please, fix this troubles, because all who use phinx in deploy process can break own production environment. 
Thanks a lot.

**Comment by airdrummingfool** [comment]
Until this is fixed, here's a possible workaround: after running the migrations, run `phinx status` and check the exit code. If it is non-zero, then there are still down or missing migrations, which means that your migrations did not complete successfully.

Note that if an exception is thrown when checking `status`, the exit code will also be `1` (see #806).

**Comment by dereuromark** [comment]
Are you able to provide a patch with your suggested changes as PR?

**Comment by othercorey** [comment]
Added in https://github.com/cakephp/phinx/pull/1462
