### ISSUE TITLE
PHPUnit warnings about mocks

### ISSUE THREAD

**Issue by shadowhand** [cakephp/phinx#970]
Using PHPUnit 5.6.1 results in a lot of warnings:

```
PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead
```

I think phpunit version lock should be more strict or tests should be updated.

**Comment by chilimatic** [comment]
@shadowhand i fixed this in https://github.com/robmorgan/phinx/pull/976
