### ISSUE TITLE
Get environment accessible from a migration

### ISSUE THREAD

**Issue by gsi-delmo** [cakephp/phinx#984]
Conceptually, the key _default_database_ in phinx.yml file should be named _default_environment_. Also the environment value should be accessible from a migration, something like:

`$this->get_environment()`

I know that right now I can get environment (parameter **e**) if it is used when phinx is executed but if no environment parameter is passed, there is no way to know the **default_environment**.

**Comment by robmorgan** [comment]
@gsi-delmo hi,

yes you are correct - this will be even more of a problem when we support multiple databases per environment.

Rob

**Comment by MasterOdin** [comment]
PR opened to rename `default_database` to `default_environment` (as that's more accurate to what's going on).

For getting the value of the currently used environment within a migration, you can do `$this->getEnvironment()` which returns the string value, and was added in 0.9.3.
