### ISSUE TITLE
sqlite adapter is suppressing errors

### ISSUE THREAD

**Issue by aldas** [cakephp/phinx#986]
MySql/Postgres have `array(\PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION)` set for PDO options which enables exceptions when dml/ddl fail but sqlite does not have it.

so if you have for example faulty DDL
```
$table = $this->table('users');
$table->addColumn('username', 'text')
    ->addColumn('username', 'integer')
    ->create();
```

this migration is applied "successfully" but no table is created

but if you would add `$db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);` into `SQLiteAdapter.connect()` it would fail with

> [PDOException]                                                    
  SQLSTATE[HY000]: General error: 1 duplicate column name: username

**Comment by dereuromark** [comment]
What is your suggested fix?

**Comment by aldas** [comment]
me PR to fix this https://github.com/cakephp/phinx/pull/989 was closed as already implemented. this is pretty old issue so I assume it got fixed
