### ISSUE TITLE
sqlite adapter forgets to recreate indexes/triggers on drop column or adding foreign key to existing table

### ISSUE THREAD

**Issue by aldas** [cakephp/phinx#988]
As Sqlite does not support alter table drop column syntax Phinx creates tmp table and renames it to old table when column is dropped. This works fine but if this old table had indexes/triggers those are not created on new table but that new table should be same as old except that column related stuff.

**Comment by aldas** [comment]
Same goes for SQLiteAdapter `addForeignKey` - when new table is created it does not recreate indexes

**Comment by dereuromark** [comment]
Are you able to provide a patch with your suggested changes as PR?
